package com.rc.project.vo;

import java.math.BigDecimal;
import java.util.Date;

public class EpContract {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.EP_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String epSno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.BG_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String bgSno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SNUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal ctSnum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SCONTENT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctScontent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_DTIME
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date ctDtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_NPAYRATIO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctNpayratio;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_NMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal ctNmoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_NIMPORT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal ctNimport;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SNOIMPORT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal ctSnoimport;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SOWNER
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSowner;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SUNITMAN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSunitman;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_STELE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctStele;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SPARTYB
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSpartyb;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SUNITMANB
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSunitmanb;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_STELEB
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSteleb;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_NISIMPORT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctNisimport;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SISLYJ
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSislyj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_NLYJSUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal ctNlyjsum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SISZBJ
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSiszbj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_NZBJSUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal ctNzbjsum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_NCONTENT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctNcontent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SGAINMAN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSgainman;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SGAINTELE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSgaintele;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SGAINADDR
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSgainaddr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SISDEL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSisdel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SISVALID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSisvalid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SREPLYBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSreplyby;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SREPLYDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date ctSreplydate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SALTERBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSalterby;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SALTERDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date ctSalterdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF7
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF8
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF9
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF10
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF11
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF12
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF13
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF14
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF15
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF16
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF17
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF18
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF19
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_SDEF20
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSdef20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_NDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal ctNdef1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_NDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal ctNdef2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_NDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal ctNdef3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_NDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal ctNdef4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_NDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal ctNdef5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_TDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date ctTdef1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_TDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date ctTdef2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_TDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date ctTdef3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_TDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date ctTdef4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_TDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date ctTdef5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_CONTRACT.CT_TDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date ctTdef6;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SNO
     *
     * @return the value of EP_CONTRACT.CT_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSno() {
        return ctSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SNO
     *
     * @param ctSno the value for EP_CONTRACT.CT_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSno(String ctSno) {
        this.ctSno = ctSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.EP_SNO
     *
     * @return the value of EP_CONTRACT.EP_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getEpSno() {
        return epSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.EP_SNO
     *
     * @param epSno the value for EP_CONTRACT.EP_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setEpSno(String epSno) {
        this.epSno = epSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.BG_SNO
     *
     * @return the value of EP_CONTRACT.BG_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getBgSno() {
        return bgSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.BG_SNO
     *
     * @param bgSno the value for EP_CONTRACT.BG_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setBgSno(String bgSno) {
        this.bgSno = bgSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SNUM
     *
     * @return the value of EP_CONTRACT.CT_SNUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getCtSnum() {
        return ctSnum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SNUM
     *
     * @param ctSnum the value for EP_CONTRACT.CT_SNUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSnum(BigDecimal ctSnum) {
        this.ctSnum = ctSnum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SCONTENT
     *
     * @return the value of EP_CONTRACT.CT_SCONTENT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtScontent() {
        return ctScontent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SCONTENT
     *
     * @param ctScontent the value for EP_CONTRACT.CT_SCONTENT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtScontent(String ctScontent) {
        this.ctScontent = ctScontent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_DTIME
     *
     * @return the value of EP_CONTRACT.CT_DTIME
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getCtDtime() {
        return ctDtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_DTIME
     *
     * @param ctDtime the value for EP_CONTRACT.CT_DTIME
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtDtime(Date ctDtime) {
        this.ctDtime = ctDtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_NPAYRATIO
     *
     * @return the value of EP_CONTRACT.CT_NPAYRATIO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtNpayratio() {
        return ctNpayratio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_NPAYRATIO
     *
     * @param ctNpayratio the value for EP_CONTRACT.CT_NPAYRATIO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtNpayratio(String ctNpayratio) {
        this.ctNpayratio = ctNpayratio;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_NMONEY
     *
     * @return the value of EP_CONTRACT.CT_NMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getCtNmoney() {
        return ctNmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_NMONEY
     *
     * @param ctNmoney the value for EP_CONTRACT.CT_NMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtNmoney(BigDecimal ctNmoney) {
        this.ctNmoney = ctNmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_NIMPORT
     *
     * @return the value of EP_CONTRACT.CT_NIMPORT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getCtNimport() {
        return ctNimport;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_NIMPORT
     *
     * @param ctNimport the value for EP_CONTRACT.CT_NIMPORT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtNimport(BigDecimal ctNimport) {
        this.ctNimport = ctNimport;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SNOIMPORT
     *
     * @return the value of EP_CONTRACT.CT_SNOIMPORT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getCtSnoimport() {
        return ctSnoimport;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SNOIMPORT
     *
     * @param ctSnoimport the value for EP_CONTRACT.CT_SNOIMPORT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSnoimport(BigDecimal ctSnoimport) {
        this.ctSnoimport = ctSnoimport;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SOWNER
     *
     * @return the value of EP_CONTRACT.CT_SOWNER
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSowner() {
        return ctSowner;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SOWNER
     *
     * @param ctSowner the value for EP_CONTRACT.CT_SOWNER
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSowner(String ctSowner) {
        this.ctSowner = ctSowner;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SUNITMAN
     *
     * @return the value of EP_CONTRACT.CT_SUNITMAN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSunitman() {
        return ctSunitman;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SUNITMAN
     *
     * @param ctSunitman the value for EP_CONTRACT.CT_SUNITMAN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSunitman(String ctSunitman) {
        this.ctSunitman = ctSunitman;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_STELE
     *
     * @return the value of EP_CONTRACT.CT_STELE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtStele() {
        return ctStele;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_STELE
     *
     * @param ctStele the value for EP_CONTRACT.CT_STELE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtStele(String ctStele) {
        this.ctStele = ctStele;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SPARTYB
     *
     * @return the value of EP_CONTRACT.CT_SPARTYB
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSpartyb() {
        return ctSpartyb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SPARTYB
     *
     * @param ctSpartyb the value for EP_CONTRACT.CT_SPARTYB
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSpartyb(String ctSpartyb) {
        this.ctSpartyb = ctSpartyb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SUNITMANB
     *
     * @return the value of EP_CONTRACT.CT_SUNITMANB
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSunitmanb() {
        return ctSunitmanb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SUNITMANB
     *
     * @param ctSunitmanb the value for EP_CONTRACT.CT_SUNITMANB
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSunitmanb(String ctSunitmanb) {
        this.ctSunitmanb = ctSunitmanb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_STELEB
     *
     * @return the value of EP_CONTRACT.CT_STELEB
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSteleb() {
        return ctSteleb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_STELEB
     *
     * @param ctSteleb the value for EP_CONTRACT.CT_STELEB
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSteleb(String ctSteleb) {
        this.ctSteleb = ctSteleb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_NISIMPORT
     *
     * @return the value of EP_CONTRACT.CT_NISIMPORT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtNisimport() {
        return ctNisimport;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_NISIMPORT
     *
     * @param ctNisimport the value for EP_CONTRACT.CT_NISIMPORT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtNisimport(String ctNisimport) {
        this.ctNisimport = ctNisimport;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SISLYJ
     *
     * @return the value of EP_CONTRACT.CT_SISLYJ
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSislyj() {
        return ctSislyj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SISLYJ
     *
     * @param ctSislyj the value for EP_CONTRACT.CT_SISLYJ
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSislyj(String ctSislyj) {
        this.ctSislyj = ctSislyj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_NLYJSUM
     *
     * @return the value of EP_CONTRACT.CT_NLYJSUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getCtNlyjsum() {
        return ctNlyjsum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_NLYJSUM
     *
     * @param ctNlyjsum the value for EP_CONTRACT.CT_NLYJSUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtNlyjsum(BigDecimal ctNlyjsum) {
        this.ctNlyjsum = ctNlyjsum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SISZBJ
     *
     * @return the value of EP_CONTRACT.CT_SISZBJ
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSiszbj() {
        return ctSiszbj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SISZBJ
     *
     * @param ctSiszbj the value for EP_CONTRACT.CT_SISZBJ
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSiszbj(String ctSiszbj) {
        this.ctSiszbj = ctSiszbj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_NZBJSUM
     *
     * @return the value of EP_CONTRACT.CT_NZBJSUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getCtNzbjsum() {
        return ctNzbjsum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_NZBJSUM
     *
     * @param ctNzbjsum the value for EP_CONTRACT.CT_NZBJSUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtNzbjsum(BigDecimal ctNzbjsum) {
        this.ctNzbjsum = ctNzbjsum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_NCONTENT
     *
     * @return the value of EP_CONTRACT.CT_NCONTENT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtNcontent() {
        return ctNcontent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_NCONTENT
     *
     * @param ctNcontent the value for EP_CONTRACT.CT_NCONTENT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtNcontent(String ctNcontent) {
        this.ctNcontent = ctNcontent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SGAINMAN
     *
     * @return the value of EP_CONTRACT.CT_SGAINMAN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSgainman() {
        return ctSgainman;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SGAINMAN
     *
     * @param ctSgainman the value for EP_CONTRACT.CT_SGAINMAN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSgainman(String ctSgainman) {
        this.ctSgainman = ctSgainman;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SGAINTELE
     *
     * @return the value of EP_CONTRACT.CT_SGAINTELE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSgaintele() {
        return ctSgaintele;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SGAINTELE
     *
     * @param ctSgaintele the value for EP_CONTRACT.CT_SGAINTELE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSgaintele(String ctSgaintele) {
        this.ctSgaintele = ctSgaintele;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SGAINADDR
     *
     * @return the value of EP_CONTRACT.CT_SGAINADDR
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSgainaddr() {
        return ctSgainaddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SGAINADDR
     *
     * @param ctSgainaddr the value for EP_CONTRACT.CT_SGAINADDR
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSgainaddr(String ctSgainaddr) {
        this.ctSgainaddr = ctSgainaddr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SISDEL
     *
     * @return the value of EP_CONTRACT.CT_SISDEL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSisdel() {
        return ctSisdel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SISDEL
     *
     * @param ctSisdel the value for EP_CONTRACT.CT_SISDEL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSisdel(String ctSisdel) {
        this.ctSisdel = ctSisdel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SISVALID
     *
     * @return the value of EP_CONTRACT.CT_SISVALID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSisvalid() {
        return ctSisvalid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SISVALID
     *
     * @param ctSisvalid the value for EP_CONTRACT.CT_SISVALID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSisvalid(String ctSisvalid) {
        this.ctSisvalid = ctSisvalid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SREPLYBY
     *
     * @return the value of EP_CONTRACT.CT_SREPLYBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSreplyby() {
        return ctSreplyby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SREPLYBY
     *
     * @param ctSreplyby the value for EP_CONTRACT.CT_SREPLYBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSreplyby(String ctSreplyby) {
        this.ctSreplyby = ctSreplyby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SREPLYDATE
     *
     * @return the value of EP_CONTRACT.CT_SREPLYDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getCtSreplydate() {
        return ctSreplydate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SREPLYDATE
     *
     * @param ctSreplydate the value for EP_CONTRACT.CT_SREPLYDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSreplydate(Date ctSreplydate) {
        this.ctSreplydate = ctSreplydate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SALTERBY
     *
     * @return the value of EP_CONTRACT.CT_SALTERBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSalterby() {
        return ctSalterby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SALTERBY
     *
     * @param ctSalterby the value for EP_CONTRACT.CT_SALTERBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSalterby(String ctSalterby) {
        this.ctSalterby = ctSalterby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SALTERDATE
     *
     * @return the value of EP_CONTRACT.CT_SALTERDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getCtSalterdate() {
        return ctSalterdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SALTERDATE
     *
     * @param ctSalterdate the value for EP_CONTRACT.CT_SALTERDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSalterdate(Date ctSalterdate) {
        this.ctSalterdate = ctSalterdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF1
     *
     * @return the value of EP_CONTRACT.CT_SDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef1() {
        return ctSdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF1
     *
     * @param ctSdef1 the value for EP_CONTRACT.CT_SDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef1(String ctSdef1) {
        this.ctSdef1 = ctSdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF2
     *
     * @return the value of EP_CONTRACT.CT_SDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef2() {
        return ctSdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF2
     *
     * @param ctSdef2 the value for EP_CONTRACT.CT_SDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef2(String ctSdef2) {
        this.ctSdef2 = ctSdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF3
     *
     * @return the value of EP_CONTRACT.CT_SDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef3() {
        return ctSdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF3
     *
     * @param ctSdef3 the value for EP_CONTRACT.CT_SDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef3(String ctSdef3) {
        this.ctSdef3 = ctSdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF4
     *
     * @return the value of EP_CONTRACT.CT_SDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef4() {
        return ctSdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF4
     *
     * @param ctSdef4 the value for EP_CONTRACT.CT_SDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef4(String ctSdef4) {
        this.ctSdef4 = ctSdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF5
     *
     * @return the value of EP_CONTRACT.CT_SDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef5() {
        return ctSdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF5
     *
     * @param ctSdef5 the value for EP_CONTRACT.CT_SDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef5(String ctSdef5) {
        this.ctSdef5 = ctSdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF6
     *
     * @return the value of EP_CONTRACT.CT_SDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef6() {
        return ctSdef6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF6
     *
     * @param ctSdef6 the value for EP_CONTRACT.CT_SDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef6(String ctSdef6) {
        this.ctSdef6 = ctSdef6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF7
     *
     * @return the value of EP_CONTRACT.CT_SDEF7
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef7() {
        return ctSdef7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF7
     *
     * @param ctSdef7 the value for EP_CONTRACT.CT_SDEF7
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef7(String ctSdef7) {
        this.ctSdef7 = ctSdef7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF8
     *
     * @return the value of EP_CONTRACT.CT_SDEF8
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef8() {
        return ctSdef8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF8
     *
     * @param ctSdef8 the value for EP_CONTRACT.CT_SDEF8
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef8(String ctSdef8) {
        this.ctSdef8 = ctSdef8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF9
     *
     * @return the value of EP_CONTRACT.CT_SDEF9
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef9() {
        return ctSdef9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF9
     *
     * @param ctSdef9 the value for EP_CONTRACT.CT_SDEF9
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef9(String ctSdef9) {
        this.ctSdef9 = ctSdef9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF10
     *
     * @return the value of EP_CONTRACT.CT_SDEF10
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef10() {
        return ctSdef10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF10
     *
     * @param ctSdef10 the value for EP_CONTRACT.CT_SDEF10
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef10(String ctSdef10) {
        this.ctSdef10 = ctSdef10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF11
     *
     * @return the value of EP_CONTRACT.CT_SDEF11
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef11() {
        return ctSdef11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF11
     *
     * @param ctSdef11 the value for EP_CONTRACT.CT_SDEF11
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef11(String ctSdef11) {
        this.ctSdef11 = ctSdef11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF12
     *
     * @return the value of EP_CONTRACT.CT_SDEF12
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef12() {
        return ctSdef12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF12
     *
     * @param ctSdef12 the value for EP_CONTRACT.CT_SDEF12
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef12(String ctSdef12) {
        this.ctSdef12 = ctSdef12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF13
     *
     * @return the value of EP_CONTRACT.CT_SDEF13
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef13() {
        return ctSdef13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF13
     *
     * @param ctSdef13 the value for EP_CONTRACT.CT_SDEF13
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef13(String ctSdef13) {
        this.ctSdef13 = ctSdef13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF14
     *
     * @return the value of EP_CONTRACT.CT_SDEF14
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef14() {
        return ctSdef14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF14
     *
     * @param ctSdef14 the value for EP_CONTRACT.CT_SDEF14
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef14(String ctSdef14) {
        this.ctSdef14 = ctSdef14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF15
     *
     * @return the value of EP_CONTRACT.CT_SDEF15
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef15() {
        return ctSdef15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF15
     *
     * @param ctSdef15 the value for EP_CONTRACT.CT_SDEF15
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef15(String ctSdef15) {
        this.ctSdef15 = ctSdef15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF16
     *
     * @return the value of EP_CONTRACT.CT_SDEF16
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef16() {
        return ctSdef16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF16
     *
     * @param ctSdef16 the value for EP_CONTRACT.CT_SDEF16
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef16(String ctSdef16) {
        this.ctSdef16 = ctSdef16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF17
     *
     * @return the value of EP_CONTRACT.CT_SDEF17
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef17() {
        return ctSdef17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF17
     *
     * @param ctSdef17 the value for EP_CONTRACT.CT_SDEF17
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef17(String ctSdef17) {
        this.ctSdef17 = ctSdef17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF18
     *
     * @return the value of EP_CONTRACT.CT_SDEF18
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef18() {
        return ctSdef18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF18
     *
     * @param ctSdef18 the value for EP_CONTRACT.CT_SDEF18
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef18(String ctSdef18) {
        this.ctSdef18 = ctSdef18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF19
     *
     * @return the value of EP_CONTRACT.CT_SDEF19
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef19() {
        return ctSdef19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF19
     *
     * @param ctSdef19 the value for EP_CONTRACT.CT_SDEF19
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef19(String ctSdef19) {
        this.ctSdef19 = ctSdef19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_SDEF20
     *
     * @return the value of EP_CONTRACT.CT_SDEF20
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSdef20() {
        return ctSdef20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_SDEF20
     *
     * @param ctSdef20 the value for EP_CONTRACT.CT_SDEF20
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSdef20(String ctSdef20) {
        this.ctSdef20 = ctSdef20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_NDEF1
     *
     * @return the value of EP_CONTRACT.CT_NDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getCtNdef1() {
        return ctNdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_NDEF1
     *
     * @param ctNdef1 the value for EP_CONTRACT.CT_NDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtNdef1(BigDecimal ctNdef1) {
        this.ctNdef1 = ctNdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_NDEF2
     *
     * @return the value of EP_CONTRACT.CT_NDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getCtNdef2() {
        return ctNdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_NDEF2
     *
     * @param ctNdef2 the value for EP_CONTRACT.CT_NDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtNdef2(BigDecimal ctNdef2) {
        this.ctNdef2 = ctNdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_NDEF3
     *
     * @return the value of EP_CONTRACT.CT_NDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getCtNdef3() {
        return ctNdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_NDEF3
     *
     * @param ctNdef3 the value for EP_CONTRACT.CT_NDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtNdef3(BigDecimal ctNdef3) {
        this.ctNdef3 = ctNdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_NDEF4
     *
     * @return the value of EP_CONTRACT.CT_NDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getCtNdef4() {
        return ctNdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_NDEF4
     *
     * @param ctNdef4 the value for EP_CONTRACT.CT_NDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtNdef4(BigDecimal ctNdef4) {
        this.ctNdef4 = ctNdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_NDEF5
     *
     * @return the value of EP_CONTRACT.CT_NDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getCtNdef5() {
        return ctNdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_NDEF5
     *
     * @param ctNdef5 the value for EP_CONTRACT.CT_NDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtNdef5(BigDecimal ctNdef5) {
        this.ctNdef5 = ctNdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_TDEF1
     *
     * @return the value of EP_CONTRACT.CT_TDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getCtTdef1() {
        return ctTdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_TDEF1
     *
     * @param ctTdef1 the value for EP_CONTRACT.CT_TDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtTdef1(Date ctTdef1) {
        this.ctTdef1 = ctTdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_TDEF2
     *
     * @return the value of EP_CONTRACT.CT_TDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getCtTdef2() {
        return ctTdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_TDEF2
     *
     * @param ctTdef2 the value for EP_CONTRACT.CT_TDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtTdef2(Date ctTdef2) {
        this.ctTdef2 = ctTdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_TDEF3
     *
     * @return the value of EP_CONTRACT.CT_TDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getCtTdef3() {
        return ctTdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_TDEF3
     *
     * @param ctTdef3 the value for EP_CONTRACT.CT_TDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtTdef3(Date ctTdef3) {
        this.ctTdef3 = ctTdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_TDEF4
     *
     * @return the value of EP_CONTRACT.CT_TDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getCtTdef4() {
        return ctTdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_TDEF4
     *
     * @param ctTdef4 the value for EP_CONTRACT.CT_TDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtTdef4(Date ctTdef4) {
        this.ctTdef4 = ctTdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_TDEF5
     *
     * @return the value of EP_CONTRACT.CT_TDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getCtTdef5() {
        return ctTdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_TDEF5
     *
     * @param ctTdef5 the value for EP_CONTRACT.CT_TDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtTdef5(Date ctTdef5) {
        this.ctTdef5 = ctTdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_CONTRACT.CT_TDEF6
     *
     * @return the value of EP_CONTRACT.CT_TDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getCtTdef6() {
        return ctTdef6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_CONTRACT.CT_TDEF6
     *
     * @param ctTdef6 the value for EP_CONTRACT.CT_TDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtTdef6(Date ctTdef6) {
        this.ctTdef6 = ctTdef6;
    }
}