package com.rc.project.vo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class EpFormworkExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table EP_FORMWORK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table EP_FORMWORK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_FORMWORK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpFormworkExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_FORMWORK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    protected EpFormworkExample(EpFormworkExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_FORMWORK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_FORMWORK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_FORMWORK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_FORMWORK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_FORMWORK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_FORMWORK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_FORMWORK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table EP_FORMWORK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andFormNidIsNull() {
            addCriterion("FORM_NID is null");
            return this;
        }

        public Criteria andFormNidIsNotNull() {
            addCriterion("FORM_NID is not null");
            return this;
        }

        public Criteria andFormNidEqualTo(BigDecimal value) {
            addCriterion("FORM_NID =", value, "formNid");
            return this;
        }

        public Criteria andFormNidNotEqualTo(BigDecimal value) {
            addCriterion("FORM_NID <>", value, "formNid");
            return this;
        }

        public Criteria andFormNidGreaterThan(BigDecimal value) {
            addCriterion("FORM_NID >", value, "formNid");
            return this;
        }

        public Criteria andFormNidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FORM_NID >=", value, "formNid");
            return this;
        }

        public Criteria andFormNidLessThan(BigDecimal value) {
            addCriterion("FORM_NID <", value, "formNid");
            return this;
        }

        public Criteria andFormNidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FORM_NID <=", value, "formNid");
            return this;
        }

        public Criteria andFormNidIn(List values) {
            addCriterion("FORM_NID in", values, "formNid");
            return this;
        }

        public Criteria andFormNidNotIn(List values) {
            addCriterion("FORM_NID not in", values, "formNid");
            return this;
        }

        public Criteria andFormNidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORM_NID between", value1, value2, "formNid");
            return this;
        }

        public Criteria andFormNidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORM_NID not between", value1, value2, "formNid");
            return this;
        }

        public Criteria andFormSnameIsNull() {
            addCriterion("FORM_SNAME is null");
            return this;
        }

        public Criteria andFormSnameIsNotNull() {
            addCriterion("FORM_SNAME is not null");
            return this;
        }

        public Criteria andFormSnameEqualTo(String value) {
            addCriterion("FORM_SNAME =", value, "formSname");
            return this;
        }

        public Criteria andFormSnameNotEqualTo(String value) {
            addCriterion("FORM_SNAME <>", value, "formSname");
            return this;
        }

        public Criteria andFormSnameGreaterThan(String value) {
            addCriterion("FORM_SNAME >", value, "formSname");
            return this;
        }

        public Criteria andFormSnameGreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SNAME >=", value, "formSname");
            return this;
        }

        public Criteria andFormSnameLessThan(String value) {
            addCriterion("FORM_SNAME <", value, "formSname");
            return this;
        }

        public Criteria andFormSnameLessThanOrEqualTo(String value) {
            addCriterion("FORM_SNAME <=", value, "formSname");
            return this;
        }

        public Criteria andFormSnameLike(String value) {
            addCriterion("FORM_SNAME like", value, "formSname");
            return this;
        }

        public Criteria andFormSnameNotLike(String value) {
            addCriterion("FORM_SNAME not like", value, "formSname");
            return this;
        }

        public Criteria andFormSnameIn(List values) {
            addCriterion("FORM_SNAME in", values, "formSname");
            return this;
        }

        public Criteria andFormSnameNotIn(List values) {
            addCriterion("FORM_SNAME not in", values, "formSname");
            return this;
        }

        public Criteria andFormSnameBetween(String value1, String value2) {
            addCriterion("FORM_SNAME between", value1, value2, "formSname");
            return this;
        }

        public Criteria andFormSnameNotBetween(String value1, String value2) {
            addCriterion("FORM_SNAME not between", value1, value2, "formSname");
            return this;
        }

        public Criteria andFormStypeIsNull() {
            addCriterion("FORM_STYPE is null");
            return this;
        }

        public Criteria andFormStypeIsNotNull() {
            addCriterion("FORM_STYPE is not null");
            return this;
        }

        public Criteria andFormStypeEqualTo(String value) {
            addCriterion("FORM_STYPE =", value, "formStype");
            return this;
        }

        public Criteria andFormStypeNotEqualTo(String value) {
            addCriterion("FORM_STYPE <>", value, "formStype");
            return this;
        }

        public Criteria andFormStypeGreaterThan(String value) {
            addCriterion("FORM_STYPE >", value, "formStype");
            return this;
        }

        public Criteria andFormStypeGreaterThanOrEqualTo(String value) {
            addCriterion("FORM_STYPE >=", value, "formStype");
            return this;
        }

        public Criteria andFormStypeLessThan(String value) {
            addCriterion("FORM_STYPE <", value, "formStype");
            return this;
        }

        public Criteria andFormStypeLessThanOrEqualTo(String value) {
            addCriterion("FORM_STYPE <=", value, "formStype");
            return this;
        }

        public Criteria andFormStypeLike(String value) {
            addCriterion("FORM_STYPE like", value, "formStype");
            return this;
        }

        public Criteria andFormStypeNotLike(String value) {
            addCriterion("FORM_STYPE not like", value, "formStype");
            return this;
        }

        public Criteria andFormStypeIn(List values) {
            addCriterion("FORM_STYPE in", values, "formStype");
            return this;
        }

        public Criteria andFormStypeNotIn(List values) {
            addCriterion("FORM_STYPE not in", values, "formStype");
            return this;
        }

        public Criteria andFormStypeBetween(String value1, String value2) {
            addCriterion("FORM_STYPE between", value1, value2, "formStype");
            return this;
        }

        public Criteria andFormStypeNotBetween(String value1, String value2) {
            addCriterion("FORM_STYPE not between", value1, value2, "formStype");
            return this;
        }

        public Criteria andFormSurlIsNull() {
            addCriterion("FORM_SURL is null");
            return this;
        }

        public Criteria andFormSurlIsNotNull() {
            addCriterion("FORM_SURL is not null");
            return this;
        }

        public Criteria andFormSurlEqualTo(String value) {
            addCriterion("FORM_SURL =", value, "formSurl");
            return this;
        }

        public Criteria andFormSurlNotEqualTo(String value) {
            addCriterion("FORM_SURL <>", value, "formSurl");
            return this;
        }

        public Criteria andFormSurlGreaterThan(String value) {
            addCriterion("FORM_SURL >", value, "formSurl");
            return this;
        }

        public Criteria andFormSurlGreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SURL >=", value, "formSurl");
            return this;
        }

        public Criteria andFormSurlLessThan(String value) {
            addCriterion("FORM_SURL <", value, "formSurl");
            return this;
        }

        public Criteria andFormSurlLessThanOrEqualTo(String value) {
            addCriterion("FORM_SURL <=", value, "formSurl");
            return this;
        }

        public Criteria andFormSurlLike(String value) {
            addCriterion("FORM_SURL like", value, "formSurl");
            return this;
        }

        public Criteria andFormSurlNotLike(String value) {
            addCriterion("FORM_SURL not like", value, "formSurl");
            return this;
        }

        public Criteria andFormSurlIn(List values) {
            addCriterion("FORM_SURL in", values, "formSurl");
            return this;
        }

        public Criteria andFormSurlNotIn(List values) {
            addCriterion("FORM_SURL not in", values, "formSurl");
            return this;
        }

        public Criteria andFormSurlBetween(String value1, String value2) {
            addCriterion("FORM_SURL between", value1, value2, "formSurl");
            return this;
        }

        public Criteria andFormSurlNotBetween(String value1, String value2) {
            addCriterion("FORM_SURL not between", value1, value2, "formSurl");
            return this;
        }

        public Criteria andFormSremarkIsNull() {
            addCriterion("FORM_SREMARK is null");
            return this;
        }

        public Criteria andFormSremarkIsNotNull() {
            addCriterion("FORM_SREMARK is not null");
            return this;
        }

        public Criteria andFormSremarkEqualTo(String value) {
            addCriterion("FORM_SREMARK =", value, "formSremark");
            return this;
        }

        public Criteria andFormSremarkNotEqualTo(String value) {
            addCriterion("FORM_SREMARK <>", value, "formSremark");
            return this;
        }

        public Criteria andFormSremarkGreaterThan(String value) {
            addCriterion("FORM_SREMARK >", value, "formSremark");
            return this;
        }

        public Criteria andFormSremarkGreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SREMARK >=", value, "formSremark");
            return this;
        }

        public Criteria andFormSremarkLessThan(String value) {
            addCriterion("FORM_SREMARK <", value, "formSremark");
            return this;
        }

        public Criteria andFormSremarkLessThanOrEqualTo(String value) {
            addCriterion("FORM_SREMARK <=", value, "formSremark");
            return this;
        }

        public Criteria andFormSremarkLike(String value) {
            addCriterion("FORM_SREMARK like", value, "formSremark");
            return this;
        }

        public Criteria andFormSremarkNotLike(String value) {
            addCriterion("FORM_SREMARK not like", value, "formSremark");
            return this;
        }

        public Criteria andFormSremarkIn(List values) {
            addCriterion("FORM_SREMARK in", values, "formSremark");
            return this;
        }

        public Criteria andFormSremarkNotIn(List values) {
            addCriterion("FORM_SREMARK not in", values, "formSremark");
            return this;
        }

        public Criteria andFormSremarkBetween(String value1, String value2) {
            addCriterion("FORM_SREMARK between", value1, value2, "formSremark");
            return this;
        }

        public Criteria andFormSremarkNotBetween(String value1, String value2) {
            addCriterion("FORM_SREMARK not between", value1, value2, "formSremark");
            return this;
        }

        public Criteria andFormSisdelIsNull() {
            addCriterion("FORM_SISDEL is null");
            return this;
        }

        public Criteria andFormSisdelIsNotNull() {
            addCriterion("FORM_SISDEL is not null");
            return this;
        }

        public Criteria andFormSisdelEqualTo(String value) {
            addCriterion("FORM_SISDEL =", value, "formSisdel");
            return this;
        }

        public Criteria andFormSisdelNotEqualTo(String value) {
            addCriterion("FORM_SISDEL <>", value, "formSisdel");
            return this;
        }

        public Criteria andFormSisdelGreaterThan(String value) {
            addCriterion("FORM_SISDEL >", value, "formSisdel");
            return this;
        }

        public Criteria andFormSisdelGreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SISDEL >=", value, "formSisdel");
            return this;
        }

        public Criteria andFormSisdelLessThan(String value) {
            addCriterion("FORM_SISDEL <", value, "formSisdel");
            return this;
        }

        public Criteria andFormSisdelLessThanOrEqualTo(String value) {
            addCriterion("FORM_SISDEL <=", value, "formSisdel");
            return this;
        }

        public Criteria andFormSisdelLike(String value) {
            addCriterion("FORM_SISDEL like", value, "formSisdel");
            return this;
        }

        public Criteria andFormSisdelNotLike(String value) {
            addCriterion("FORM_SISDEL not like", value, "formSisdel");
            return this;
        }

        public Criteria andFormSisdelIn(List values) {
            addCriterion("FORM_SISDEL in", values, "formSisdel");
            return this;
        }

        public Criteria andFormSisdelNotIn(List values) {
            addCriterion("FORM_SISDEL not in", values, "formSisdel");
            return this;
        }

        public Criteria andFormSisdelBetween(String value1, String value2) {
            addCriterion("FORM_SISDEL between", value1, value2, "formSisdel");
            return this;
        }

        public Criteria andFormSisdelNotBetween(String value1, String value2) {
            addCriterion("FORM_SISDEL not between", value1, value2, "formSisdel");
            return this;
        }

        public Criteria andFormSisvalidIsNull() {
            addCriterion("FORM_SISVALID is null");
            return this;
        }

        public Criteria andFormSisvalidIsNotNull() {
            addCriterion("FORM_SISVALID is not null");
            return this;
        }

        public Criteria andFormSisvalidEqualTo(String value) {
            addCriterion("FORM_SISVALID =", value, "formSisvalid");
            return this;
        }

        public Criteria andFormSisvalidNotEqualTo(String value) {
            addCriterion("FORM_SISVALID <>", value, "formSisvalid");
            return this;
        }

        public Criteria andFormSisvalidGreaterThan(String value) {
            addCriterion("FORM_SISVALID >", value, "formSisvalid");
            return this;
        }

        public Criteria andFormSisvalidGreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SISVALID >=", value, "formSisvalid");
            return this;
        }

        public Criteria andFormSisvalidLessThan(String value) {
            addCriterion("FORM_SISVALID <", value, "formSisvalid");
            return this;
        }

        public Criteria andFormSisvalidLessThanOrEqualTo(String value) {
            addCriterion("FORM_SISVALID <=", value, "formSisvalid");
            return this;
        }

        public Criteria andFormSisvalidLike(String value) {
            addCriterion("FORM_SISVALID like", value, "formSisvalid");
            return this;
        }

        public Criteria andFormSisvalidNotLike(String value) {
            addCriterion("FORM_SISVALID not like", value, "formSisvalid");
            return this;
        }

        public Criteria andFormSisvalidIn(List values) {
            addCriterion("FORM_SISVALID in", values, "formSisvalid");
            return this;
        }

        public Criteria andFormSisvalidNotIn(List values) {
            addCriterion("FORM_SISVALID not in", values, "formSisvalid");
            return this;
        }

        public Criteria andFormSisvalidBetween(String value1, String value2) {
            addCriterion("FORM_SISVALID between", value1, value2, "formSisvalid");
            return this;
        }

        public Criteria andFormSisvalidNotBetween(String value1, String value2) {
            addCriterion("FORM_SISVALID not between", value1, value2, "formSisvalid");
            return this;
        }

        public Criteria andFormSreplybyIsNull() {
            addCriterion("FORM_SREPLYBY is null");
            return this;
        }

        public Criteria andFormSreplybyIsNotNull() {
            addCriterion("FORM_SREPLYBY is not null");
            return this;
        }

        public Criteria andFormSreplybyEqualTo(String value) {
            addCriterion("FORM_SREPLYBY =", value, "formSreplyby");
            return this;
        }

        public Criteria andFormSreplybyNotEqualTo(String value) {
            addCriterion("FORM_SREPLYBY <>", value, "formSreplyby");
            return this;
        }

        public Criteria andFormSreplybyGreaterThan(String value) {
            addCriterion("FORM_SREPLYBY >", value, "formSreplyby");
            return this;
        }

        public Criteria andFormSreplybyGreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SREPLYBY >=", value, "formSreplyby");
            return this;
        }

        public Criteria andFormSreplybyLessThan(String value) {
            addCriterion("FORM_SREPLYBY <", value, "formSreplyby");
            return this;
        }

        public Criteria andFormSreplybyLessThanOrEqualTo(String value) {
            addCriterion("FORM_SREPLYBY <=", value, "formSreplyby");
            return this;
        }

        public Criteria andFormSreplybyLike(String value) {
            addCriterion("FORM_SREPLYBY like", value, "formSreplyby");
            return this;
        }

        public Criteria andFormSreplybyNotLike(String value) {
            addCriterion("FORM_SREPLYBY not like", value, "formSreplyby");
            return this;
        }

        public Criteria andFormSreplybyIn(List values) {
            addCriterion("FORM_SREPLYBY in", values, "formSreplyby");
            return this;
        }

        public Criteria andFormSreplybyNotIn(List values) {
            addCriterion("FORM_SREPLYBY not in", values, "formSreplyby");
            return this;
        }

        public Criteria andFormSreplybyBetween(String value1, String value2) {
            addCriterion("FORM_SREPLYBY between", value1, value2, "formSreplyby");
            return this;
        }

        public Criteria andFormSreplybyNotBetween(String value1, String value2) {
            addCriterion("FORM_SREPLYBY not between", value1, value2, "formSreplyby");
            return this;
        }

        public Criteria andFormSreplydateIsNull() {
            addCriterion("FORM_SREPLYDATE is null");
            return this;
        }

        public Criteria andFormSreplydateIsNotNull() {
            addCriterion("FORM_SREPLYDATE is not null");
            return this;
        }

        public Criteria andFormSreplydateEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_SREPLYDATE =", value, "formSreplydate");
            return this;
        }

        public Criteria andFormSreplydateNotEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_SREPLYDATE <>", value, "formSreplydate");
            return this;
        }

        public Criteria andFormSreplydateGreaterThan(Date value) {
            addCriterionForJDBCDate("FORM_SREPLYDATE >", value, "formSreplydate");
            return this;
        }

        public Criteria andFormSreplydateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_SREPLYDATE >=", value, "formSreplydate");
            return this;
        }

        public Criteria andFormSreplydateLessThan(Date value) {
            addCriterionForJDBCDate("FORM_SREPLYDATE <", value, "formSreplydate");
            return this;
        }

        public Criteria andFormSreplydateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_SREPLYDATE <=", value, "formSreplydate");
            return this;
        }

        public Criteria andFormSreplydateIn(List values) {
            addCriterionForJDBCDate("FORM_SREPLYDATE in", values, "formSreplydate");
            return this;
        }

        public Criteria andFormSreplydateNotIn(List values) {
            addCriterionForJDBCDate("FORM_SREPLYDATE not in", values, "formSreplydate");
            return this;
        }

        public Criteria andFormSreplydateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_SREPLYDATE between", value1, value2, "formSreplydate");
            return this;
        }

        public Criteria andFormSreplydateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_SREPLYDATE not between", value1, value2, "formSreplydate");
            return this;
        }

        public Criteria andFormSalterbyIsNull() {
            addCriterion("FORM_SALTERBY is null");
            return this;
        }

        public Criteria andFormSalterbyIsNotNull() {
            addCriterion("FORM_SALTERBY is not null");
            return this;
        }

        public Criteria andFormSalterbyEqualTo(String value) {
            addCriterion("FORM_SALTERBY =", value, "formSalterby");
            return this;
        }

        public Criteria andFormSalterbyNotEqualTo(String value) {
            addCriterion("FORM_SALTERBY <>", value, "formSalterby");
            return this;
        }

        public Criteria andFormSalterbyGreaterThan(String value) {
            addCriterion("FORM_SALTERBY >", value, "formSalterby");
            return this;
        }

        public Criteria andFormSalterbyGreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SALTERBY >=", value, "formSalterby");
            return this;
        }

        public Criteria andFormSalterbyLessThan(String value) {
            addCriterion("FORM_SALTERBY <", value, "formSalterby");
            return this;
        }

        public Criteria andFormSalterbyLessThanOrEqualTo(String value) {
            addCriterion("FORM_SALTERBY <=", value, "formSalterby");
            return this;
        }

        public Criteria andFormSalterbyLike(String value) {
            addCriterion("FORM_SALTERBY like", value, "formSalterby");
            return this;
        }

        public Criteria andFormSalterbyNotLike(String value) {
            addCriterion("FORM_SALTERBY not like", value, "formSalterby");
            return this;
        }

        public Criteria andFormSalterbyIn(List values) {
            addCriterion("FORM_SALTERBY in", values, "formSalterby");
            return this;
        }

        public Criteria andFormSalterbyNotIn(List values) {
            addCriterion("FORM_SALTERBY not in", values, "formSalterby");
            return this;
        }

        public Criteria andFormSalterbyBetween(String value1, String value2) {
            addCriterion("FORM_SALTERBY between", value1, value2, "formSalterby");
            return this;
        }

        public Criteria andFormSalterbyNotBetween(String value1, String value2) {
            addCriterion("FORM_SALTERBY not between", value1, value2, "formSalterby");
            return this;
        }

        public Criteria andFormSalterdateIsNull() {
            addCriterion("FORM_SALTERDATE is null");
            return this;
        }

        public Criteria andFormSalterdateIsNotNull() {
            addCriterion("FORM_SALTERDATE is not null");
            return this;
        }

        public Criteria andFormSalterdateEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_SALTERDATE =", value, "formSalterdate");
            return this;
        }

        public Criteria andFormSalterdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_SALTERDATE <>", value, "formSalterdate");
            return this;
        }

        public Criteria andFormSalterdateGreaterThan(Date value) {
            addCriterionForJDBCDate("FORM_SALTERDATE >", value, "formSalterdate");
            return this;
        }

        public Criteria andFormSalterdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_SALTERDATE >=", value, "formSalterdate");
            return this;
        }

        public Criteria andFormSalterdateLessThan(Date value) {
            addCriterionForJDBCDate("FORM_SALTERDATE <", value, "formSalterdate");
            return this;
        }

        public Criteria andFormSalterdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_SALTERDATE <=", value, "formSalterdate");
            return this;
        }

        public Criteria andFormSalterdateIn(List values) {
            addCriterionForJDBCDate("FORM_SALTERDATE in", values, "formSalterdate");
            return this;
        }

        public Criteria andFormSalterdateNotIn(List values) {
            addCriterionForJDBCDate("FORM_SALTERDATE not in", values, "formSalterdate");
            return this;
        }

        public Criteria andFormSalterdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_SALTERDATE between", value1, value2, "formSalterdate");
            return this;
        }

        public Criteria andFormSalterdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_SALTERDATE not between", value1, value2, "formSalterdate");
            return this;
        }

        public Criteria andFormSdef1IsNull() {
            addCriterion("FORM_SDEF1 is null");
            return this;
        }

        public Criteria andFormSdef1IsNotNull() {
            addCriterion("FORM_SDEF1 is not null");
            return this;
        }

        public Criteria andFormSdef1EqualTo(String value) {
            addCriterion("FORM_SDEF1 =", value, "formSdef1");
            return this;
        }

        public Criteria andFormSdef1NotEqualTo(String value) {
            addCriterion("FORM_SDEF1 <>", value, "formSdef1");
            return this;
        }

        public Criteria andFormSdef1GreaterThan(String value) {
            addCriterion("FORM_SDEF1 >", value, "formSdef1");
            return this;
        }

        public Criteria andFormSdef1GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF1 >=", value, "formSdef1");
            return this;
        }

        public Criteria andFormSdef1LessThan(String value) {
            addCriterion("FORM_SDEF1 <", value, "formSdef1");
            return this;
        }

        public Criteria andFormSdef1LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF1 <=", value, "formSdef1");
            return this;
        }

        public Criteria andFormSdef1Like(String value) {
            addCriterion("FORM_SDEF1 like", value, "formSdef1");
            return this;
        }

        public Criteria andFormSdef1NotLike(String value) {
            addCriterion("FORM_SDEF1 not like", value, "formSdef1");
            return this;
        }

        public Criteria andFormSdef1In(List values) {
            addCriterion("FORM_SDEF1 in", values, "formSdef1");
            return this;
        }

        public Criteria andFormSdef1NotIn(List values) {
            addCriterion("FORM_SDEF1 not in", values, "formSdef1");
            return this;
        }

        public Criteria andFormSdef1Between(String value1, String value2) {
            addCriterion("FORM_SDEF1 between", value1, value2, "formSdef1");
            return this;
        }

        public Criteria andFormSdef1NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF1 not between", value1, value2, "formSdef1");
            return this;
        }

        public Criteria andFormSdef2IsNull() {
            addCriterion("FORM_SDEF2 is null");
            return this;
        }

        public Criteria andFormSdef2IsNotNull() {
            addCriterion("FORM_SDEF2 is not null");
            return this;
        }

        public Criteria andFormSdef2EqualTo(String value) {
            addCriterion("FORM_SDEF2 =", value, "formSdef2");
            return this;
        }

        public Criteria andFormSdef2NotEqualTo(String value) {
            addCriterion("FORM_SDEF2 <>", value, "formSdef2");
            return this;
        }

        public Criteria andFormSdef2GreaterThan(String value) {
            addCriterion("FORM_SDEF2 >", value, "formSdef2");
            return this;
        }

        public Criteria andFormSdef2GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF2 >=", value, "formSdef2");
            return this;
        }

        public Criteria andFormSdef2LessThan(String value) {
            addCriterion("FORM_SDEF2 <", value, "formSdef2");
            return this;
        }

        public Criteria andFormSdef2LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF2 <=", value, "formSdef2");
            return this;
        }

        public Criteria andFormSdef2Like(String value) {
            addCriterion("FORM_SDEF2 like", value, "formSdef2");
            return this;
        }

        public Criteria andFormSdef2NotLike(String value) {
            addCriterion("FORM_SDEF2 not like", value, "formSdef2");
            return this;
        }

        public Criteria andFormSdef2In(List values) {
            addCriterion("FORM_SDEF2 in", values, "formSdef2");
            return this;
        }

        public Criteria andFormSdef2NotIn(List values) {
            addCriterion("FORM_SDEF2 not in", values, "formSdef2");
            return this;
        }

        public Criteria andFormSdef2Between(String value1, String value2) {
            addCriterion("FORM_SDEF2 between", value1, value2, "formSdef2");
            return this;
        }

        public Criteria andFormSdef2NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF2 not between", value1, value2, "formSdef2");
            return this;
        }

        public Criteria andFormSdef3IsNull() {
            addCriterion("FORM_SDEF3 is null");
            return this;
        }

        public Criteria andFormSdef3IsNotNull() {
            addCriterion("FORM_SDEF3 is not null");
            return this;
        }

        public Criteria andFormSdef3EqualTo(String value) {
            addCriterion("FORM_SDEF3 =", value, "formSdef3");
            return this;
        }

        public Criteria andFormSdef3NotEqualTo(String value) {
            addCriterion("FORM_SDEF3 <>", value, "formSdef3");
            return this;
        }

        public Criteria andFormSdef3GreaterThan(String value) {
            addCriterion("FORM_SDEF3 >", value, "formSdef3");
            return this;
        }

        public Criteria andFormSdef3GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF3 >=", value, "formSdef3");
            return this;
        }

        public Criteria andFormSdef3LessThan(String value) {
            addCriterion("FORM_SDEF3 <", value, "formSdef3");
            return this;
        }

        public Criteria andFormSdef3LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF3 <=", value, "formSdef3");
            return this;
        }

        public Criteria andFormSdef3Like(String value) {
            addCriterion("FORM_SDEF3 like", value, "formSdef3");
            return this;
        }

        public Criteria andFormSdef3NotLike(String value) {
            addCriterion("FORM_SDEF3 not like", value, "formSdef3");
            return this;
        }

        public Criteria andFormSdef3In(List values) {
            addCriterion("FORM_SDEF3 in", values, "formSdef3");
            return this;
        }

        public Criteria andFormSdef3NotIn(List values) {
            addCriterion("FORM_SDEF3 not in", values, "formSdef3");
            return this;
        }

        public Criteria andFormSdef3Between(String value1, String value2) {
            addCriterion("FORM_SDEF3 between", value1, value2, "formSdef3");
            return this;
        }

        public Criteria andFormSdef3NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF3 not between", value1, value2, "formSdef3");
            return this;
        }

        public Criteria andFormSdef4IsNull() {
            addCriterion("FORM_SDEF4 is null");
            return this;
        }

        public Criteria andFormSdef4IsNotNull() {
            addCriterion("FORM_SDEF4 is not null");
            return this;
        }

        public Criteria andFormSdef4EqualTo(String value) {
            addCriterion("FORM_SDEF4 =", value, "formSdef4");
            return this;
        }

        public Criteria andFormSdef4NotEqualTo(String value) {
            addCriterion("FORM_SDEF4 <>", value, "formSdef4");
            return this;
        }

        public Criteria andFormSdef4GreaterThan(String value) {
            addCriterion("FORM_SDEF4 >", value, "formSdef4");
            return this;
        }

        public Criteria andFormSdef4GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF4 >=", value, "formSdef4");
            return this;
        }

        public Criteria andFormSdef4LessThan(String value) {
            addCriterion("FORM_SDEF4 <", value, "formSdef4");
            return this;
        }

        public Criteria andFormSdef4LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF4 <=", value, "formSdef4");
            return this;
        }

        public Criteria andFormSdef4Like(String value) {
            addCriterion("FORM_SDEF4 like", value, "formSdef4");
            return this;
        }

        public Criteria andFormSdef4NotLike(String value) {
            addCriterion("FORM_SDEF4 not like", value, "formSdef4");
            return this;
        }

        public Criteria andFormSdef4In(List values) {
            addCriterion("FORM_SDEF4 in", values, "formSdef4");
            return this;
        }

        public Criteria andFormSdef4NotIn(List values) {
            addCriterion("FORM_SDEF4 not in", values, "formSdef4");
            return this;
        }

        public Criteria andFormSdef4Between(String value1, String value2) {
            addCriterion("FORM_SDEF4 between", value1, value2, "formSdef4");
            return this;
        }

        public Criteria andFormSdef4NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF4 not between", value1, value2, "formSdef4");
            return this;
        }

        public Criteria andFormSdef5IsNull() {
            addCriterion("FORM_SDEF5 is null");
            return this;
        }

        public Criteria andFormSdef5IsNotNull() {
            addCriterion("FORM_SDEF5 is not null");
            return this;
        }

        public Criteria andFormSdef5EqualTo(String value) {
            addCriterion("FORM_SDEF5 =", value, "formSdef5");
            return this;
        }

        public Criteria andFormSdef5NotEqualTo(String value) {
            addCriterion("FORM_SDEF5 <>", value, "formSdef5");
            return this;
        }

        public Criteria andFormSdef5GreaterThan(String value) {
            addCriterion("FORM_SDEF5 >", value, "formSdef5");
            return this;
        }

        public Criteria andFormSdef5GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF5 >=", value, "formSdef5");
            return this;
        }

        public Criteria andFormSdef5LessThan(String value) {
            addCriterion("FORM_SDEF5 <", value, "formSdef5");
            return this;
        }

        public Criteria andFormSdef5LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF5 <=", value, "formSdef5");
            return this;
        }

        public Criteria andFormSdef5Like(String value) {
            addCriterion("FORM_SDEF5 like", value, "formSdef5");
            return this;
        }

        public Criteria andFormSdef5NotLike(String value) {
            addCriterion("FORM_SDEF5 not like", value, "formSdef5");
            return this;
        }

        public Criteria andFormSdef5In(List values) {
            addCriterion("FORM_SDEF5 in", values, "formSdef5");
            return this;
        }

        public Criteria andFormSdef5NotIn(List values) {
            addCriterion("FORM_SDEF5 not in", values, "formSdef5");
            return this;
        }

        public Criteria andFormSdef5Between(String value1, String value2) {
            addCriterion("FORM_SDEF5 between", value1, value2, "formSdef5");
            return this;
        }

        public Criteria andFormSdef5NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF5 not between", value1, value2, "formSdef5");
            return this;
        }

        public Criteria andFormSdef6IsNull() {
            addCriterion("FORM_SDEF6 is null");
            return this;
        }

        public Criteria andFormSdef6IsNotNull() {
            addCriterion("FORM_SDEF6 is not null");
            return this;
        }

        public Criteria andFormSdef6EqualTo(String value) {
            addCriterion("FORM_SDEF6 =", value, "formSdef6");
            return this;
        }

        public Criteria andFormSdef6NotEqualTo(String value) {
            addCriterion("FORM_SDEF6 <>", value, "formSdef6");
            return this;
        }

        public Criteria andFormSdef6GreaterThan(String value) {
            addCriterion("FORM_SDEF6 >", value, "formSdef6");
            return this;
        }

        public Criteria andFormSdef6GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF6 >=", value, "formSdef6");
            return this;
        }

        public Criteria andFormSdef6LessThan(String value) {
            addCriterion("FORM_SDEF6 <", value, "formSdef6");
            return this;
        }

        public Criteria andFormSdef6LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF6 <=", value, "formSdef6");
            return this;
        }

        public Criteria andFormSdef6Like(String value) {
            addCriterion("FORM_SDEF6 like", value, "formSdef6");
            return this;
        }

        public Criteria andFormSdef6NotLike(String value) {
            addCriterion("FORM_SDEF6 not like", value, "formSdef6");
            return this;
        }

        public Criteria andFormSdef6In(List values) {
            addCriterion("FORM_SDEF6 in", values, "formSdef6");
            return this;
        }

        public Criteria andFormSdef6NotIn(List values) {
            addCriterion("FORM_SDEF6 not in", values, "formSdef6");
            return this;
        }

        public Criteria andFormSdef6Between(String value1, String value2) {
            addCriterion("FORM_SDEF6 between", value1, value2, "formSdef6");
            return this;
        }

        public Criteria andFormSdef6NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF6 not between", value1, value2, "formSdef6");
            return this;
        }

        public Criteria andFormSdef7IsNull() {
            addCriterion("FORM_SDEF7 is null");
            return this;
        }

        public Criteria andFormSdef7IsNotNull() {
            addCriterion("FORM_SDEF7 is not null");
            return this;
        }

        public Criteria andFormSdef7EqualTo(String value) {
            addCriterion("FORM_SDEF7 =", value, "formSdef7");
            return this;
        }

        public Criteria andFormSdef7NotEqualTo(String value) {
            addCriterion("FORM_SDEF7 <>", value, "formSdef7");
            return this;
        }

        public Criteria andFormSdef7GreaterThan(String value) {
            addCriterion("FORM_SDEF7 >", value, "formSdef7");
            return this;
        }

        public Criteria andFormSdef7GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF7 >=", value, "formSdef7");
            return this;
        }

        public Criteria andFormSdef7LessThan(String value) {
            addCriterion("FORM_SDEF7 <", value, "formSdef7");
            return this;
        }

        public Criteria andFormSdef7LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF7 <=", value, "formSdef7");
            return this;
        }

        public Criteria andFormSdef7Like(String value) {
            addCriterion("FORM_SDEF7 like", value, "formSdef7");
            return this;
        }

        public Criteria andFormSdef7NotLike(String value) {
            addCriterion("FORM_SDEF7 not like", value, "formSdef7");
            return this;
        }

        public Criteria andFormSdef7In(List values) {
            addCriterion("FORM_SDEF7 in", values, "formSdef7");
            return this;
        }

        public Criteria andFormSdef7NotIn(List values) {
            addCriterion("FORM_SDEF7 not in", values, "formSdef7");
            return this;
        }

        public Criteria andFormSdef7Between(String value1, String value2) {
            addCriterion("FORM_SDEF7 between", value1, value2, "formSdef7");
            return this;
        }

        public Criteria andFormSdef7NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF7 not between", value1, value2, "formSdef7");
            return this;
        }

        public Criteria andFormSdef8IsNull() {
            addCriterion("FORM_SDEF8 is null");
            return this;
        }

        public Criteria andFormSdef8IsNotNull() {
            addCriterion("FORM_SDEF8 is not null");
            return this;
        }

        public Criteria andFormSdef8EqualTo(String value) {
            addCriterion("FORM_SDEF8 =", value, "formSdef8");
            return this;
        }

        public Criteria andFormSdef8NotEqualTo(String value) {
            addCriterion("FORM_SDEF8 <>", value, "formSdef8");
            return this;
        }

        public Criteria andFormSdef8GreaterThan(String value) {
            addCriterion("FORM_SDEF8 >", value, "formSdef8");
            return this;
        }

        public Criteria andFormSdef8GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF8 >=", value, "formSdef8");
            return this;
        }

        public Criteria andFormSdef8LessThan(String value) {
            addCriterion("FORM_SDEF8 <", value, "formSdef8");
            return this;
        }

        public Criteria andFormSdef8LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF8 <=", value, "formSdef8");
            return this;
        }

        public Criteria andFormSdef8Like(String value) {
            addCriterion("FORM_SDEF8 like", value, "formSdef8");
            return this;
        }

        public Criteria andFormSdef8NotLike(String value) {
            addCriterion("FORM_SDEF8 not like", value, "formSdef8");
            return this;
        }

        public Criteria andFormSdef8In(List values) {
            addCriterion("FORM_SDEF8 in", values, "formSdef8");
            return this;
        }

        public Criteria andFormSdef8NotIn(List values) {
            addCriterion("FORM_SDEF8 not in", values, "formSdef8");
            return this;
        }

        public Criteria andFormSdef8Between(String value1, String value2) {
            addCriterion("FORM_SDEF8 between", value1, value2, "formSdef8");
            return this;
        }

        public Criteria andFormSdef8NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF8 not between", value1, value2, "formSdef8");
            return this;
        }

        public Criteria andFormSdef9IsNull() {
            addCriterion("FORM_SDEF9 is null");
            return this;
        }

        public Criteria andFormSdef9IsNotNull() {
            addCriterion("FORM_SDEF9 is not null");
            return this;
        }

        public Criteria andFormSdef9EqualTo(String value) {
            addCriterion("FORM_SDEF9 =", value, "formSdef9");
            return this;
        }

        public Criteria andFormSdef9NotEqualTo(String value) {
            addCriterion("FORM_SDEF9 <>", value, "formSdef9");
            return this;
        }

        public Criteria andFormSdef9GreaterThan(String value) {
            addCriterion("FORM_SDEF9 >", value, "formSdef9");
            return this;
        }

        public Criteria andFormSdef9GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF9 >=", value, "formSdef9");
            return this;
        }

        public Criteria andFormSdef9LessThan(String value) {
            addCriterion("FORM_SDEF9 <", value, "formSdef9");
            return this;
        }

        public Criteria andFormSdef9LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF9 <=", value, "formSdef9");
            return this;
        }

        public Criteria andFormSdef9Like(String value) {
            addCriterion("FORM_SDEF9 like", value, "formSdef9");
            return this;
        }

        public Criteria andFormSdef9NotLike(String value) {
            addCriterion("FORM_SDEF9 not like", value, "formSdef9");
            return this;
        }

        public Criteria andFormSdef9In(List values) {
            addCriterion("FORM_SDEF9 in", values, "formSdef9");
            return this;
        }

        public Criteria andFormSdef9NotIn(List values) {
            addCriterion("FORM_SDEF9 not in", values, "formSdef9");
            return this;
        }

        public Criteria andFormSdef9Between(String value1, String value2) {
            addCriterion("FORM_SDEF9 between", value1, value2, "formSdef9");
            return this;
        }

        public Criteria andFormSdef9NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF9 not between", value1, value2, "formSdef9");
            return this;
        }

        public Criteria andFormSdef10IsNull() {
            addCriterion("FORM_SDEF10 is null");
            return this;
        }

        public Criteria andFormSdef10IsNotNull() {
            addCriterion("FORM_SDEF10 is not null");
            return this;
        }

        public Criteria andFormSdef10EqualTo(String value) {
            addCriterion("FORM_SDEF10 =", value, "formSdef10");
            return this;
        }

        public Criteria andFormSdef10NotEqualTo(String value) {
            addCriterion("FORM_SDEF10 <>", value, "formSdef10");
            return this;
        }

        public Criteria andFormSdef10GreaterThan(String value) {
            addCriterion("FORM_SDEF10 >", value, "formSdef10");
            return this;
        }

        public Criteria andFormSdef10GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF10 >=", value, "formSdef10");
            return this;
        }

        public Criteria andFormSdef10LessThan(String value) {
            addCriterion("FORM_SDEF10 <", value, "formSdef10");
            return this;
        }

        public Criteria andFormSdef10LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF10 <=", value, "formSdef10");
            return this;
        }

        public Criteria andFormSdef10Like(String value) {
            addCriterion("FORM_SDEF10 like", value, "formSdef10");
            return this;
        }

        public Criteria andFormSdef10NotLike(String value) {
            addCriterion("FORM_SDEF10 not like", value, "formSdef10");
            return this;
        }

        public Criteria andFormSdef10In(List values) {
            addCriterion("FORM_SDEF10 in", values, "formSdef10");
            return this;
        }

        public Criteria andFormSdef10NotIn(List values) {
            addCriterion("FORM_SDEF10 not in", values, "formSdef10");
            return this;
        }

        public Criteria andFormSdef10Between(String value1, String value2) {
            addCriterion("FORM_SDEF10 between", value1, value2, "formSdef10");
            return this;
        }

        public Criteria andFormSdef10NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF10 not between", value1, value2, "formSdef10");
            return this;
        }

        public Criteria andFormSdef11IsNull() {
            addCriterion("FORM_SDEF11 is null");
            return this;
        }

        public Criteria andFormSdef11IsNotNull() {
            addCriterion("FORM_SDEF11 is not null");
            return this;
        }

        public Criteria andFormSdef11EqualTo(String value) {
            addCriterion("FORM_SDEF11 =", value, "formSdef11");
            return this;
        }

        public Criteria andFormSdef11NotEqualTo(String value) {
            addCriterion("FORM_SDEF11 <>", value, "formSdef11");
            return this;
        }

        public Criteria andFormSdef11GreaterThan(String value) {
            addCriterion("FORM_SDEF11 >", value, "formSdef11");
            return this;
        }

        public Criteria andFormSdef11GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF11 >=", value, "formSdef11");
            return this;
        }

        public Criteria andFormSdef11LessThan(String value) {
            addCriterion("FORM_SDEF11 <", value, "formSdef11");
            return this;
        }

        public Criteria andFormSdef11LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF11 <=", value, "formSdef11");
            return this;
        }

        public Criteria andFormSdef11Like(String value) {
            addCriterion("FORM_SDEF11 like", value, "formSdef11");
            return this;
        }

        public Criteria andFormSdef11NotLike(String value) {
            addCriterion("FORM_SDEF11 not like", value, "formSdef11");
            return this;
        }

        public Criteria andFormSdef11In(List values) {
            addCriterion("FORM_SDEF11 in", values, "formSdef11");
            return this;
        }

        public Criteria andFormSdef11NotIn(List values) {
            addCriterion("FORM_SDEF11 not in", values, "formSdef11");
            return this;
        }

        public Criteria andFormSdef11Between(String value1, String value2) {
            addCriterion("FORM_SDEF11 between", value1, value2, "formSdef11");
            return this;
        }

        public Criteria andFormSdef11NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF11 not between", value1, value2, "formSdef11");
            return this;
        }

        public Criteria andFormSdef12IsNull() {
            addCriterion("FORM_SDEF12 is null");
            return this;
        }

        public Criteria andFormSdef12IsNotNull() {
            addCriterion("FORM_SDEF12 is not null");
            return this;
        }

        public Criteria andFormSdef12EqualTo(String value) {
            addCriterion("FORM_SDEF12 =", value, "formSdef12");
            return this;
        }

        public Criteria andFormSdef12NotEqualTo(String value) {
            addCriterion("FORM_SDEF12 <>", value, "formSdef12");
            return this;
        }

        public Criteria andFormSdef12GreaterThan(String value) {
            addCriterion("FORM_SDEF12 >", value, "formSdef12");
            return this;
        }

        public Criteria andFormSdef12GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF12 >=", value, "formSdef12");
            return this;
        }

        public Criteria andFormSdef12LessThan(String value) {
            addCriterion("FORM_SDEF12 <", value, "formSdef12");
            return this;
        }

        public Criteria andFormSdef12LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF12 <=", value, "formSdef12");
            return this;
        }

        public Criteria andFormSdef12Like(String value) {
            addCriterion("FORM_SDEF12 like", value, "formSdef12");
            return this;
        }

        public Criteria andFormSdef12NotLike(String value) {
            addCriterion("FORM_SDEF12 not like", value, "formSdef12");
            return this;
        }

        public Criteria andFormSdef12In(List values) {
            addCriterion("FORM_SDEF12 in", values, "formSdef12");
            return this;
        }

        public Criteria andFormSdef12NotIn(List values) {
            addCriterion("FORM_SDEF12 not in", values, "formSdef12");
            return this;
        }

        public Criteria andFormSdef12Between(String value1, String value2) {
            addCriterion("FORM_SDEF12 between", value1, value2, "formSdef12");
            return this;
        }

        public Criteria andFormSdef12NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF12 not between", value1, value2, "formSdef12");
            return this;
        }

        public Criteria andFormSdef13IsNull() {
            addCriterion("FORM_SDEF13 is null");
            return this;
        }

        public Criteria andFormSdef13IsNotNull() {
            addCriterion("FORM_SDEF13 is not null");
            return this;
        }

        public Criteria andFormSdef13EqualTo(String value) {
            addCriterion("FORM_SDEF13 =", value, "formSdef13");
            return this;
        }

        public Criteria andFormSdef13NotEqualTo(String value) {
            addCriterion("FORM_SDEF13 <>", value, "formSdef13");
            return this;
        }

        public Criteria andFormSdef13GreaterThan(String value) {
            addCriterion("FORM_SDEF13 >", value, "formSdef13");
            return this;
        }

        public Criteria andFormSdef13GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF13 >=", value, "formSdef13");
            return this;
        }

        public Criteria andFormSdef13LessThan(String value) {
            addCriterion("FORM_SDEF13 <", value, "formSdef13");
            return this;
        }

        public Criteria andFormSdef13LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF13 <=", value, "formSdef13");
            return this;
        }

        public Criteria andFormSdef13Like(String value) {
            addCriterion("FORM_SDEF13 like", value, "formSdef13");
            return this;
        }

        public Criteria andFormSdef13NotLike(String value) {
            addCriterion("FORM_SDEF13 not like", value, "formSdef13");
            return this;
        }

        public Criteria andFormSdef13In(List values) {
            addCriterion("FORM_SDEF13 in", values, "formSdef13");
            return this;
        }

        public Criteria andFormSdef13NotIn(List values) {
            addCriterion("FORM_SDEF13 not in", values, "formSdef13");
            return this;
        }

        public Criteria andFormSdef13Between(String value1, String value2) {
            addCriterion("FORM_SDEF13 between", value1, value2, "formSdef13");
            return this;
        }

        public Criteria andFormSdef13NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF13 not between", value1, value2, "formSdef13");
            return this;
        }

        public Criteria andFormSdef14IsNull() {
            addCriterion("FORM_SDEF14 is null");
            return this;
        }

        public Criteria andFormSdef14IsNotNull() {
            addCriterion("FORM_SDEF14 is not null");
            return this;
        }

        public Criteria andFormSdef14EqualTo(String value) {
            addCriterion("FORM_SDEF14 =", value, "formSdef14");
            return this;
        }

        public Criteria andFormSdef14NotEqualTo(String value) {
            addCriterion("FORM_SDEF14 <>", value, "formSdef14");
            return this;
        }

        public Criteria andFormSdef14GreaterThan(String value) {
            addCriterion("FORM_SDEF14 >", value, "formSdef14");
            return this;
        }

        public Criteria andFormSdef14GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF14 >=", value, "formSdef14");
            return this;
        }

        public Criteria andFormSdef14LessThan(String value) {
            addCriterion("FORM_SDEF14 <", value, "formSdef14");
            return this;
        }

        public Criteria andFormSdef14LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF14 <=", value, "formSdef14");
            return this;
        }

        public Criteria andFormSdef14Like(String value) {
            addCriterion("FORM_SDEF14 like", value, "formSdef14");
            return this;
        }

        public Criteria andFormSdef14NotLike(String value) {
            addCriterion("FORM_SDEF14 not like", value, "formSdef14");
            return this;
        }

        public Criteria andFormSdef14In(List values) {
            addCriterion("FORM_SDEF14 in", values, "formSdef14");
            return this;
        }

        public Criteria andFormSdef14NotIn(List values) {
            addCriterion("FORM_SDEF14 not in", values, "formSdef14");
            return this;
        }

        public Criteria andFormSdef14Between(String value1, String value2) {
            addCriterion("FORM_SDEF14 between", value1, value2, "formSdef14");
            return this;
        }

        public Criteria andFormSdef14NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF14 not between", value1, value2, "formSdef14");
            return this;
        }

        public Criteria andFormSdef15IsNull() {
            addCriterion("FORM_SDEF15 is null");
            return this;
        }

        public Criteria andFormSdef15IsNotNull() {
            addCriterion("FORM_SDEF15 is not null");
            return this;
        }

        public Criteria andFormSdef15EqualTo(String value) {
            addCriterion("FORM_SDEF15 =", value, "formSdef15");
            return this;
        }

        public Criteria andFormSdef15NotEqualTo(String value) {
            addCriterion("FORM_SDEF15 <>", value, "formSdef15");
            return this;
        }

        public Criteria andFormSdef15GreaterThan(String value) {
            addCriterion("FORM_SDEF15 >", value, "formSdef15");
            return this;
        }

        public Criteria andFormSdef15GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF15 >=", value, "formSdef15");
            return this;
        }

        public Criteria andFormSdef15LessThan(String value) {
            addCriterion("FORM_SDEF15 <", value, "formSdef15");
            return this;
        }

        public Criteria andFormSdef15LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF15 <=", value, "formSdef15");
            return this;
        }

        public Criteria andFormSdef15Like(String value) {
            addCriterion("FORM_SDEF15 like", value, "formSdef15");
            return this;
        }

        public Criteria andFormSdef15NotLike(String value) {
            addCriterion("FORM_SDEF15 not like", value, "formSdef15");
            return this;
        }

        public Criteria andFormSdef15In(List values) {
            addCriterion("FORM_SDEF15 in", values, "formSdef15");
            return this;
        }

        public Criteria andFormSdef15NotIn(List values) {
            addCriterion("FORM_SDEF15 not in", values, "formSdef15");
            return this;
        }

        public Criteria andFormSdef15Between(String value1, String value2) {
            addCriterion("FORM_SDEF15 between", value1, value2, "formSdef15");
            return this;
        }

        public Criteria andFormSdef15NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF15 not between", value1, value2, "formSdef15");
            return this;
        }

        public Criteria andFormSdef16IsNull() {
            addCriterion("FORM_SDEF16 is null");
            return this;
        }

        public Criteria andFormSdef16IsNotNull() {
            addCriterion("FORM_SDEF16 is not null");
            return this;
        }

        public Criteria andFormSdef16EqualTo(String value) {
            addCriterion("FORM_SDEF16 =", value, "formSdef16");
            return this;
        }

        public Criteria andFormSdef16NotEqualTo(String value) {
            addCriterion("FORM_SDEF16 <>", value, "formSdef16");
            return this;
        }

        public Criteria andFormSdef16GreaterThan(String value) {
            addCriterion("FORM_SDEF16 >", value, "formSdef16");
            return this;
        }

        public Criteria andFormSdef16GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF16 >=", value, "formSdef16");
            return this;
        }

        public Criteria andFormSdef16LessThan(String value) {
            addCriterion("FORM_SDEF16 <", value, "formSdef16");
            return this;
        }

        public Criteria andFormSdef16LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF16 <=", value, "formSdef16");
            return this;
        }

        public Criteria andFormSdef16Like(String value) {
            addCriterion("FORM_SDEF16 like", value, "formSdef16");
            return this;
        }

        public Criteria andFormSdef16NotLike(String value) {
            addCriterion("FORM_SDEF16 not like", value, "formSdef16");
            return this;
        }

        public Criteria andFormSdef16In(List values) {
            addCriterion("FORM_SDEF16 in", values, "formSdef16");
            return this;
        }

        public Criteria andFormSdef16NotIn(List values) {
            addCriterion("FORM_SDEF16 not in", values, "formSdef16");
            return this;
        }

        public Criteria andFormSdef16Between(String value1, String value2) {
            addCriterion("FORM_SDEF16 between", value1, value2, "formSdef16");
            return this;
        }

        public Criteria andFormSdef16NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF16 not between", value1, value2, "formSdef16");
            return this;
        }

        public Criteria andFormSdef17IsNull() {
            addCriterion("FORM_SDEF17 is null");
            return this;
        }

        public Criteria andFormSdef17IsNotNull() {
            addCriterion("FORM_SDEF17 is not null");
            return this;
        }

        public Criteria andFormSdef17EqualTo(String value) {
            addCriterion("FORM_SDEF17 =", value, "formSdef17");
            return this;
        }

        public Criteria andFormSdef17NotEqualTo(String value) {
            addCriterion("FORM_SDEF17 <>", value, "formSdef17");
            return this;
        }

        public Criteria andFormSdef17GreaterThan(String value) {
            addCriterion("FORM_SDEF17 >", value, "formSdef17");
            return this;
        }

        public Criteria andFormSdef17GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF17 >=", value, "formSdef17");
            return this;
        }

        public Criteria andFormSdef17LessThan(String value) {
            addCriterion("FORM_SDEF17 <", value, "formSdef17");
            return this;
        }

        public Criteria andFormSdef17LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF17 <=", value, "formSdef17");
            return this;
        }

        public Criteria andFormSdef17Like(String value) {
            addCriterion("FORM_SDEF17 like", value, "formSdef17");
            return this;
        }

        public Criteria andFormSdef17NotLike(String value) {
            addCriterion("FORM_SDEF17 not like", value, "formSdef17");
            return this;
        }

        public Criteria andFormSdef17In(List values) {
            addCriterion("FORM_SDEF17 in", values, "formSdef17");
            return this;
        }

        public Criteria andFormSdef17NotIn(List values) {
            addCriterion("FORM_SDEF17 not in", values, "formSdef17");
            return this;
        }

        public Criteria andFormSdef17Between(String value1, String value2) {
            addCriterion("FORM_SDEF17 between", value1, value2, "formSdef17");
            return this;
        }

        public Criteria andFormSdef17NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF17 not between", value1, value2, "formSdef17");
            return this;
        }

        public Criteria andFormSdef18IsNull() {
            addCriterion("FORM_SDEF18 is null");
            return this;
        }

        public Criteria andFormSdef18IsNotNull() {
            addCriterion("FORM_SDEF18 is not null");
            return this;
        }

        public Criteria andFormSdef18EqualTo(String value) {
            addCriterion("FORM_SDEF18 =", value, "formSdef18");
            return this;
        }

        public Criteria andFormSdef18NotEqualTo(String value) {
            addCriterion("FORM_SDEF18 <>", value, "formSdef18");
            return this;
        }

        public Criteria andFormSdef18GreaterThan(String value) {
            addCriterion("FORM_SDEF18 >", value, "formSdef18");
            return this;
        }

        public Criteria andFormSdef18GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF18 >=", value, "formSdef18");
            return this;
        }

        public Criteria andFormSdef18LessThan(String value) {
            addCriterion("FORM_SDEF18 <", value, "formSdef18");
            return this;
        }

        public Criteria andFormSdef18LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF18 <=", value, "formSdef18");
            return this;
        }

        public Criteria andFormSdef18Like(String value) {
            addCriterion("FORM_SDEF18 like", value, "formSdef18");
            return this;
        }

        public Criteria andFormSdef18NotLike(String value) {
            addCriterion("FORM_SDEF18 not like", value, "formSdef18");
            return this;
        }

        public Criteria andFormSdef18In(List values) {
            addCriterion("FORM_SDEF18 in", values, "formSdef18");
            return this;
        }

        public Criteria andFormSdef18NotIn(List values) {
            addCriterion("FORM_SDEF18 not in", values, "formSdef18");
            return this;
        }

        public Criteria andFormSdef18Between(String value1, String value2) {
            addCriterion("FORM_SDEF18 between", value1, value2, "formSdef18");
            return this;
        }

        public Criteria andFormSdef18NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF18 not between", value1, value2, "formSdef18");
            return this;
        }

        public Criteria andFormSdef19IsNull() {
            addCriterion("FORM_SDEF19 is null");
            return this;
        }

        public Criteria andFormSdef19IsNotNull() {
            addCriterion("FORM_SDEF19 is not null");
            return this;
        }

        public Criteria andFormSdef19EqualTo(String value) {
            addCriterion("FORM_SDEF19 =", value, "formSdef19");
            return this;
        }

        public Criteria andFormSdef19NotEqualTo(String value) {
            addCriterion("FORM_SDEF19 <>", value, "formSdef19");
            return this;
        }

        public Criteria andFormSdef19GreaterThan(String value) {
            addCriterion("FORM_SDEF19 >", value, "formSdef19");
            return this;
        }

        public Criteria andFormSdef19GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF19 >=", value, "formSdef19");
            return this;
        }

        public Criteria andFormSdef19LessThan(String value) {
            addCriterion("FORM_SDEF19 <", value, "formSdef19");
            return this;
        }

        public Criteria andFormSdef19LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF19 <=", value, "formSdef19");
            return this;
        }

        public Criteria andFormSdef19Like(String value) {
            addCriterion("FORM_SDEF19 like", value, "formSdef19");
            return this;
        }

        public Criteria andFormSdef19NotLike(String value) {
            addCriterion("FORM_SDEF19 not like", value, "formSdef19");
            return this;
        }

        public Criteria andFormSdef19In(List values) {
            addCriterion("FORM_SDEF19 in", values, "formSdef19");
            return this;
        }

        public Criteria andFormSdef19NotIn(List values) {
            addCriterion("FORM_SDEF19 not in", values, "formSdef19");
            return this;
        }

        public Criteria andFormSdef19Between(String value1, String value2) {
            addCriterion("FORM_SDEF19 between", value1, value2, "formSdef19");
            return this;
        }

        public Criteria andFormSdef19NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF19 not between", value1, value2, "formSdef19");
            return this;
        }

        public Criteria andFormSdef20IsNull() {
            addCriterion("FORM_SDEF20 is null");
            return this;
        }

        public Criteria andFormSdef20IsNotNull() {
            addCriterion("FORM_SDEF20 is not null");
            return this;
        }

        public Criteria andFormSdef20EqualTo(String value) {
            addCriterion("FORM_SDEF20 =", value, "formSdef20");
            return this;
        }

        public Criteria andFormSdef20NotEqualTo(String value) {
            addCriterion("FORM_SDEF20 <>", value, "formSdef20");
            return this;
        }

        public Criteria andFormSdef20GreaterThan(String value) {
            addCriterion("FORM_SDEF20 >", value, "formSdef20");
            return this;
        }

        public Criteria andFormSdef20GreaterThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF20 >=", value, "formSdef20");
            return this;
        }

        public Criteria andFormSdef20LessThan(String value) {
            addCriterion("FORM_SDEF20 <", value, "formSdef20");
            return this;
        }

        public Criteria andFormSdef20LessThanOrEqualTo(String value) {
            addCriterion("FORM_SDEF20 <=", value, "formSdef20");
            return this;
        }

        public Criteria andFormSdef20Like(String value) {
            addCriterion("FORM_SDEF20 like", value, "formSdef20");
            return this;
        }

        public Criteria andFormSdef20NotLike(String value) {
            addCriterion("FORM_SDEF20 not like", value, "formSdef20");
            return this;
        }

        public Criteria andFormSdef20In(List values) {
            addCriterion("FORM_SDEF20 in", values, "formSdef20");
            return this;
        }

        public Criteria andFormSdef20NotIn(List values) {
            addCriterion("FORM_SDEF20 not in", values, "formSdef20");
            return this;
        }

        public Criteria andFormSdef20Between(String value1, String value2) {
            addCriterion("FORM_SDEF20 between", value1, value2, "formSdef20");
            return this;
        }

        public Criteria andFormSdef20NotBetween(String value1, String value2) {
            addCriterion("FORM_SDEF20 not between", value1, value2, "formSdef20");
            return this;
        }

        public Criteria andFormNdef1IsNull() {
            addCriterion("FORM_NDEF1 is null");
            return this;
        }

        public Criteria andFormNdef1IsNotNull() {
            addCriterion("FORM_NDEF1 is not null");
            return this;
        }

        public Criteria andFormNdef1EqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF1 =", value, "formNdef1");
            return this;
        }

        public Criteria andFormNdef1NotEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF1 <>", value, "formNdef1");
            return this;
        }

        public Criteria andFormNdef1GreaterThan(BigDecimal value) {
            addCriterion("FORM_NDEF1 >", value, "formNdef1");
            return this;
        }

        public Criteria andFormNdef1GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF1 >=", value, "formNdef1");
            return this;
        }

        public Criteria andFormNdef1LessThan(BigDecimal value) {
            addCriterion("FORM_NDEF1 <", value, "formNdef1");
            return this;
        }

        public Criteria andFormNdef1LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF1 <=", value, "formNdef1");
            return this;
        }

        public Criteria andFormNdef1In(List values) {
            addCriterion("FORM_NDEF1 in", values, "formNdef1");
            return this;
        }

        public Criteria andFormNdef1NotIn(List values) {
            addCriterion("FORM_NDEF1 not in", values, "formNdef1");
            return this;
        }

        public Criteria andFormNdef1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORM_NDEF1 between", value1, value2, "formNdef1");
            return this;
        }

        public Criteria andFormNdef1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORM_NDEF1 not between", value1, value2, "formNdef1");
            return this;
        }

        public Criteria andFormNdef2IsNull() {
            addCriterion("FORM_NDEF2 is null");
            return this;
        }

        public Criteria andFormNdef2IsNotNull() {
            addCriterion("FORM_NDEF2 is not null");
            return this;
        }

        public Criteria andFormNdef2EqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF2 =", value, "formNdef2");
            return this;
        }

        public Criteria andFormNdef2NotEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF2 <>", value, "formNdef2");
            return this;
        }

        public Criteria andFormNdef2GreaterThan(BigDecimal value) {
            addCriterion("FORM_NDEF2 >", value, "formNdef2");
            return this;
        }

        public Criteria andFormNdef2GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF2 >=", value, "formNdef2");
            return this;
        }

        public Criteria andFormNdef2LessThan(BigDecimal value) {
            addCriterion("FORM_NDEF2 <", value, "formNdef2");
            return this;
        }

        public Criteria andFormNdef2LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF2 <=", value, "formNdef2");
            return this;
        }

        public Criteria andFormNdef2In(List values) {
            addCriterion("FORM_NDEF2 in", values, "formNdef2");
            return this;
        }

        public Criteria andFormNdef2NotIn(List values) {
            addCriterion("FORM_NDEF2 not in", values, "formNdef2");
            return this;
        }

        public Criteria andFormNdef2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORM_NDEF2 between", value1, value2, "formNdef2");
            return this;
        }

        public Criteria andFormNdef2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORM_NDEF2 not between", value1, value2, "formNdef2");
            return this;
        }

        public Criteria andFormNdef3IsNull() {
            addCriterion("FORM_NDEF3 is null");
            return this;
        }

        public Criteria andFormNdef3IsNotNull() {
            addCriterion("FORM_NDEF3 is not null");
            return this;
        }

        public Criteria andFormNdef3EqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF3 =", value, "formNdef3");
            return this;
        }

        public Criteria andFormNdef3NotEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF3 <>", value, "formNdef3");
            return this;
        }

        public Criteria andFormNdef3GreaterThan(BigDecimal value) {
            addCriterion("FORM_NDEF3 >", value, "formNdef3");
            return this;
        }

        public Criteria andFormNdef3GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF3 >=", value, "formNdef3");
            return this;
        }

        public Criteria andFormNdef3LessThan(BigDecimal value) {
            addCriterion("FORM_NDEF3 <", value, "formNdef3");
            return this;
        }

        public Criteria andFormNdef3LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF3 <=", value, "formNdef3");
            return this;
        }

        public Criteria andFormNdef3In(List values) {
            addCriterion("FORM_NDEF3 in", values, "formNdef3");
            return this;
        }

        public Criteria andFormNdef3NotIn(List values) {
            addCriterion("FORM_NDEF3 not in", values, "formNdef3");
            return this;
        }

        public Criteria andFormNdef3Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORM_NDEF3 between", value1, value2, "formNdef3");
            return this;
        }

        public Criteria andFormNdef3NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORM_NDEF3 not between", value1, value2, "formNdef3");
            return this;
        }

        public Criteria andFormNdef4IsNull() {
            addCriterion("FORM_NDEF4 is null");
            return this;
        }

        public Criteria andFormNdef4IsNotNull() {
            addCriterion("FORM_NDEF4 is not null");
            return this;
        }

        public Criteria andFormNdef4EqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF4 =", value, "formNdef4");
            return this;
        }

        public Criteria andFormNdef4NotEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF4 <>", value, "formNdef4");
            return this;
        }

        public Criteria andFormNdef4GreaterThan(BigDecimal value) {
            addCriterion("FORM_NDEF4 >", value, "formNdef4");
            return this;
        }

        public Criteria andFormNdef4GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF4 >=", value, "formNdef4");
            return this;
        }

        public Criteria andFormNdef4LessThan(BigDecimal value) {
            addCriterion("FORM_NDEF4 <", value, "formNdef4");
            return this;
        }

        public Criteria andFormNdef4LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF4 <=", value, "formNdef4");
            return this;
        }

        public Criteria andFormNdef4In(List values) {
            addCriterion("FORM_NDEF4 in", values, "formNdef4");
            return this;
        }

        public Criteria andFormNdef4NotIn(List values) {
            addCriterion("FORM_NDEF4 not in", values, "formNdef4");
            return this;
        }

        public Criteria andFormNdef4Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORM_NDEF4 between", value1, value2, "formNdef4");
            return this;
        }

        public Criteria andFormNdef4NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORM_NDEF4 not between", value1, value2, "formNdef4");
            return this;
        }

        public Criteria andFormNdef5IsNull() {
            addCriterion("FORM_NDEF5 is null");
            return this;
        }

        public Criteria andFormNdef5IsNotNull() {
            addCriterion("FORM_NDEF5 is not null");
            return this;
        }

        public Criteria andFormNdef5EqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF5 =", value, "formNdef5");
            return this;
        }

        public Criteria andFormNdef5NotEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF5 <>", value, "formNdef5");
            return this;
        }

        public Criteria andFormNdef5GreaterThan(BigDecimal value) {
            addCriterion("FORM_NDEF5 >", value, "formNdef5");
            return this;
        }

        public Criteria andFormNdef5GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF5 >=", value, "formNdef5");
            return this;
        }

        public Criteria andFormNdef5LessThan(BigDecimal value) {
            addCriterion("FORM_NDEF5 <", value, "formNdef5");
            return this;
        }

        public Criteria andFormNdef5LessThanOrEqualTo(BigDecimal value) {
            addCriterion("FORM_NDEF5 <=", value, "formNdef5");
            return this;
        }

        public Criteria andFormNdef5In(List values) {
            addCriterion("FORM_NDEF5 in", values, "formNdef5");
            return this;
        }

        public Criteria andFormNdef5NotIn(List values) {
            addCriterion("FORM_NDEF5 not in", values, "formNdef5");
            return this;
        }

        public Criteria andFormNdef5Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORM_NDEF5 between", value1, value2, "formNdef5");
            return this;
        }

        public Criteria andFormNdef5NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FORM_NDEF5 not between", value1, value2, "formNdef5");
            return this;
        }

        public Criteria andFormTdef1IsNull() {
            addCriterion("FORM_TDEF1 is null");
            return this;
        }

        public Criteria andFormTdef1IsNotNull() {
            addCriterion("FORM_TDEF1 is not null");
            return this;
        }

        public Criteria andFormTdef1EqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF1 =", value, "formTdef1");
            return this;
        }

        public Criteria andFormTdef1NotEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF1 <>", value, "formTdef1");
            return this;
        }

        public Criteria andFormTdef1GreaterThan(Date value) {
            addCriterionForJDBCDate("FORM_TDEF1 >", value, "formTdef1");
            return this;
        }

        public Criteria andFormTdef1GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF1 >=", value, "formTdef1");
            return this;
        }

        public Criteria andFormTdef1LessThan(Date value) {
            addCriterionForJDBCDate("FORM_TDEF1 <", value, "formTdef1");
            return this;
        }

        public Criteria andFormTdef1LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF1 <=", value, "formTdef1");
            return this;
        }

        public Criteria andFormTdef1In(List values) {
            addCriterionForJDBCDate("FORM_TDEF1 in", values, "formTdef1");
            return this;
        }

        public Criteria andFormTdef1NotIn(List values) {
            addCriterionForJDBCDate("FORM_TDEF1 not in", values, "formTdef1");
            return this;
        }

        public Criteria andFormTdef1Between(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_TDEF1 between", value1, value2, "formTdef1");
            return this;
        }

        public Criteria andFormTdef1NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_TDEF1 not between", value1, value2, "formTdef1");
            return this;
        }

        public Criteria andFormTdef2IsNull() {
            addCriterion("FORM_TDEF2 is null");
            return this;
        }

        public Criteria andFormTdef2IsNotNull() {
            addCriterion("FORM_TDEF2 is not null");
            return this;
        }

        public Criteria andFormTdef2EqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF2 =", value, "formTdef2");
            return this;
        }

        public Criteria andFormTdef2NotEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF2 <>", value, "formTdef2");
            return this;
        }

        public Criteria andFormTdef2GreaterThan(Date value) {
            addCriterionForJDBCDate("FORM_TDEF2 >", value, "formTdef2");
            return this;
        }

        public Criteria andFormTdef2GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF2 >=", value, "formTdef2");
            return this;
        }

        public Criteria andFormTdef2LessThan(Date value) {
            addCriterionForJDBCDate("FORM_TDEF2 <", value, "formTdef2");
            return this;
        }

        public Criteria andFormTdef2LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF2 <=", value, "formTdef2");
            return this;
        }

        public Criteria andFormTdef2In(List values) {
            addCriterionForJDBCDate("FORM_TDEF2 in", values, "formTdef2");
            return this;
        }

        public Criteria andFormTdef2NotIn(List values) {
            addCriterionForJDBCDate("FORM_TDEF2 not in", values, "formTdef2");
            return this;
        }

        public Criteria andFormTdef2Between(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_TDEF2 between", value1, value2, "formTdef2");
            return this;
        }

        public Criteria andFormTdef2NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_TDEF2 not between", value1, value2, "formTdef2");
            return this;
        }

        public Criteria andFormTdef3IsNull() {
            addCriterion("FORM_TDEF3 is null");
            return this;
        }

        public Criteria andFormTdef3IsNotNull() {
            addCriterion("FORM_TDEF3 is not null");
            return this;
        }

        public Criteria andFormTdef3EqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF3 =", value, "formTdef3");
            return this;
        }

        public Criteria andFormTdef3NotEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF3 <>", value, "formTdef3");
            return this;
        }

        public Criteria andFormTdef3GreaterThan(Date value) {
            addCriterionForJDBCDate("FORM_TDEF3 >", value, "formTdef3");
            return this;
        }

        public Criteria andFormTdef3GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF3 >=", value, "formTdef3");
            return this;
        }

        public Criteria andFormTdef3LessThan(Date value) {
            addCriterionForJDBCDate("FORM_TDEF3 <", value, "formTdef3");
            return this;
        }

        public Criteria andFormTdef3LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF3 <=", value, "formTdef3");
            return this;
        }

        public Criteria andFormTdef3In(List values) {
            addCriterionForJDBCDate("FORM_TDEF3 in", values, "formTdef3");
            return this;
        }

        public Criteria andFormTdef3NotIn(List values) {
            addCriterionForJDBCDate("FORM_TDEF3 not in", values, "formTdef3");
            return this;
        }

        public Criteria andFormTdef3Between(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_TDEF3 between", value1, value2, "formTdef3");
            return this;
        }

        public Criteria andFormTdef3NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_TDEF3 not between", value1, value2, "formTdef3");
            return this;
        }

        public Criteria andFormTdef4IsNull() {
            addCriterion("FORM_TDEF4 is null");
            return this;
        }

        public Criteria andFormTdef4IsNotNull() {
            addCriterion("FORM_TDEF4 is not null");
            return this;
        }

        public Criteria andFormTdef4EqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF4 =", value, "formTdef4");
            return this;
        }

        public Criteria andFormTdef4NotEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF4 <>", value, "formTdef4");
            return this;
        }

        public Criteria andFormTdef4GreaterThan(Date value) {
            addCriterionForJDBCDate("FORM_TDEF4 >", value, "formTdef4");
            return this;
        }

        public Criteria andFormTdef4GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF4 >=", value, "formTdef4");
            return this;
        }

        public Criteria andFormTdef4LessThan(Date value) {
            addCriterionForJDBCDate("FORM_TDEF4 <", value, "formTdef4");
            return this;
        }

        public Criteria andFormTdef4LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF4 <=", value, "formTdef4");
            return this;
        }

        public Criteria andFormTdef4In(List values) {
            addCriterionForJDBCDate("FORM_TDEF4 in", values, "formTdef4");
            return this;
        }

        public Criteria andFormTdef4NotIn(List values) {
            addCriterionForJDBCDate("FORM_TDEF4 not in", values, "formTdef4");
            return this;
        }

        public Criteria andFormTdef4Between(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_TDEF4 between", value1, value2, "formTdef4");
            return this;
        }

        public Criteria andFormTdef4NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_TDEF4 not between", value1, value2, "formTdef4");
            return this;
        }

        public Criteria andFormTdef5IsNull() {
            addCriterion("FORM_TDEF5 is null");
            return this;
        }

        public Criteria andFormTdef5IsNotNull() {
            addCriterion("FORM_TDEF5 is not null");
            return this;
        }

        public Criteria andFormTdef5EqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF5 =", value, "formTdef5");
            return this;
        }

        public Criteria andFormTdef5NotEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF5 <>", value, "formTdef5");
            return this;
        }

        public Criteria andFormTdef5GreaterThan(Date value) {
            addCriterionForJDBCDate("FORM_TDEF5 >", value, "formTdef5");
            return this;
        }

        public Criteria andFormTdef5GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF5 >=", value, "formTdef5");
            return this;
        }

        public Criteria andFormTdef5LessThan(Date value) {
            addCriterionForJDBCDate("FORM_TDEF5 <", value, "formTdef5");
            return this;
        }

        public Criteria andFormTdef5LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FORM_TDEF5 <=", value, "formTdef5");
            return this;
        }

        public Criteria andFormTdef5In(List values) {
            addCriterionForJDBCDate("FORM_TDEF5 in", values, "formTdef5");
            return this;
        }

        public Criteria andFormTdef5NotIn(List values) {
            addCriterionForJDBCDate("FORM_TDEF5 not in", values, "formTdef5");
            return this;
        }

        public Criteria andFormTdef5Between(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_TDEF5 between", value1, value2, "formTdef5");
            return this;
        }

        public Criteria andFormTdef5NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FORM_TDEF5 not between", value1, value2, "formTdef5");
            return this;
        }
    }
}