package com.rc.project.vo;

import java.math.BigDecimal;
import java.util.Date;

public class EpMail {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_NID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal mlNid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.EP_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String epSno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.BG_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String bgSno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_NNUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal mlNnum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_STOMAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlStomail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SSENDMAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSsendmail;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SSENDPWD
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSsendpwd;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_STITLE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlStitle;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SCONTENT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlScontent;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SFILEURL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSfileurl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_STEMPLETE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlStemplete;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SREMARK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSremark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SISDEL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSisdel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SISVALID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSisvalid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SREPLYBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSreplyby;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SREPLYDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date mlSreplydate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SALTERBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSalterby;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SALTERDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date mlSalterdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF7
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF8
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF9
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF10
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF11
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF12
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF13
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF14
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF15
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF16
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF17
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF18
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF19
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_SDEF20
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String mlSdef20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_NDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal mlNdef1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_NDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal mlNdef2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_NDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal mlNdef3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_NDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal mlNdef4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_NDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal mlNdef5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_TDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date mlTdef1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_TDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date mlTdef2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_TDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date mlTdef3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_TDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date mlTdef4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_MAIL.ML_TDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date mlTdef5;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_NID
     *
     * @return the value of EP_MAIL.ML_NID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getMlNid() {
        return mlNid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_NID
     *
     * @param mlNid the value for EP_MAIL.ML_NID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlNid(BigDecimal mlNid) {
        this.mlNid = mlNid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.EP_SNO
     *
     * @return the value of EP_MAIL.EP_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getEpSno() {
        return epSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.EP_SNO
     *
     * @param epSno the value for EP_MAIL.EP_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setEpSno(String epSno) {
        this.epSno = epSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.BG_SNO
     *
     * @return the value of EP_MAIL.BG_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getBgSno() {
        return bgSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.BG_SNO
     *
     * @param bgSno the value for EP_MAIL.BG_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setBgSno(String bgSno) {
        this.bgSno = bgSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_NNUM
     *
     * @return the value of EP_MAIL.ML_NNUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getMlNnum() {
        return mlNnum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_NNUM
     *
     * @param mlNnum the value for EP_MAIL.ML_NNUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlNnum(BigDecimal mlNnum) {
        this.mlNnum = mlNnum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_STOMAIL
     *
     * @return the value of EP_MAIL.ML_STOMAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlStomail() {
        return mlStomail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_STOMAIL
     *
     * @param mlStomail the value for EP_MAIL.ML_STOMAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlStomail(String mlStomail) {
        this.mlStomail = mlStomail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SSENDMAIL
     *
     * @return the value of EP_MAIL.ML_SSENDMAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSsendmail() {
        return mlSsendmail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SSENDMAIL
     *
     * @param mlSsendmail the value for EP_MAIL.ML_SSENDMAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSsendmail(String mlSsendmail) {
        this.mlSsendmail = mlSsendmail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SSENDPWD
     *
     * @return the value of EP_MAIL.ML_SSENDPWD
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSsendpwd() {
        return mlSsendpwd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SSENDPWD
     *
     * @param mlSsendpwd the value for EP_MAIL.ML_SSENDPWD
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSsendpwd(String mlSsendpwd) {
        this.mlSsendpwd = mlSsendpwd;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_STITLE
     *
     * @return the value of EP_MAIL.ML_STITLE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlStitle() {
        return mlStitle;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_STITLE
     *
     * @param mlStitle the value for EP_MAIL.ML_STITLE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlStitle(String mlStitle) {
        this.mlStitle = mlStitle;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SCONTENT
     *
     * @return the value of EP_MAIL.ML_SCONTENT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlScontent() {
        return mlScontent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SCONTENT
     *
     * @param mlScontent the value for EP_MAIL.ML_SCONTENT
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlScontent(String mlScontent) {
        this.mlScontent = mlScontent;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SFILEURL
     *
     * @return the value of EP_MAIL.ML_SFILEURL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSfileurl() {
        return mlSfileurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SFILEURL
     *
     * @param mlSfileurl the value for EP_MAIL.ML_SFILEURL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSfileurl(String mlSfileurl) {
        this.mlSfileurl = mlSfileurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_STEMPLETE
     *
     * @return the value of EP_MAIL.ML_STEMPLETE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlStemplete() {
        return mlStemplete;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_STEMPLETE
     *
     * @param mlStemplete the value for EP_MAIL.ML_STEMPLETE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlStemplete(String mlStemplete) {
        this.mlStemplete = mlStemplete;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SREMARK
     *
     * @return the value of EP_MAIL.ML_SREMARK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSremark() {
        return mlSremark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SREMARK
     *
     * @param mlSremark the value for EP_MAIL.ML_SREMARK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSremark(String mlSremark) {
        this.mlSremark = mlSremark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SISDEL
     *
     * @return the value of EP_MAIL.ML_SISDEL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSisdel() {
        return mlSisdel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SISDEL
     *
     * @param mlSisdel the value for EP_MAIL.ML_SISDEL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSisdel(String mlSisdel) {
        this.mlSisdel = mlSisdel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SISVALID
     *
     * @return the value of EP_MAIL.ML_SISVALID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSisvalid() {
        return mlSisvalid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SISVALID
     *
     * @param mlSisvalid the value for EP_MAIL.ML_SISVALID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSisvalid(String mlSisvalid) {
        this.mlSisvalid = mlSisvalid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SREPLYBY
     *
     * @return the value of EP_MAIL.ML_SREPLYBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSreplyby() {
        return mlSreplyby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SREPLYBY
     *
     * @param mlSreplyby the value for EP_MAIL.ML_SREPLYBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSreplyby(String mlSreplyby) {
        this.mlSreplyby = mlSreplyby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SREPLYDATE
     *
     * @return the value of EP_MAIL.ML_SREPLYDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getMlSreplydate() {
        return mlSreplydate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SREPLYDATE
     *
     * @param mlSreplydate the value for EP_MAIL.ML_SREPLYDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSreplydate(Date mlSreplydate) {
        this.mlSreplydate = mlSreplydate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SALTERBY
     *
     * @return the value of EP_MAIL.ML_SALTERBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSalterby() {
        return mlSalterby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SALTERBY
     *
     * @param mlSalterby the value for EP_MAIL.ML_SALTERBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSalterby(String mlSalterby) {
        this.mlSalterby = mlSalterby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SALTERDATE
     *
     * @return the value of EP_MAIL.ML_SALTERDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getMlSalterdate() {
        return mlSalterdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SALTERDATE
     *
     * @param mlSalterdate the value for EP_MAIL.ML_SALTERDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSalterdate(Date mlSalterdate) {
        this.mlSalterdate = mlSalterdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF1
     *
     * @return the value of EP_MAIL.ML_SDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef1() {
        return mlSdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF1
     *
     * @param mlSdef1 the value for EP_MAIL.ML_SDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef1(String mlSdef1) {
        this.mlSdef1 = mlSdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF2
     *
     * @return the value of EP_MAIL.ML_SDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef2() {
        return mlSdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF2
     *
     * @param mlSdef2 the value for EP_MAIL.ML_SDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef2(String mlSdef2) {
        this.mlSdef2 = mlSdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF3
     *
     * @return the value of EP_MAIL.ML_SDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef3() {
        return mlSdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF3
     *
     * @param mlSdef3 the value for EP_MAIL.ML_SDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef3(String mlSdef3) {
        this.mlSdef3 = mlSdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF4
     *
     * @return the value of EP_MAIL.ML_SDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef4() {
        return mlSdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF4
     *
     * @param mlSdef4 the value for EP_MAIL.ML_SDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef4(String mlSdef4) {
        this.mlSdef4 = mlSdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF5
     *
     * @return the value of EP_MAIL.ML_SDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef5() {
        return mlSdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF5
     *
     * @param mlSdef5 the value for EP_MAIL.ML_SDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef5(String mlSdef5) {
        this.mlSdef5 = mlSdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF6
     *
     * @return the value of EP_MAIL.ML_SDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef6() {
        return mlSdef6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF6
     *
     * @param mlSdef6 the value for EP_MAIL.ML_SDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef6(String mlSdef6) {
        this.mlSdef6 = mlSdef6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF7
     *
     * @return the value of EP_MAIL.ML_SDEF7
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef7() {
        return mlSdef7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF7
     *
     * @param mlSdef7 the value for EP_MAIL.ML_SDEF7
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef7(String mlSdef7) {
        this.mlSdef7 = mlSdef7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF8
     *
     * @return the value of EP_MAIL.ML_SDEF8
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef8() {
        return mlSdef8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF8
     *
     * @param mlSdef8 the value for EP_MAIL.ML_SDEF8
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef8(String mlSdef8) {
        this.mlSdef8 = mlSdef8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF9
     *
     * @return the value of EP_MAIL.ML_SDEF9
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef9() {
        return mlSdef9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF9
     *
     * @param mlSdef9 the value for EP_MAIL.ML_SDEF9
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef9(String mlSdef9) {
        this.mlSdef9 = mlSdef9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF10
     *
     * @return the value of EP_MAIL.ML_SDEF10
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef10() {
        return mlSdef10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF10
     *
     * @param mlSdef10 the value for EP_MAIL.ML_SDEF10
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef10(String mlSdef10) {
        this.mlSdef10 = mlSdef10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF11
     *
     * @return the value of EP_MAIL.ML_SDEF11
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef11() {
        return mlSdef11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF11
     *
     * @param mlSdef11 the value for EP_MAIL.ML_SDEF11
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef11(String mlSdef11) {
        this.mlSdef11 = mlSdef11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF12
     *
     * @return the value of EP_MAIL.ML_SDEF12
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef12() {
        return mlSdef12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF12
     *
     * @param mlSdef12 the value for EP_MAIL.ML_SDEF12
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef12(String mlSdef12) {
        this.mlSdef12 = mlSdef12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF13
     *
     * @return the value of EP_MAIL.ML_SDEF13
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef13() {
        return mlSdef13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF13
     *
     * @param mlSdef13 the value for EP_MAIL.ML_SDEF13
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef13(String mlSdef13) {
        this.mlSdef13 = mlSdef13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF14
     *
     * @return the value of EP_MAIL.ML_SDEF14
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef14() {
        return mlSdef14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF14
     *
     * @param mlSdef14 the value for EP_MAIL.ML_SDEF14
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef14(String mlSdef14) {
        this.mlSdef14 = mlSdef14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF15
     *
     * @return the value of EP_MAIL.ML_SDEF15
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef15() {
        return mlSdef15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF15
     *
     * @param mlSdef15 the value for EP_MAIL.ML_SDEF15
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef15(String mlSdef15) {
        this.mlSdef15 = mlSdef15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF16
     *
     * @return the value of EP_MAIL.ML_SDEF16
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef16() {
        return mlSdef16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF16
     *
     * @param mlSdef16 the value for EP_MAIL.ML_SDEF16
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef16(String mlSdef16) {
        this.mlSdef16 = mlSdef16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF17
     *
     * @return the value of EP_MAIL.ML_SDEF17
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef17() {
        return mlSdef17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF17
     *
     * @param mlSdef17 the value for EP_MAIL.ML_SDEF17
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef17(String mlSdef17) {
        this.mlSdef17 = mlSdef17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF18
     *
     * @return the value of EP_MAIL.ML_SDEF18
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef18() {
        return mlSdef18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF18
     *
     * @param mlSdef18 the value for EP_MAIL.ML_SDEF18
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef18(String mlSdef18) {
        this.mlSdef18 = mlSdef18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF19
     *
     * @return the value of EP_MAIL.ML_SDEF19
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef19() {
        return mlSdef19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF19
     *
     * @param mlSdef19 the value for EP_MAIL.ML_SDEF19
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef19(String mlSdef19) {
        this.mlSdef19 = mlSdef19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_SDEF20
     *
     * @return the value of EP_MAIL.ML_SDEF20
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getMlSdef20() {
        return mlSdef20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_SDEF20
     *
     * @param mlSdef20 the value for EP_MAIL.ML_SDEF20
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlSdef20(String mlSdef20) {
        this.mlSdef20 = mlSdef20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_NDEF1
     *
     * @return the value of EP_MAIL.ML_NDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getMlNdef1() {
        return mlNdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_NDEF1
     *
     * @param mlNdef1 the value for EP_MAIL.ML_NDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlNdef1(BigDecimal mlNdef1) {
        this.mlNdef1 = mlNdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_NDEF2
     *
     * @return the value of EP_MAIL.ML_NDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getMlNdef2() {
        return mlNdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_NDEF2
     *
     * @param mlNdef2 the value for EP_MAIL.ML_NDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlNdef2(BigDecimal mlNdef2) {
        this.mlNdef2 = mlNdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_NDEF3
     *
     * @return the value of EP_MAIL.ML_NDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getMlNdef3() {
        return mlNdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_NDEF3
     *
     * @param mlNdef3 the value for EP_MAIL.ML_NDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlNdef3(BigDecimal mlNdef3) {
        this.mlNdef3 = mlNdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_NDEF4
     *
     * @return the value of EP_MAIL.ML_NDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getMlNdef4() {
        return mlNdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_NDEF4
     *
     * @param mlNdef4 the value for EP_MAIL.ML_NDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlNdef4(BigDecimal mlNdef4) {
        this.mlNdef4 = mlNdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_NDEF5
     *
     * @return the value of EP_MAIL.ML_NDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getMlNdef5() {
        return mlNdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_NDEF5
     *
     * @param mlNdef5 the value for EP_MAIL.ML_NDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlNdef5(BigDecimal mlNdef5) {
        this.mlNdef5 = mlNdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_TDEF1
     *
     * @return the value of EP_MAIL.ML_TDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getMlTdef1() {
        return mlTdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_TDEF1
     *
     * @param mlTdef1 the value for EP_MAIL.ML_TDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlTdef1(Date mlTdef1) {
        this.mlTdef1 = mlTdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_TDEF2
     *
     * @return the value of EP_MAIL.ML_TDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getMlTdef2() {
        return mlTdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_TDEF2
     *
     * @param mlTdef2 the value for EP_MAIL.ML_TDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlTdef2(Date mlTdef2) {
        this.mlTdef2 = mlTdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_TDEF3
     *
     * @return the value of EP_MAIL.ML_TDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getMlTdef3() {
        return mlTdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_TDEF3
     *
     * @param mlTdef3 the value for EP_MAIL.ML_TDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlTdef3(Date mlTdef3) {
        this.mlTdef3 = mlTdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_TDEF4
     *
     * @return the value of EP_MAIL.ML_TDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getMlTdef4() {
        return mlTdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_TDEF4
     *
     * @param mlTdef4 the value for EP_MAIL.ML_TDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlTdef4(Date mlTdef4) {
        this.mlTdef4 = mlTdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_MAIL.ML_TDEF5
     *
     * @return the value of EP_MAIL.ML_TDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getMlTdef5() {
        return mlTdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_MAIL.ML_TDEF5
     *
     * @param mlTdef5 the value for EP_MAIL.ML_TDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setMlTdef5(Date mlTdef5) {
        this.mlTdef5 = mlTdef5;
    }
}