package com.rc.project.vo;

import java.math.BigDecimal;
import java.util.Date;

public class EpPayMoney {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_NID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal pmNid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.EP_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String epSno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.CT_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String ctSno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.BG_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String bgSno;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_NNUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal pmNnum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_NMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal pmNmoney;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_STYPE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmStype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SBILL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSbill;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_DTIME
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date pmDtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SPERSON
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSperson;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SREMARK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSremark;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SISDEL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSisdel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SISVALID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSisvalid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SREPLYBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSreplyby;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SREPLYDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date pmSreplydate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SALTERBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSalterby;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SALTERDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date pmSalterdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF7
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF8
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF9
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF10
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef10;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF11
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef11;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF12
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef12;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF13
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef13;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF14
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef14;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF15
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef15;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF16
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef16;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF17
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef17;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF18
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef18;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF19
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef19;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_SDEF20
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String pmSdef20;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_NDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal pmNdef1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_NDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal pmNdef2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_NDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal pmNdef3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_NDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal pmNdef4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_NDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal pmNdef5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_TDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date pmTdef1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_TDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date pmTdef2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_TDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date pmTdef3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_TDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date pmTdef4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column EP_PAYMONEY.PM_TDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date pmTdef5;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_NID
     *
     * @return the value of EP_PAYMONEY.PM_NID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getPmNid() {
        return pmNid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_NID
     *
     * @param pmNid the value for EP_PAYMONEY.PM_NID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmNid(BigDecimal pmNid) {
        this.pmNid = pmNid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.EP_SNO
     *
     * @return the value of EP_PAYMONEY.EP_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getEpSno() {
        return epSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.EP_SNO
     *
     * @param epSno the value for EP_PAYMONEY.EP_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setEpSno(String epSno) {
        this.epSno = epSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.CT_SNO
     *
     * @return the value of EP_PAYMONEY.CT_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getCtSno() {
        return ctSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.CT_SNO
     *
     * @param ctSno the value for EP_PAYMONEY.CT_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setCtSno(String ctSno) {
        this.ctSno = ctSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.BG_SNO
     *
     * @return the value of EP_PAYMONEY.BG_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getBgSno() {
        return bgSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.BG_SNO
     *
     * @param bgSno the value for EP_PAYMONEY.BG_SNO
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setBgSno(String bgSno) {
        this.bgSno = bgSno;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_NNUM
     *
     * @return the value of EP_PAYMONEY.PM_NNUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getPmNnum() {
        return pmNnum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_NNUM
     *
     * @param pmNnum the value for EP_PAYMONEY.PM_NNUM
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmNnum(BigDecimal pmNnum) {
        this.pmNnum = pmNnum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_NMONEY
     *
     * @return the value of EP_PAYMONEY.PM_NMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getPmNmoney() {
        return pmNmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_NMONEY
     *
     * @param pmNmoney the value for EP_PAYMONEY.PM_NMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmNmoney(BigDecimal pmNmoney) {
        this.pmNmoney = pmNmoney;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_STYPE
     *
     * @return the value of EP_PAYMONEY.PM_STYPE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmStype() {
        return pmStype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_STYPE
     *
     * @param pmStype the value for EP_PAYMONEY.PM_STYPE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmStype(String pmStype) {
        this.pmStype = pmStype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SBILL
     *
     * @return the value of EP_PAYMONEY.PM_SBILL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSbill() {
        return pmSbill;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SBILL
     *
     * @param pmSbill the value for EP_PAYMONEY.PM_SBILL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSbill(String pmSbill) {
        this.pmSbill = pmSbill;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_DTIME
     *
     * @return the value of EP_PAYMONEY.PM_DTIME
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getPmDtime() {
        return pmDtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_DTIME
     *
     * @param pmDtime the value for EP_PAYMONEY.PM_DTIME
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmDtime(Date pmDtime) {
        this.pmDtime = pmDtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SPERSON
     *
     * @return the value of EP_PAYMONEY.PM_SPERSON
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSperson() {
        return pmSperson;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SPERSON
     *
     * @param pmSperson the value for EP_PAYMONEY.PM_SPERSON
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSperson(String pmSperson) {
        this.pmSperson = pmSperson;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SREMARK
     *
     * @return the value of EP_PAYMONEY.PM_SREMARK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSremark() {
        return pmSremark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SREMARK
     *
     * @param pmSremark the value for EP_PAYMONEY.PM_SREMARK
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSremark(String pmSremark) {
        this.pmSremark = pmSremark;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SISDEL
     *
     * @return the value of EP_PAYMONEY.PM_SISDEL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSisdel() {
        return pmSisdel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SISDEL
     *
     * @param pmSisdel the value for EP_PAYMONEY.PM_SISDEL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSisdel(String pmSisdel) {
        this.pmSisdel = pmSisdel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SISVALID
     *
     * @return the value of EP_PAYMONEY.PM_SISVALID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSisvalid() {
        return pmSisvalid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SISVALID
     *
     * @param pmSisvalid the value for EP_PAYMONEY.PM_SISVALID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSisvalid(String pmSisvalid) {
        this.pmSisvalid = pmSisvalid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SREPLYBY
     *
     * @return the value of EP_PAYMONEY.PM_SREPLYBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSreplyby() {
        return pmSreplyby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SREPLYBY
     *
     * @param pmSreplyby the value for EP_PAYMONEY.PM_SREPLYBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSreplyby(String pmSreplyby) {
        this.pmSreplyby = pmSreplyby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SREPLYDATE
     *
     * @return the value of EP_PAYMONEY.PM_SREPLYDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getPmSreplydate() {
        return pmSreplydate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SREPLYDATE
     *
     * @param pmSreplydate the value for EP_PAYMONEY.PM_SREPLYDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSreplydate(Date pmSreplydate) {
        this.pmSreplydate = pmSreplydate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SALTERBY
     *
     * @return the value of EP_PAYMONEY.PM_SALTERBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSalterby() {
        return pmSalterby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SALTERBY
     *
     * @param pmSalterby the value for EP_PAYMONEY.PM_SALTERBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSalterby(String pmSalterby) {
        this.pmSalterby = pmSalterby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SALTERDATE
     *
     * @return the value of EP_PAYMONEY.PM_SALTERDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getPmSalterdate() {
        return pmSalterdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SALTERDATE
     *
     * @param pmSalterdate the value for EP_PAYMONEY.PM_SALTERDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSalterdate(Date pmSalterdate) {
        this.pmSalterdate = pmSalterdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF1
     *
     * @return the value of EP_PAYMONEY.PM_SDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef1() {
        return pmSdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF1
     *
     * @param pmSdef1 the value for EP_PAYMONEY.PM_SDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef1(String pmSdef1) {
        this.pmSdef1 = pmSdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF2
     *
     * @return the value of EP_PAYMONEY.PM_SDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef2() {
        return pmSdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF2
     *
     * @param pmSdef2 the value for EP_PAYMONEY.PM_SDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef2(String pmSdef2) {
        this.pmSdef2 = pmSdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF3
     *
     * @return the value of EP_PAYMONEY.PM_SDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef3() {
        return pmSdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF3
     *
     * @param pmSdef3 the value for EP_PAYMONEY.PM_SDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef3(String pmSdef3) {
        this.pmSdef3 = pmSdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF4
     *
     * @return the value of EP_PAYMONEY.PM_SDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef4() {
        return pmSdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF4
     *
     * @param pmSdef4 the value for EP_PAYMONEY.PM_SDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef4(String pmSdef4) {
        this.pmSdef4 = pmSdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF5
     *
     * @return the value of EP_PAYMONEY.PM_SDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef5() {
        return pmSdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF5
     *
     * @param pmSdef5 the value for EP_PAYMONEY.PM_SDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef5(String pmSdef5) {
        this.pmSdef5 = pmSdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF6
     *
     * @return the value of EP_PAYMONEY.PM_SDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef6() {
        return pmSdef6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF6
     *
     * @param pmSdef6 the value for EP_PAYMONEY.PM_SDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef6(String pmSdef6) {
        this.pmSdef6 = pmSdef6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF7
     *
     * @return the value of EP_PAYMONEY.PM_SDEF7
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef7() {
        return pmSdef7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF7
     *
     * @param pmSdef7 the value for EP_PAYMONEY.PM_SDEF7
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef7(String pmSdef7) {
        this.pmSdef7 = pmSdef7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF8
     *
     * @return the value of EP_PAYMONEY.PM_SDEF8
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef8() {
        return pmSdef8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF8
     *
     * @param pmSdef8 the value for EP_PAYMONEY.PM_SDEF8
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef8(String pmSdef8) {
        this.pmSdef8 = pmSdef8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF9
     *
     * @return the value of EP_PAYMONEY.PM_SDEF9
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef9() {
        return pmSdef9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF9
     *
     * @param pmSdef9 the value for EP_PAYMONEY.PM_SDEF9
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef9(String pmSdef9) {
        this.pmSdef9 = pmSdef9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF10
     *
     * @return the value of EP_PAYMONEY.PM_SDEF10
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef10() {
        return pmSdef10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF10
     *
     * @param pmSdef10 the value for EP_PAYMONEY.PM_SDEF10
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef10(String pmSdef10) {
        this.pmSdef10 = pmSdef10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF11
     *
     * @return the value of EP_PAYMONEY.PM_SDEF11
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef11() {
        return pmSdef11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF11
     *
     * @param pmSdef11 the value for EP_PAYMONEY.PM_SDEF11
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef11(String pmSdef11) {
        this.pmSdef11 = pmSdef11;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF12
     *
     * @return the value of EP_PAYMONEY.PM_SDEF12
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef12() {
        return pmSdef12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF12
     *
     * @param pmSdef12 the value for EP_PAYMONEY.PM_SDEF12
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef12(String pmSdef12) {
        this.pmSdef12 = pmSdef12;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF13
     *
     * @return the value of EP_PAYMONEY.PM_SDEF13
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef13() {
        return pmSdef13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF13
     *
     * @param pmSdef13 the value for EP_PAYMONEY.PM_SDEF13
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef13(String pmSdef13) {
        this.pmSdef13 = pmSdef13;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF14
     *
     * @return the value of EP_PAYMONEY.PM_SDEF14
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef14() {
        return pmSdef14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF14
     *
     * @param pmSdef14 the value for EP_PAYMONEY.PM_SDEF14
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef14(String pmSdef14) {
        this.pmSdef14 = pmSdef14;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF15
     *
     * @return the value of EP_PAYMONEY.PM_SDEF15
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef15() {
        return pmSdef15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF15
     *
     * @param pmSdef15 the value for EP_PAYMONEY.PM_SDEF15
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef15(String pmSdef15) {
        this.pmSdef15 = pmSdef15;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF16
     *
     * @return the value of EP_PAYMONEY.PM_SDEF16
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef16() {
        return pmSdef16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF16
     *
     * @param pmSdef16 the value for EP_PAYMONEY.PM_SDEF16
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef16(String pmSdef16) {
        this.pmSdef16 = pmSdef16;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF17
     *
     * @return the value of EP_PAYMONEY.PM_SDEF17
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef17() {
        return pmSdef17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF17
     *
     * @param pmSdef17 the value for EP_PAYMONEY.PM_SDEF17
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef17(String pmSdef17) {
        this.pmSdef17 = pmSdef17;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF18
     *
     * @return the value of EP_PAYMONEY.PM_SDEF18
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef18() {
        return pmSdef18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF18
     *
     * @param pmSdef18 the value for EP_PAYMONEY.PM_SDEF18
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef18(String pmSdef18) {
        this.pmSdef18 = pmSdef18;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF19
     *
     * @return the value of EP_PAYMONEY.PM_SDEF19
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef19() {
        return pmSdef19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF19
     *
     * @param pmSdef19 the value for EP_PAYMONEY.PM_SDEF19
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef19(String pmSdef19) {
        this.pmSdef19 = pmSdef19;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_SDEF20
     *
     * @return the value of EP_PAYMONEY.PM_SDEF20
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getPmSdef20() {
        return pmSdef20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_SDEF20
     *
     * @param pmSdef20 the value for EP_PAYMONEY.PM_SDEF20
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmSdef20(String pmSdef20) {
        this.pmSdef20 = pmSdef20;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_NDEF1
     *
     * @return the value of EP_PAYMONEY.PM_NDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getPmNdef1() {
        return pmNdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_NDEF1
     *
     * @param pmNdef1 the value for EP_PAYMONEY.PM_NDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmNdef1(BigDecimal pmNdef1) {
        this.pmNdef1 = pmNdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_NDEF2
     *
     * @return the value of EP_PAYMONEY.PM_NDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getPmNdef2() {
        return pmNdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_NDEF2
     *
     * @param pmNdef2 the value for EP_PAYMONEY.PM_NDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmNdef2(BigDecimal pmNdef2) {
        this.pmNdef2 = pmNdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_NDEF3
     *
     * @return the value of EP_PAYMONEY.PM_NDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getPmNdef3() {
        return pmNdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_NDEF3
     *
     * @param pmNdef3 the value for EP_PAYMONEY.PM_NDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmNdef3(BigDecimal pmNdef3) {
        this.pmNdef3 = pmNdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_NDEF4
     *
     * @return the value of EP_PAYMONEY.PM_NDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getPmNdef4() {
        return pmNdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_NDEF4
     *
     * @param pmNdef4 the value for EP_PAYMONEY.PM_NDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmNdef4(BigDecimal pmNdef4) {
        this.pmNdef4 = pmNdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_NDEF5
     *
     * @return the value of EP_PAYMONEY.PM_NDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getPmNdef5() {
        return pmNdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_NDEF5
     *
     * @param pmNdef5 the value for EP_PAYMONEY.PM_NDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmNdef5(BigDecimal pmNdef5) {
        this.pmNdef5 = pmNdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_TDEF1
     *
     * @return the value of EP_PAYMONEY.PM_TDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getPmTdef1() {
        return pmTdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_TDEF1
     *
     * @param pmTdef1 the value for EP_PAYMONEY.PM_TDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmTdef1(Date pmTdef1) {
        this.pmTdef1 = pmTdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_TDEF2
     *
     * @return the value of EP_PAYMONEY.PM_TDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getPmTdef2() {
        return pmTdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_TDEF2
     *
     * @param pmTdef2 the value for EP_PAYMONEY.PM_TDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmTdef2(Date pmTdef2) {
        this.pmTdef2 = pmTdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_TDEF3
     *
     * @return the value of EP_PAYMONEY.PM_TDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getPmTdef3() {
        return pmTdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_TDEF3
     *
     * @param pmTdef3 the value for EP_PAYMONEY.PM_TDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmTdef3(Date pmTdef3) {
        this.pmTdef3 = pmTdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_TDEF4
     *
     * @return the value of EP_PAYMONEY.PM_TDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getPmTdef4() {
        return pmTdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_TDEF4
     *
     * @param pmTdef4 the value for EP_PAYMONEY.PM_TDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmTdef4(Date pmTdef4) {
        this.pmTdef4 = pmTdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column EP_PAYMONEY.PM_TDEF5
     *
     * @return the value of EP_PAYMONEY.PM_TDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getPmTdef5() {
        return pmTdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column EP_PAYMONEY.PM_TDEF5
     *
     * @param pmTdef5 the value for EP_PAYMONEY.PM_TDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setPmTdef5(Date pmTdef5) {
        this.pmTdef5 = pmTdef5;
    }
}