package com.rc.project.vo;

import java.math.BigDecimal;
import java.util.Date;

public class EpProject {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SID
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.RP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SYEAR
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSyear;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SNAMEXIAO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSnamexiao;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SMONEY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal epSmoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SISZC
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSiszc;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.UD_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String udSno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SPERDEPARTNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSperdepartname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EMP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String empSno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SPERSON
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSperson;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SISDEL
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSisdel;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SISVALID
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSisvalid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SREPLYBY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSreplyby;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SREPLYDATE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date epSreplydate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SALTERBY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSalterby;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SALTERDATE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date epSalterdate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef4;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef5;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF6
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef6;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF7
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef7;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF8
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef8;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF9
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef9;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF10
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef10;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF11
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef11;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF12
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef12;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF13
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef13;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF14
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef14;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF15
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef15;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF16
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef16;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF17
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef17;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF18
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef18;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF19
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef19;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_SDEF20
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String epSdef20;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_NDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal epNdef1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_NDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal epNdef2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_NDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal epNdef3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_NDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal epNdef4;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_NDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal epNdef5;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_NDEF6
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal epNdef6;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_NDEF7
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal epNdef7;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_NDEF8
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal epNdef8;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_NDEF9
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal epNdef9;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_NDEF10
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal epNdef10;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_DDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date epDdef1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_DDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date epDdef2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_DDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date epDdef3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_DDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date epDdef4;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column EP_PROJECT.EP_DDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date epDdef5;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SID
	 * @return  the value of EP_PROJECT.EP_SID
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSid() {
		return epSid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SID
	 * @param epSid  the value for EP_PROJECT.EP_SID
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSid(String epSid) {
		this.epSid = epSid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SNO
	 * @return  the value of EP_PROJECT.EP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSno() {
		return epSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SNO
	 * @param epSno  the value for EP_PROJECT.EP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSno(String epSno) {
		this.epSno = epSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.RP_SNO
	 * @return  the value of EP_PROJECT.RP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSno() {
		return rpSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.RP_SNO
	 * @param rpSno  the value for EP_PROJECT.RP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSno(String rpSno) {
		this.rpSno = rpSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SYEAR
	 * @return  the value of EP_PROJECT.EP_SYEAR
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSyear() {
		return epSyear;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SYEAR
	 * @param epSyear  the value for EP_PROJECT.EP_SYEAR
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSyear(String epSyear) {
		this.epSyear = epSyear;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SNAME
	 * @return  the value of EP_PROJECT.EP_SNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSname() {
		return epSname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SNAME
	 * @param epSname  the value for EP_PROJECT.EP_SNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSname(String epSname) {
		this.epSname = epSname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SNAMEXIAO
	 * @return  the value of EP_PROJECT.EP_SNAMEXIAO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSnamexiao() {
		return epSnamexiao;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SNAMEXIAO
	 * @param epSnamexiao  the value for EP_PROJECT.EP_SNAMEXIAO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSnamexiao(String epSnamexiao) {
		this.epSnamexiao = epSnamexiao;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SMONEY
	 * @return  the value of EP_PROJECT.EP_SMONEY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getEpSmoney() {
		return epSmoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SMONEY
	 * @param epSmoney  the value for EP_PROJECT.EP_SMONEY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSmoney(BigDecimal epSmoney) {
		this.epSmoney = epSmoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SISZC
	 * @return  the value of EP_PROJECT.EP_SISZC
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSiszc() {
		return epSiszc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SISZC
	 * @param epSiszc  the value for EP_PROJECT.EP_SISZC
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSiszc(String epSiszc) {
		this.epSiszc = epSiszc;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.UD_SNO
	 * @return  the value of EP_PROJECT.UD_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getUdSno() {
		return udSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.UD_SNO
	 * @param udSno  the value for EP_PROJECT.UD_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setUdSno(String udSno) {
		this.udSno = udSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SPERDEPARTNAME
	 * @return  the value of EP_PROJECT.EP_SPERDEPARTNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSperdepartname() {
		return epSperdepartname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SPERDEPARTNAME
	 * @param epSperdepartname  the value for EP_PROJECT.EP_SPERDEPARTNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSperdepartname(String epSperdepartname) {
		this.epSperdepartname = epSperdepartname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EMP_SNO
	 * @return  the value of EP_PROJECT.EMP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEmpSno() {
		return empSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EMP_SNO
	 * @param empSno  the value for EP_PROJECT.EMP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEmpSno(String empSno) {
		this.empSno = empSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SPERSON
	 * @return  the value of EP_PROJECT.EP_SPERSON
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSperson() {
		return epSperson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SPERSON
	 * @param epSperson  the value for EP_PROJECT.EP_SPERSON
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSperson(String epSperson) {
		this.epSperson = epSperson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SISDEL
	 * @return  the value of EP_PROJECT.EP_SISDEL
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSisdel() {
		return epSisdel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SISDEL
	 * @param epSisdel  the value for EP_PROJECT.EP_SISDEL
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSisdel(String epSisdel) {
		this.epSisdel = epSisdel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SISVALID
	 * @return  the value of EP_PROJECT.EP_SISVALID
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSisvalid() {
		return epSisvalid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SISVALID
	 * @param epSisvalid  the value for EP_PROJECT.EP_SISVALID
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSisvalid(String epSisvalid) {
		this.epSisvalid = epSisvalid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SREPLYBY
	 * @return  the value of EP_PROJECT.EP_SREPLYBY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSreplyby() {
		return epSreplyby;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SREPLYBY
	 * @param epSreplyby  the value for EP_PROJECT.EP_SREPLYBY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSreplyby(String epSreplyby) {
		this.epSreplyby = epSreplyby;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SREPLYDATE
	 * @return  the value of EP_PROJECT.EP_SREPLYDATE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getEpSreplydate() {
		return epSreplydate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SREPLYDATE
	 * @param epSreplydate  the value for EP_PROJECT.EP_SREPLYDATE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSreplydate(Date epSreplydate) {
		this.epSreplydate = epSreplydate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SALTERBY
	 * @return  the value of EP_PROJECT.EP_SALTERBY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSalterby() {
		return epSalterby;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SALTERBY
	 * @param epSalterby  the value for EP_PROJECT.EP_SALTERBY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSalterby(String epSalterby) {
		this.epSalterby = epSalterby;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SALTERDATE
	 * @return  the value of EP_PROJECT.EP_SALTERDATE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getEpSalterdate() {
		return epSalterdate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SALTERDATE
	 * @param epSalterdate  the value for EP_PROJECT.EP_SALTERDATE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSalterdate(Date epSalterdate) {
		this.epSalterdate = epSalterdate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF1
	 * @return  the value of EP_PROJECT.EP_SDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef1() {
		return epSdef1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF1
	 * @param epSdef1  the value for EP_PROJECT.EP_SDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef1(String epSdef1) {
		this.epSdef1 = epSdef1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF2
	 * @return  the value of EP_PROJECT.EP_SDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef2() {
		return epSdef2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF2
	 * @param epSdef2  the value for EP_PROJECT.EP_SDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef2(String epSdef2) {
		this.epSdef2 = epSdef2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF3
	 * @return  the value of EP_PROJECT.EP_SDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef3() {
		return epSdef3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF3
	 * @param epSdef3  the value for EP_PROJECT.EP_SDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef3(String epSdef3) {
		this.epSdef3 = epSdef3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF4
	 * @return  the value of EP_PROJECT.EP_SDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef4() {
		return epSdef4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF4
	 * @param epSdef4  the value for EP_PROJECT.EP_SDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef4(String epSdef4) {
		this.epSdef4 = epSdef4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF5
	 * @return  the value of EP_PROJECT.EP_SDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef5() {
		return epSdef5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF5
	 * @param epSdef5  the value for EP_PROJECT.EP_SDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef5(String epSdef5) {
		this.epSdef5 = epSdef5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF6
	 * @return  the value of EP_PROJECT.EP_SDEF6
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef6() {
		return epSdef6;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF6
	 * @param epSdef6  the value for EP_PROJECT.EP_SDEF6
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef6(String epSdef6) {
		this.epSdef6 = epSdef6;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF7
	 * @return  the value of EP_PROJECT.EP_SDEF7
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef7() {
		return epSdef7;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF7
	 * @param epSdef7  the value for EP_PROJECT.EP_SDEF7
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef7(String epSdef7) {
		this.epSdef7 = epSdef7;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF8
	 * @return  the value of EP_PROJECT.EP_SDEF8
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef8() {
		return epSdef8;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF8
	 * @param epSdef8  the value for EP_PROJECT.EP_SDEF8
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef8(String epSdef8) {
		this.epSdef8 = epSdef8;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF9
	 * @return  the value of EP_PROJECT.EP_SDEF9
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef9() {
		return epSdef9;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF9
	 * @param epSdef9  the value for EP_PROJECT.EP_SDEF9
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef9(String epSdef9) {
		this.epSdef9 = epSdef9;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF10
	 * @return  the value of EP_PROJECT.EP_SDEF10
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef10() {
		return epSdef10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF10
	 * @param epSdef10  the value for EP_PROJECT.EP_SDEF10
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef10(String epSdef10) {
		this.epSdef10 = epSdef10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF11
	 * @return  the value of EP_PROJECT.EP_SDEF11
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef11() {
		return epSdef11;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF11
	 * @param epSdef11  the value for EP_PROJECT.EP_SDEF11
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef11(String epSdef11) {
		this.epSdef11 = epSdef11;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF12
	 * @return  the value of EP_PROJECT.EP_SDEF12
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef12() {
		return epSdef12;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF12
	 * @param epSdef12  the value for EP_PROJECT.EP_SDEF12
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef12(String epSdef12) {
		this.epSdef12 = epSdef12;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF13
	 * @return  the value of EP_PROJECT.EP_SDEF13
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef13() {
		return epSdef13;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF13
	 * @param epSdef13  the value for EP_PROJECT.EP_SDEF13
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef13(String epSdef13) {
		this.epSdef13 = epSdef13;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF14
	 * @return  the value of EP_PROJECT.EP_SDEF14
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef14() {
		return epSdef14;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF14
	 * @param epSdef14  the value for EP_PROJECT.EP_SDEF14
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef14(String epSdef14) {
		this.epSdef14 = epSdef14;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF15
	 * @return  the value of EP_PROJECT.EP_SDEF15
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef15() {
		return epSdef15;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF15
	 * @param epSdef15  the value for EP_PROJECT.EP_SDEF15
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef15(String epSdef15) {
		this.epSdef15 = epSdef15;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF16
	 * @return  the value of EP_PROJECT.EP_SDEF16
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef16() {
		return epSdef16;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF16
	 * @param epSdef16  the value for EP_PROJECT.EP_SDEF16
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef16(String epSdef16) {
		this.epSdef16 = epSdef16;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF17
	 * @return  the value of EP_PROJECT.EP_SDEF17
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef17() {
		return epSdef17;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF17
	 * @param epSdef17  the value for EP_PROJECT.EP_SDEF17
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef17(String epSdef17) {
		this.epSdef17 = epSdef17;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF18
	 * @return  the value of EP_PROJECT.EP_SDEF18
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef18() {
		return epSdef18;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF18
	 * @param epSdef18  the value for EP_PROJECT.EP_SDEF18
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef18(String epSdef18) {
		this.epSdef18 = epSdef18;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF19
	 * @return  the value of EP_PROJECT.EP_SDEF19
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef19() {
		return epSdef19;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF19
	 * @param epSdef19  the value for EP_PROJECT.EP_SDEF19
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef19(String epSdef19) {
		this.epSdef19 = epSdef19;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_SDEF20
	 * @return  the value of EP_PROJECT.EP_SDEF20
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEpSdef20() {
		return epSdef20;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_SDEF20
	 * @param epSdef20  the value for EP_PROJECT.EP_SDEF20
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpSdef20(String epSdef20) {
		this.epSdef20 = epSdef20;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_NDEF1
	 * @return  the value of EP_PROJECT.EP_NDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getEpNdef1() {
		return epNdef1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_NDEF1
	 * @param epNdef1  the value for EP_PROJECT.EP_NDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpNdef1(BigDecimal epNdef1) {
		this.epNdef1 = epNdef1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_NDEF2
	 * @return  the value of EP_PROJECT.EP_NDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getEpNdef2() {
		return epNdef2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_NDEF2
	 * @param epNdef2  the value for EP_PROJECT.EP_NDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpNdef2(BigDecimal epNdef2) {
		this.epNdef2 = epNdef2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_NDEF3
	 * @return  the value of EP_PROJECT.EP_NDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getEpNdef3() {
		return epNdef3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_NDEF3
	 * @param epNdef3  the value for EP_PROJECT.EP_NDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpNdef3(BigDecimal epNdef3) {
		this.epNdef3 = epNdef3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_NDEF4
	 * @return  the value of EP_PROJECT.EP_NDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getEpNdef4() {
		return epNdef4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_NDEF4
	 * @param epNdef4  the value for EP_PROJECT.EP_NDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpNdef4(BigDecimal epNdef4) {
		this.epNdef4 = epNdef4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_NDEF5
	 * @return  the value of EP_PROJECT.EP_NDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getEpNdef5() {
		return epNdef5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_NDEF5
	 * @param epNdef5  the value for EP_PROJECT.EP_NDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpNdef5(BigDecimal epNdef5) {
		this.epNdef5 = epNdef5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_NDEF6
	 * @return  the value of EP_PROJECT.EP_NDEF6
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getEpNdef6() {
		return epNdef6;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_NDEF6
	 * @param epNdef6  the value for EP_PROJECT.EP_NDEF6
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpNdef6(BigDecimal epNdef6) {
		this.epNdef6 = epNdef6;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_NDEF7
	 * @return  the value of EP_PROJECT.EP_NDEF7
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getEpNdef7() {
		return epNdef7;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_NDEF7
	 * @param epNdef7  the value for EP_PROJECT.EP_NDEF7
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpNdef7(BigDecimal epNdef7) {
		this.epNdef7 = epNdef7;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_NDEF8
	 * @return  the value of EP_PROJECT.EP_NDEF8
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getEpNdef8() {
		return epNdef8;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_NDEF8
	 * @param epNdef8  the value for EP_PROJECT.EP_NDEF8
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpNdef8(BigDecimal epNdef8) {
		this.epNdef8 = epNdef8;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_NDEF9
	 * @return  the value of EP_PROJECT.EP_NDEF9
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getEpNdef9() {
		return epNdef9;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_NDEF9
	 * @param epNdef9  the value for EP_PROJECT.EP_NDEF9
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpNdef9(BigDecimal epNdef9) {
		this.epNdef9 = epNdef9;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_NDEF10
	 * @return  the value of EP_PROJECT.EP_NDEF10
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getEpNdef10() {
		return epNdef10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_NDEF10
	 * @param epNdef10  the value for EP_PROJECT.EP_NDEF10
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpNdef10(BigDecimal epNdef10) {
		this.epNdef10 = epNdef10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_DDEF1
	 * @return  the value of EP_PROJECT.EP_DDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getEpDdef1() {
		return epDdef1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_DDEF1
	 * @param epDdef1  the value for EP_PROJECT.EP_DDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpDdef1(Date epDdef1) {
		this.epDdef1 = epDdef1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_DDEF2
	 * @return  the value of EP_PROJECT.EP_DDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getEpDdef2() {
		return epDdef2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_DDEF2
	 * @param epDdef2  the value for EP_PROJECT.EP_DDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpDdef2(Date epDdef2) {
		this.epDdef2 = epDdef2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_DDEF3
	 * @return  the value of EP_PROJECT.EP_DDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getEpDdef3() {
		return epDdef3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_DDEF3
	 * @param epDdef3  the value for EP_PROJECT.EP_DDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpDdef3(Date epDdef3) {
		this.epDdef3 = epDdef3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_DDEF4
	 * @return  the value of EP_PROJECT.EP_DDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getEpDdef4() {
		return epDdef4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_DDEF4
	 * @param epDdef4  the value for EP_PROJECT.EP_DDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpDdef4(Date epDdef4) {
		this.epDdef4 = epDdef4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column EP_PROJECT.EP_DDEF5
	 * @return  the value of EP_PROJECT.EP_DDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getEpDdef5() {
		return epDdef5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column EP_PROJECT.EP_DDEF5
	 * @param epDdef5  the value for EP_PROJECT.EP_DDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEpDdef5(Date epDdef5) {
		this.epDdef5 = epDdef5;
	}
}