package com.rc.project.vo;

import java.math.BigDecimal;
import java.util.Date;

public class RpFile {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_NID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private BigDecimal rpfNid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_STYPE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfStype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SURL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSurl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SYEAR
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSyear;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SISDEL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSisdel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SISVALID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSisvalid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SREPLYBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSreplyby;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SREPLYDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date rpfSreplydate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SALTERBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSalterby;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SALTERDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private Date rpfSalterdate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSdef1;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSdef2;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSdef3;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSdef4;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSdef5;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSdef6;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SDEF7
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSdef7;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SDEF8
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSdef8;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SDEF9
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSdef9;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column RP_FILE.RPF_SDEF10
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private String rpfSdef10;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_NID
     *
     * @return the value of RP_FILE.RPF_NID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public BigDecimal getRpfNid() {
        return rpfNid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_NID
     *
     * @param rpfNid the value for RP_FILE.RPF_NID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfNid(BigDecimal rpfNid) {
        this.rpfNid = rpfNid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_STYPE
     *
     * @return the value of RP_FILE.RPF_STYPE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfStype() {
        return rpfStype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_STYPE
     *
     * @param rpfStype the value for RP_FILE.RPF_STYPE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfStype(String rpfStype) {
        this.rpfStype = rpfStype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SURL
     *
     * @return the value of RP_FILE.RPF_SURL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSurl() {
        return rpfSurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SURL
     *
     * @param rpfSurl the value for RP_FILE.RPF_SURL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSurl(String rpfSurl) {
        this.rpfSurl = rpfSurl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SYEAR
     *
     * @return the value of RP_FILE.RPF_SYEAR
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSyear() {
        return rpfSyear;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SYEAR
     *
     * @param rpfSyear the value for RP_FILE.RPF_SYEAR
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSyear(String rpfSyear) {
        this.rpfSyear = rpfSyear;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SISDEL
     *
     * @return the value of RP_FILE.RPF_SISDEL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSisdel() {
        return rpfSisdel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SISDEL
     *
     * @param rpfSisdel the value for RP_FILE.RPF_SISDEL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSisdel(String rpfSisdel) {
        this.rpfSisdel = rpfSisdel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SISVALID
     *
     * @return the value of RP_FILE.RPF_SISVALID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSisvalid() {
        return rpfSisvalid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SISVALID
     *
     * @param rpfSisvalid the value for RP_FILE.RPF_SISVALID
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSisvalid(String rpfSisvalid) {
        this.rpfSisvalid = rpfSisvalid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SREPLYBY
     *
     * @return the value of RP_FILE.RPF_SREPLYBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSreplyby() {
        return rpfSreplyby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SREPLYBY
     *
     * @param rpfSreplyby the value for RP_FILE.RPF_SREPLYBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSreplyby(String rpfSreplyby) {
        this.rpfSreplyby = rpfSreplyby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SREPLYDATE
     *
     * @return the value of RP_FILE.RPF_SREPLYDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getRpfSreplydate() {
        return rpfSreplydate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SREPLYDATE
     *
     * @param rpfSreplydate the value for RP_FILE.RPF_SREPLYDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSreplydate(Date rpfSreplydate) {
        this.rpfSreplydate = rpfSreplydate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SALTERBY
     *
     * @return the value of RP_FILE.RPF_SALTERBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSalterby() {
        return rpfSalterby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SALTERBY
     *
     * @param rpfSalterby the value for RP_FILE.RPF_SALTERBY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSalterby(String rpfSalterby) {
        this.rpfSalterby = rpfSalterby;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SALTERDATE
     *
     * @return the value of RP_FILE.RPF_SALTERDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Date getRpfSalterdate() {
        return rpfSalterdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SALTERDATE
     *
     * @param rpfSalterdate the value for RP_FILE.RPF_SALTERDATE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSalterdate(Date rpfSalterdate) {
        this.rpfSalterdate = rpfSalterdate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SDEF1
     *
     * @return the value of RP_FILE.RPF_SDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSdef1() {
        return rpfSdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SDEF1
     *
     * @param rpfSdef1 the value for RP_FILE.RPF_SDEF1
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSdef1(String rpfSdef1) {
        this.rpfSdef1 = rpfSdef1;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SDEF2
     *
     * @return the value of RP_FILE.RPF_SDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSdef2() {
        return rpfSdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SDEF2
     *
     * @param rpfSdef2 the value for RP_FILE.RPF_SDEF2
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSdef2(String rpfSdef2) {
        this.rpfSdef2 = rpfSdef2;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SDEF3
     *
     * @return the value of RP_FILE.RPF_SDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSdef3() {
        return rpfSdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SDEF3
     *
     * @param rpfSdef3 the value for RP_FILE.RPF_SDEF3
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSdef3(String rpfSdef3) {
        this.rpfSdef3 = rpfSdef3;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SDEF4
     *
     * @return the value of RP_FILE.RPF_SDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSdef4() {
        return rpfSdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SDEF4
     *
     * @param rpfSdef4 the value for RP_FILE.RPF_SDEF4
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSdef4(String rpfSdef4) {
        this.rpfSdef4 = rpfSdef4;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SDEF5
     *
     * @return the value of RP_FILE.RPF_SDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSdef5() {
        return rpfSdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SDEF5
     *
     * @param rpfSdef5 the value for RP_FILE.RPF_SDEF5
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSdef5(String rpfSdef5) {
        this.rpfSdef5 = rpfSdef5;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SDEF6
     *
     * @return the value of RP_FILE.RPF_SDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSdef6() {
        return rpfSdef6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SDEF6
     *
     * @param rpfSdef6 the value for RP_FILE.RPF_SDEF6
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSdef6(String rpfSdef6) {
        this.rpfSdef6 = rpfSdef6;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SDEF7
     *
     * @return the value of RP_FILE.RPF_SDEF7
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSdef7() {
        return rpfSdef7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SDEF7
     *
     * @param rpfSdef7 the value for RP_FILE.RPF_SDEF7
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSdef7(String rpfSdef7) {
        this.rpfSdef7 = rpfSdef7;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SDEF8
     *
     * @return the value of RP_FILE.RPF_SDEF8
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSdef8() {
        return rpfSdef8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SDEF8
     *
     * @param rpfSdef8 the value for RP_FILE.RPF_SDEF8
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSdef8(String rpfSdef8) {
        this.rpfSdef8 = rpfSdef8;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SDEF9
     *
     * @return the value of RP_FILE.RPF_SDEF9
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSdef9() {
        return rpfSdef9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SDEF9
     *
     * @param rpfSdef9 the value for RP_FILE.RPF_SDEF9
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSdef9(String rpfSdef9) {
        this.rpfSdef9 = rpfSdef9;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column RP_FILE.RPF_SDEF10
     *
     * @return the value of RP_FILE.RPF_SDEF10
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getRpfSdef10() {
        return rpfSdef10;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column RP_FILE.RPF_SDEF10
     *
     * @param rpfSdef10 the value for RP_FILE.RPF_SDEF10
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setRpfSdef10(String rpfSdef10) {
        this.rpfSdef10 = rpfSdef10;
    }
}