package com.rc.project.vo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class RpFileExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table RP_FILE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table RP_FILE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_FILE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public RpFileExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_FILE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    protected RpFileExample(RpFileExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_FILE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_FILE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_FILE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_FILE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_FILE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_FILE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_FILE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table RP_FILE
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andRpfNidIsNull() {
            addCriterion("RPF_NID is null");
            return this;
        }

        public Criteria andRpfNidIsNotNull() {
            addCriterion("RPF_NID is not null");
            return this;
        }

        public Criteria andRpfNidEqualTo(BigDecimal value) {
            addCriterion("RPF_NID =", value, "rpfNid");
            return this;
        }

        public Criteria andRpfNidNotEqualTo(BigDecimal value) {
            addCriterion("RPF_NID <>", value, "rpfNid");
            return this;
        }

        public Criteria andRpfNidGreaterThan(BigDecimal value) {
            addCriterion("RPF_NID >", value, "rpfNid");
            return this;
        }

        public Criteria andRpfNidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RPF_NID >=", value, "rpfNid");
            return this;
        }

        public Criteria andRpfNidLessThan(BigDecimal value) {
            addCriterion("RPF_NID <", value, "rpfNid");
            return this;
        }

        public Criteria andRpfNidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RPF_NID <=", value, "rpfNid");
            return this;
        }

        public Criteria andRpfNidIn(List values) {
            addCriterion("RPF_NID in", values, "rpfNid");
            return this;
        }

        public Criteria andRpfNidNotIn(List values) {
            addCriterion("RPF_NID not in", values, "rpfNid");
            return this;
        }

        public Criteria andRpfNidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RPF_NID between", value1, value2, "rpfNid");
            return this;
        }

        public Criteria andRpfNidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RPF_NID not between", value1, value2, "rpfNid");
            return this;
        }

        public Criteria andRpfStypeIsNull() {
            addCriterion("RPF_STYPE is null");
            return this;
        }

        public Criteria andRpfStypeIsNotNull() {
            addCriterion("RPF_STYPE is not null");
            return this;
        }

        public Criteria andRpfStypeEqualTo(String value) {
            addCriterion("RPF_STYPE =", value, "rpfStype");
            return this;
        }

        public Criteria andRpfStypeNotEqualTo(String value) {
            addCriterion("RPF_STYPE <>", value, "rpfStype");
            return this;
        }

        public Criteria andRpfStypeGreaterThan(String value) {
            addCriterion("RPF_STYPE >", value, "rpfStype");
            return this;
        }

        public Criteria andRpfStypeGreaterThanOrEqualTo(String value) {
            addCriterion("RPF_STYPE >=", value, "rpfStype");
            return this;
        }

        public Criteria andRpfStypeLessThan(String value) {
            addCriterion("RPF_STYPE <", value, "rpfStype");
            return this;
        }

        public Criteria andRpfStypeLessThanOrEqualTo(String value) {
            addCriterion("RPF_STYPE <=", value, "rpfStype");
            return this;
        }

        public Criteria andRpfStypeLike(String value) {
            addCriterion("RPF_STYPE like", value, "rpfStype");
            return this;
        }

        public Criteria andRpfStypeNotLike(String value) {
            addCriterion("RPF_STYPE not like", value, "rpfStype");
            return this;
        }

        public Criteria andRpfStypeIn(List values) {
            addCriterion("RPF_STYPE in", values, "rpfStype");
            return this;
        }

        public Criteria andRpfStypeNotIn(List values) {
            addCriterion("RPF_STYPE not in", values, "rpfStype");
            return this;
        }

        public Criteria andRpfStypeBetween(String value1, String value2) {
            addCriterion("RPF_STYPE between", value1, value2, "rpfStype");
            return this;
        }

        public Criteria andRpfStypeNotBetween(String value1, String value2) {
            addCriterion("RPF_STYPE not between", value1, value2, "rpfStype");
            return this;
        }

        public Criteria andRpfSurlIsNull() {
            addCriterion("RPF_SURL is null");
            return this;
        }

        public Criteria andRpfSurlIsNotNull() {
            addCriterion("RPF_SURL is not null");
            return this;
        }

        public Criteria andRpfSurlEqualTo(String value) {
            addCriterion("RPF_SURL =", value, "rpfSurl");
            return this;
        }

        public Criteria andRpfSurlNotEqualTo(String value) {
            addCriterion("RPF_SURL <>", value, "rpfSurl");
            return this;
        }

        public Criteria andRpfSurlGreaterThan(String value) {
            addCriterion("RPF_SURL >", value, "rpfSurl");
            return this;
        }

        public Criteria andRpfSurlGreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SURL >=", value, "rpfSurl");
            return this;
        }

        public Criteria andRpfSurlLessThan(String value) {
            addCriterion("RPF_SURL <", value, "rpfSurl");
            return this;
        }

        public Criteria andRpfSurlLessThanOrEqualTo(String value) {
            addCriterion("RPF_SURL <=", value, "rpfSurl");
            return this;
        }

        public Criteria andRpfSurlLike(String value) {
            addCriterion("RPF_SURL like", value, "rpfSurl");
            return this;
        }

        public Criteria andRpfSurlNotLike(String value) {
            addCriterion("RPF_SURL not like", value, "rpfSurl");
            return this;
        }

        public Criteria andRpfSurlIn(List values) {
            addCriterion("RPF_SURL in", values, "rpfSurl");
            return this;
        }

        public Criteria andRpfSurlNotIn(List values) {
            addCriterion("RPF_SURL not in", values, "rpfSurl");
            return this;
        }

        public Criteria andRpfSurlBetween(String value1, String value2) {
            addCriterion("RPF_SURL between", value1, value2, "rpfSurl");
            return this;
        }

        public Criteria andRpfSurlNotBetween(String value1, String value2) {
            addCriterion("RPF_SURL not between", value1, value2, "rpfSurl");
            return this;
        }

        public Criteria andRpfSyearIsNull() {
            addCriterion("RPF_SYEAR is null");
            return this;
        }

        public Criteria andRpfSyearIsNotNull() {
            addCriterion("RPF_SYEAR is not null");
            return this;
        }

        public Criteria andRpfSyearEqualTo(String value) {
            addCriterion("RPF_SYEAR =", value, "rpfSyear");
            return this;
        }

        public Criteria andRpfSyearNotEqualTo(String value) {
            addCriterion("RPF_SYEAR <>", value, "rpfSyear");
            return this;
        }

        public Criteria andRpfSyearGreaterThan(String value) {
            addCriterion("RPF_SYEAR >", value, "rpfSyear");
            return this;
        }

        public Criteria andRpfSyearGreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SYEAR >=", value, "rpfSyear");
            return this;
        }

        public Criteria andRpfSyearLessThan(String value) {
            addCriterion("RPF_SYEAR <", value, "rpfSyear");
            return this;
        }

        public Criteria andRpfSyearLessThanOrEqualTo(String value) {
            addCriterion("RPF_SYEAR <=", value, "rpfSyear");
            return this;
        }

        public Criteria andRpfSyearLike(String value) {
            addCriterion("RPF_SYEAR like", value, "rpfSyear");
            return this;
        }

        public Criteria andRpfSyearNotLike(String value) {
            addCriterion("RPF_SYEAR not like", value, "rpfSyear");
            return this;
        }

        public Criteria andRpfSyearIn(List values) {
            addCriterion("RPF_SYEAR in", values, "rpfSyear");
            return this;
        }

        public Criteria andRpfSyearNotIn(List values) {
            addCriterion("RPF_SYEAR not in", values, "rpfSyear");
            return this;
        }

        public Criteria andRpfSyearBetween(String value1, String value2) {
            addCriterion("RPF_SYEAR between", value1, value2, "rpfSyear");
            return this;
        }

        public Criteria andRpfSyearNotBetween(String value1, String value2) {
            addCriterion("RPF_SYEAR not between", value1, value2, "rpfSyear");
            return this;
        }

        public Criteria andRpfSisdelIsNull() {
            addCriterion("RPF_SISDEL is null");
            return this;
        }

        public Criteria andRpfSisdelIsNotNull() {
            addCriterion("RPF_SISDEL is not null");
            return this;
        }

        public Criteria andRpfSisdelEqualTo(String value) {
            addCriterion("RPF_SISDEL =", value, "rpfSisdel");
            return this;
        }

        public Criteria andRpfSisdelNotEqualTo(String value) {
            addCriterion("RPF_SISDEL <>", value, "rpfSisdel");
            return this;
        }

        public Criteria andRpfSisdelGreaterThan(String value) {
            addCriterion("RPF_SISDEL >", value, "rpfSisdel");
            return this;
        }

        public Criteria andRpfSisdelGreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SISDEL >=", value, "rpfSisdel");
            return this;
        }

        public Criteria andRpfSisdelLessThan(String value) {
            addCriterion("RPF_SISDEL <", value, "rpfSisdel");
            return this;
        }

        public Criteria andRpfSisdelLessThanOrEqualTo(String value) {
            addCriterion("RPF_SISDEL <=", value, "rpfSisdel");
            return this;
        }

        public Criteria andRpfSisdelLike(String value) {
            addCriterion("RPF_SISDEL like", value, "rpfSisdel");
            return this;
        }

        public Criteria andRpfSisdelNotLike(String value) {
            addCriterion("RPF_SISDEL not like", value, "rpfSisdel");
            return this;
        }

        public Criteria andRpfSisdelIn(List values) {
            addCriterion("RPF_SISDEL in", values, "rpfSisdel");
            return this;
        }

        public Criteria andRpfSisdelNotIn(List values) {
            addCriterion("RPF_SISDEL not in", values, "rpfSisdel");
            return this;
        }

        public Criteria andRpfSisdelBetween(String value1, String value2) {
            addCriterion("RPF_SISDEL between", value1, value2, "rpfSisdel");
            return this;
        }

        public Criteria andRpfSisdelNotBetween(String value1, String value2) {
            addCriterion("RPF_SISDEL not between", value1, value2, "rpfSisdel");
            return this;
        }

        public Criteria andRpfSisvalidIsNull() {
            addCriterion("RPF_SISVALID is null");
            return this;
        }

        public Criteria andRpfSisvalidIsNotNull() {
            addCriterion("RPF_SISVALID is not null");
            return this;
        }

        public Criteria andRpfSisvalidEqualTo(String value) {
            addCriterion("RPF_SISVALID =", value, "rpfSisvalid");
            return this;
        }

        public Criteria andRpfSisvalidNotEqualTo(String value) {
            addCriterion("RPF_SISVALID <>", value, "rpfSisvalid");
            return this;
        }

        public Criteria andRpfSisvalidGreaterThan(String value) {
            addCriterion("RPF_SISVALID >", value, "rpfSisvalid");
            return this;
        }

        public Criteria andRpfSisvalidGreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SISVALID >=", value, "rpfSisvalid");
            return this;
        }

        public Criteria andRpfSisvalidLessThan(String value) {
            addCriterion("RPF_SISVALID <", value, "rpfSisvalid");
            return this;
        }

        public Criteria andRpfSisvalidLessThanOrEqualTo(String value) {
            addCriterion("RPF_SISVALID <=", value, "rpfSisvalid");
            return this;
        }

        public Criteria andRpfSisvalidLike(String value) {
            addCriterion("RPF_SISVALID like", value, "rpfSisvalid");
            return this;
        }

        public Criteria andRpfSisvalidNotLike(String value) {
            addCriterion("RPF_SISVALID not like", value, "rpfSisvalid");
            return this;
        }

        public Criteria andRpfSisvalidIn(List values) {
            addCriterion("RPF_SISVALID in", values, "rpfSisvalid");
            return this;
        }

        public Criteria andRpfSisvalidNotIn(List values) {
            addCriterion("RPF_SISVALID not in", values, "rpfSisvalid");
            return this;
        }

        public Criteria andRpfSisvalidBetween(String value1, String value2) {
            addCriterion("RPF_SISVALID between", value1, value2, "rpfSisvalid");
            return this;
        }

        public Criteria andRpfSisvalidNotBetween(String value1, String value2) {
            addCriterion("RPF_SISVALID not between", value1, value2, "rpfSisvalid");
            return this;
        }

        public Criteria andRpfSreplybyIsNull() {
            addCriterion("RPF_SREPLYBY is null");
            return this;
        }

        public Criteria andRpfSreplybyIsNotNull() {
            addCriterion("RPF_SREPLYBY is not null");
            return this;
        }

        public Criteria andRpfSreplybyEqualTo(String value) {
            addCriterion("RPF_SREPLYBY =", value, "rpfSreplyby");
            return this;
        }

        public Criteria andRpfSreplybyNotEqualTo(String value) {
            addCriterion("RPF_SREPLYBY <>", value, "rpfSreplyby");
            return this;
        }

        public Criteria andRpfSreplybyGreaterThan(String value) {
            addCriterion("RPF_SREPLYBY >", value, "rpfSreplyby");
            return this;
        }

        public Criteria andRpfSreplybyGreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SREPLYBY >=", value, "rpfSreplyby");
            return this;
        }

        public Criteria andRpfSreplybyLessThan(String value) {
            addCriterion("RPF_SREPLYBY <", value, "rpfSreplyby");
            return this;
        }

        public Criteria andRpfSreplybyLessThanOrEqualTo(String value) {
            addCriterion("RPF_SREPLYBY <=", value, "rpfSreplyby");
            return this;
        }

        public Criteria andRpfSreplybyLike(String value) {
            addCriterion("RPF_SREPLYBY like", value, "rpfSreplyby");
            return this;
        }

        public Criteria andRpfSreplybyNotLike(String value) {
            addCriterion("RPF_SREPLYBY not like", value, "rpfSreplyby");
            return this;
        }

        public Criteria andRpfSreplybyIn(List values) {
            addCriterion("RPF_SREPLYBY in", values, "rpfSreplyby");
            return this;
        }

        public Criteria andRpfSreplybyNotIn(List values) {
            addCriterion("RPF_SREPLYBY not in", values, "rpfSreplyby");
            return this;
        }

        public Criteria andRpfSreplybyBetween(String value1, String value2) {
            addCriterion("RPF_SREPLYBY between", value1, value2, "rpfSreplyby");
            return this;
        }

        public Criteria andRpfSreplybyNotBetween(String value1, String value2) {
            addCriterion("RPF_SREPLYBY not between", value1, value2, "rpfSreplyby");
            return this;
        }

        public Criteria andRpfSreplydateIsNull() {
            addCriterion("RPF_SREPLYDATE is null");
            return this;
        }

        public Criteria andRpfSreplydateIsNotNull() {
            addCriterion("RPF_SREPLYDATE is not null");
            return this;
        }

        public Criteria andRpfSreplydateEqualTo(Date value) {
            addCriterionForJDBCDate("RPF_SREPLYDATE =", value, "rpfSreplydate");
            return this;
        }

        public Criteria andRpfSreplydateNotEqualTo(Date value) {
            addCriterionForJDBCDate("RPF_SREPLYDATE <>", value, "rpfSreplydate");
            return this;
        }

        public Criteria andRpfSreplydateGreaterThan(Date value) {
            addCriterionForJDBCDate("RPF_SREPLYDATE >", value, "rpfSreplydate");
            return this;
        }

        public Criteria andRpfSreplydateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RPF_SREPLYDATE >=", value, "rpfSreplydate");
            return this;
        }

        public Criteria andRpfSreplydateLessThan(Date value) {
            addCriterionForJDBCDate("RPF_SREPLYDATE <", value, "rpfSreplydate");
            return this;
        }

        public Criteria andRpfSreplydateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RPF_SREPLYDATE <=", value, "rpfSreplydate");
            return this;
        }

        public Criteria andRpfSreplydateIn(List values) {
            addCriterionForJDBCDate("RPF_SREPLYDATE in", values, "rpfSreplydate");
            return this;
        }

        public Criteria andRpfSreplydateNotIn(List values) {
            addCriterionForJDBCDate("RPF_SREPLYDATE not in", values, "rpfSreplydate");
            return this;
        }

        public Criteria andRpfSreplydateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RPF_SREPLYDATE between", value1, value2, "rpfSreplydate");
            return this;
        }

        public Criteria andRpfSreplydateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RPF_SREPLYDATE not between", value1, value2, "rpfSreplydate");
            return this;
        }

        public Criteria andRpfSalterbyIsNull() {
            addCriterion("RPF_SALTERBY is null");
            return this;
        }

        public Criteria andRpfSalterbyIsNotNull() {
            addCriterion("RPF_SALTERBY is not null");
            return this;
        }

        public Criteria andRpfSalterbyEqualTo(String value) {
            addCriterion("RPF_SALTERBY =", value, "rpfSalterby");
            return this;
        }

        public Criteria andRpfSalterbyNotEqualTo(String value) {
            addCriterion("RPF_SALTERBY <>", value, "rpfSalterby");
            return this;
        }

        public Criteria andRpfSalterbyGreaterThan(String value) {
            addCriterion("RPF_SALTERBY >", value, "rpfSalterby");
            return this;
        }

        public Criteria andRpfSalterbyGreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SALTERBY >=", value, "rpfSalterby");
            return this;
        }

        public Criteria andRpfSalterbyLessThan(String value) {
            addCriterion("RPF_SALTERBY <", value, "rpfSalterby");
            return this;
        }

        public Criteria andRpfSalterbyLessThanOrEqualTo(String value) {
            addCriterion("RPF_SALTERBY <=", value, "rpfSalterby");
            return this;
        }

        public Criteria andRpfSalterbyLike(String value) {
            addCriterion("RPF_SALTERBY like", value, "rpfSalterby");
            return this;
        }

        public Criteria andRpfSalterbyNotLike(String value) {
            addCriterion("RPF_SALTERBY not like", value, "rpfSalterby");
            return this;
        }

        public Criteria andRpfSalterbyIn(List values) {
            addCriterion("RPF_SALTERBY in", values, "rpfSalterby");
            return this;
        }

        public Criteria andRpfSalterbyNotIn(List values) {
            addCriterion("RPF_SALTERBY not in", values, "rpfSalterby");
            return this;
        }

        public Criteria andRpfSalterbyBetween(String value1, String value2) {
            addCriterion("RPF_SALTERBY between", value1, value2, "rpfSalterby");
            return this;
        }

        public Criteria andRpfSalterbyNotBetween(String value1, String value2) {
            addCriterion("RPF_SALTERBY not between", value1, value2, "rpfSalterby");
            return this;
        }

        public Criteria andRpfSalterdateIsNull() {
            addCriterion("RPF_SALTERDATE is null");
            return this;
        }

        public Criteria andRpfSalterdateIsNotNull() {
            addCriterion("RPF_SALTERDATE is not null");
            return this;
        }

        public Criteria andRpfSalterdateEqualTo(Date value) {
            addCriterionForJDBCDate("RPF_SALTERDATE =", value, "rpfSalterdate");
            return this;
        }

        public Criteria andRpfSalterdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("RPF_SALTERDATE <>", value, "rpfSalterdate");
            return this;
        }

        public Criteria andRpfSalterdateGreaterThan(Date value) {
            addCriterionForJDBCDate("RPF_SALTERDATE >", value, "rpfSalterdate");
            return this;
        }

        public Criteria andRpfSalterdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RPF_SALTERDATE >=", value, "rpfSalterdate");
            return this;
        }

        public Criteria andRpfSalterdateLessThan(Date value) {
            addCriterionForJDBCDate("RPF_SALTERDATE <", value, "rpfSalterdate");
            return this;
        }

        public Criteria andRpfSalterdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RPF_SALTERDATE <=", value, "rpfSalterdate");
            return this;
        }

        public Criteria andRpfSalterdateIn(List values) {
            addCriterionForJDBCDate("RPF_SALTERDATE in", values, "rpfSalterdate");
            return this;
        }

        public Criteria andRpfSalterdateNotIn(List values) {
            addCriterionForJDBCDate("RPF_SALTERDATE not in", values, "rpfSalterdate");
            return this;
        }

        public Criteria andRpfSalterdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RPF_SALTERDATE between", value1, value2, "rpfSalterdate");
            return this;
        }

        public Criteria andRpfSalterdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RPF_SALTERDATE not between", value1, value2, "rpfSalterdate");
            return this;
        }

        public Criteria andRpfSdef1IsNull() {
            addCriterion("RPF_SDEF1 is null");
            return this;
        }

        public Criteria andRpfSdef1IsNotNull() {
            addCriterion("RPF_SDEF1 is not null");
            return this;
        }

        public Criteria andRpfSdef1EqualTo(String value) {
            addCriterion("RPF_SDEF1 =", value, "rpfSdef1");
            return this;
        }

        public Criteria andRpfSdef1NotEqualTo(String value) {
            addCriterion("RPF_SDEF1 <>", value, "rpfSdef1");
            return this;
        }

        public Criteria andRpfSdef1GreaterThan(String value) {
            addCriterion("RPF_SDEF1 >", value, "rpfSdef1");
            return this;
        }

        public Criteria andRpfSdef1GreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF1 >=", value, "rpfSdef1");
            return this;
        }

        public Criteria andRpfSdef1LessThan(String value) {
            addCriterion("RPF_SDEF1 <", value, "rpfSdef1");
            return this;
        }

        public Criteria andRpfSdef1LessThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF1 <=", value, "rpfSdef1");
            return this;
        }

        public Criteria andRpfSdef1Like(String value) {
            addCriterion("RPF_SDEF1 like", value, "rpfSdef1");
            return this;
        }

        public Criteria andRpfSdef1NotLike(String value) {
            addCriterion("RPF_SDEF1 not like", value, "rpfSdef1");
            return this;
        }

        public Criteria andRpfSdef1In(List values) {
            addCriterion("RPF_SDEF1 in", values, "rpfSdef1");
            return this;
        }

        public Criteria andRpfSdef1NotIn(List values) {
            addCriterion("RPF_SDEF1 not in", values, "rpfSdef1");
            return this;
        }

        public Criteria andRpfSdef1Between(String value1, String value2) {
            addCriterion("RPF_SDEF1 between", value1, value2, "rpfSdef1");
            return this;
        }

        public Criteria andRpfSdef1NotBetween(String value1, String value2) {
            addCriterion("RPF_SDEF1 not between", value1, value2, "rpfSdef1");
            return this;
        }

        public Criteria andRpfSdef2IsNull() {
            addCriterion("RPF_SDEF2 is null");
            return this;
        }

        public Criteria andRpfSdef2IsNotNull() {
            addCriterion("RPF_SDEF2 is not null");
            return this;
        }

        public Criteria andRpfSdef2EqualTo(String value) {
            addCriterion("RPF_SDEF2 =", value, "rpfSdef2");
            return this;
        }

        public Criteria andRpfSdef2NotEqualTo(String value) {
            addCriterion("RPF_SDEF2 <>", value, "rpfSdef2");
            return this;
        }

        public Criteria andRpfSdef2GreaterThan(String value) {
            addCriterion("RPF_SDEF2 >", value, "rpfSdef2");
            return this;
        }

        public Criteria andRpfSdef2GreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF2 >=", value, "rpfSdef2");
            return this;
        }

        public Criteria andRpfSdef2LessThan(String value) {
            addCriterion("RPF_SDEF2 <", value, "rpfSdef2");
            return this;
        }

        public Criteria andRpfSdef2LessThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF2 <=", value, "rpfSdef2");
            return this;
        }

        public Criteria andRpfSdef2Like(String value) {
            addCriterion("RPF_SDEF2 like", value, "rpfSdef2");
            return this;
        }

        public Criteria andRpfSdef2NotLike(String value) {
            addCriterion("RPF_SDEF2 not like", value, "rpfSdef2");
            return this;
        }

        public Criteria andRpfSdef2In(List values) {
            addCriterion("RPF_SDEF2 in", values, "rpfSdef2");
            return this;
        }

        public Criteria andRpfSdef2NotIn(List values) {
            addCriterion("RPF_SDEF2 not in", values, "rpfSdef2");
            return this;
        }

        public Criteria andRpfSdef2Between(String value1, String value2) {
            addCriterion("RPF_SDEF2 between", value1, value2, "rpfSdef2");
            return this;
        }

        public Criteria andRpfSdef2NotBetween(String value1, String value2) {
            addCriterion("RPF_SDEF2 not between", value1, value2, "rpfSdef2");
            return this;
        }

        public Criteria andRpfSdef3IsNull() {
            addCriterion("RPF_SDEF3 is null");
            return this;
        }

        public Criteria andRpfSdef3IsNotNull() {
            addCriterion("RPF_SDEF3 is not null");
            return this;
        }

        public Criteria andRpfSdef3EqualTo(String value) {
            addCriterion("RPF_SDEF3 =", value, "rpfSdef3");
            return this;
        }

        public Criteria andRpfSdef3NotEqualTo(String value) {
            addCriterion("RPF_SDEF3 <>", value, "rpfSdef3");
            return this;
        }

        public Criteria andRpfSdef3GreaterThan(String value) {
            addCriterion("RPF_SDEF3 >", value, "rpfSdef3");
            return this;
        }

        public Criteria andRpfSdef3GreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF3 >=", value, "rpfSdef3");
            return this;
        }

        public Criteria andRpfSdef3LessThan(String value) {
            addCriterion("RPF_SDEF3 <", value, "rpfSdef3");
            return this;
        }

        public Criteria andRpfSdef3LessThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF3 <=", value, "rpfSdef3");
            return this;
        }

        public Criteria andRpfSdef3Like(String value) {
            addCriterion("RPF_SDEF3 like", value, "rpfSdef3");
            return this;
        }

        public Criteria andRpfSdef3NotLike(String value) {
            addCriterion("RPF_SDEF3 not like", value, "rpfSdef3");
            return this;
        }

        public Criteria andRpfSdef3In(List values) {
            addCriterion("RPF_SDEF3 in", values, "rpfSdef3");
            return this;
        }

        public Criteria andRpfSdef3NotIn(List values) {
            addCriterion("RPF_SDEF3 not in", values, "rpfSdef3");
            return this;
        }

        public Criteria andRpfSdef3Between(String value1, String value2) {
            addCriterion("RPF_SDEF3 between", value1, value2, "rpfSdef3");
            return this;
        }

        public Criteria andRpfSdef3NotBetween(String value1, String value2) {
            addCriterion("RPF_SDEF3 not between", value1, value2, "rpfSdef3");
            return this;
        }

        public Criteria andRpfSdef4IsNull() {
            addCriterion("RPF_SDEF4 is null");
            return this;
        }

        public Criteria andRpfSdef4IsNotNull() {
            addCriterion("RPF_SDEF4 is not null");
            return this;
        }

        public Criteria andRpfSdef4EqualTo(String value) {
            addCriterion("RPF_SDEF4 =", value, "rpfSdef4");
            return this;
        }

        public Criteria andRpfSdef4NotEqualTo(String value) {
            addCriterion("RPF_SDEF4 <>", value, "rpfSdef4");
            return this;
        }

        public Criteria andRpfSdef4GreaterThan(String value) {
            addCriterion("RPF_SDEF4 >", value, "rpfSdef4");
            return this;
        }

        public Criteria andRpfSdef4GreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF4 >=", value, "rpfSdef4");
            return this;
        }

        public Criteria andRpfSdef4LessThan(String value) {
            addCriterion("RPF_SDEF4 <", value, "rpfSdef4");
            return this;
        }

        public Criteria andRpfSdef4LessThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF4 <=", value, "rpfSdef4");
            return this;
        }

        public Criteria andRpfSdef4Like(String value) {
            addCriterion("RPF_SDEF4 like", value, "rpfSdef4");
            return this;
        }

        public Criteria andRpfSdef4NotLike(String value) {
            addCriterion("RPF_SDEF4 not like", value, "rpfSdef4");
            return this;
        }

        public Criteria andRpfSdef4In(List values) {
            addCriterion("RPF_SDEF4 in", values, "rpfSdef4");
            return this;
        }

        public Criteria andRpfSdef4NotIn(List values) {
            addCriterion("RPF_SDEF4 not in", values, "rpfSdef4");
            return this;
        }

        public Criteria andRpfSdef4Between(String value1, String value2) {
            addCriterion("RPF_SDEF4 between", value1, value2, "rpfSdef4");
            return this;
        }

        public Criteria andRpfSdef4NotBetween(String value1, String value2) {
            addCriterion("RPF_SDEF4 not between", value1, value2, "rpfSdef4");
            return this;
        }

        public Criteria andRpfSdef5IsNull() {
            addCriterion("RPF_SDEF5 is null");
            return this;
        }

        public Criteria andRpfSdef5IsNotNull() {
            addCriterion("RPF_SDEF5 is not null");
            return this;
        }

        public Criteria andRpfSdef5EqualTo(String value) {
            addCriterion("RPF_SDEF5 =", value, "rpfSdef5");
            return this;
        }

        public Criteria andRpfSdef5NotEqualTo(String value) {
            addCriterion("RPF_SDEF5 <>", value, "rpfSdef5");
            return this;
        }

        public Criteria andRpfSdef5GreaterThan(String value) {
            addCriterion("RPF_SDEF5 >", value, "rpfSdef5");
            return this;
        }

        public Criteria andRpfSdef5GreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF5 >=", value, "rpfSdef5");
            return this;
        }

        public Criteria andRpfSdef5LessThan(String value) {
            addCriterion("RPF_SDEF5 <", value, "rpfSdef5");
            return this;
        }

        public Criteria andRpfSdef5LessThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF5 <=", value, "rpfSdef5");
            return this;
        }

        public Criteria andRpfSdef5Like(String value) {
            addCriterion("RPF_SDEF5 like", value, "rpfSdef5");
            return this;
        }

        public Criteria andRpfSdef5NotLike(String value) {
            addCriterion("RPF_SDEF5 not like", value, "rpfSdef5");
            return this;
        }

        public Criteria andRpfSdef5In(List values) {
            addCriterion("RPF_SDEF5 in", values, "rpfSdef5");
            return this;
        }

        public Criteria andRpfSdef5NotIn(List values) {
            addCriterion("RPF_SDEF5 not in", values, "rpfSdef5");
            return this;
        }

        public Criteria andRpfSdef5Between(String value1, String value2) {
            addCriterion("RPF_SDEF5 between", value1, value2, "rpfSdef5");
            return this;
        }

        public Criteria andRpfSdef5NotBetween(String value1, String value2) {
            addCriterion("RPF_SDEF5 not between", value1, value2, "rpfSdef5");
            return this;
        }

        public Criteria andRpfSdef6IsNull() {
            addCriterion("RPF_SDEF6 is null");
            return this;
        }

        public Criteria andRpfSdef6IsNotNull() {
            addCriterion("RPF_SDEF6 is not null");
            return this;
        }

        public Criteria andRpfSdef6EqualTo(String value) {
            addCriterion("RPF_SDEF6 =", value, "rpfSdef6");
            return this;
        }

        public Criteria andRpfSdef6NotEqualTo(String value) {
            addCriterion("RPF_SDEF6 <>", value, "rpfSdef6");
            return this;
        }

        public Criteria andRpfSdef6GreaterThan(String value) {
            addCriterion("RPF_SDEF6 >", value, "rpfSdef6");
            return this;
        }

        public Criteria andRpfSdef6GreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF6 >=", value, "rpfSdef6");
            return this;
        }

        public Criteria andRpfSdef6LessThan(String value) {
            addCriterion("RPF_SDEF6 <", value, "rpfSdef6");
            return this;
        }

        public Criteria andRpfSdef6LessThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF6 <=", value, "rpfSdef6");
            return this;
        }

        public Criteria andRpfSdef6Like(String value) {
            addCriterion("RPF_SDEF6 like", value, "rpfSdef6");
            return this;
        }

        public Criteria andRpfSdef6NotLike(String value) {
            addCriterion("RPF_SDEF6 not like", value, "rpfSdef6");
            return this;
        }

        public Criteria andRpfSdef6In(List values) {
            addCriterion("RPF_SDEF6 in", values, "rpfSdef6");
            return this;
        }

        public Criteria andRpfSdef6NotIn(List values) {
            addCriterion("RPF_SDEF6 not in", values, "rpfSdef6");
            return this;
        }

        public Criteria andRpfSdef6Between(String value1, String value2) {
            addCriterion("RPF_SDEF6 between", value1, value2, "rpfSdef6");
            return this;
        }

        public Criteria andRpfSdef6NotBetween(String value1, String value2) {
            addCriterion("RPF_SDEF6 not between", value1, value2, "rpfSdef6");
            return this;
        }

        public Criteria andRpfSdef7IsNull() {
            addCriterion("RPF_SDEF7 is null");
            return this;
        }

        public Criteria andRpfSdef7IsNotNull() {
            addCriterion("RPF_SDEF7 is not null");
            return this;
        }

        public Criteria andRpfSdef7EqualTo(String value) {
            addCriterion("RPF_SDEF7 =", value, "rpfSdef7");
            return this;
        }

        public Criteria andRpfSdef7NotEqualTo(String value) {
            addCriterion("RPF_SDEF7 <>", value, "rpfSdef7");
            return this;
        }

        public Criteria andRpfSdef7GreaterThan(String value) {
            addCriterion("RPF_SDEF7 >", value, "rpfSdef7");
            return this;
        }

        public Criteria andRpfSdef7GreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF7 >=", value, "rpfSdef7");
            return this;
        }

        public Criteria andRpfSdef7LessThan(String value) {
            addCriterion("RPF_SDEF7 <", value, "rpfSdef7");
            return this;
        }

        public Criteria andRpfSdef7LessThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF7 <=", value, "rpfSdef7");
            return this;
        }

        public Criteria andRpfSdef7Like(String value) {
            addCriterion("RPF_SDEF7 like", value, "rpfSdef7");
            return this;
        }

        public Criteria andRpfSdef7NotLike(String value) {
            addCriterion("RPF_SDEF7 not like", value, "rpfSdef7");
            return this;
        }

        public Criteria andRpfSdef7In(List values) {
            addCriterion("RPF_SDEF7 in", values, "rpfSdef7");
            return this;
        }

        public Criteria andRpfSdef7NotIn(List values) {
            addCriterion("RPF_SDEF7 not in", values, "rpfSdef7");
            return this;
        }

        public Criteria andRpfSdef7Between(String value1, String value2) {
            addCriterion("RPF_SDEF7 between", value1, value2, "rpfSdef7");
            return this;
        }

        public Criteria andRpfSdef7NotBetween(String value1, String value2) {
            addCriterion("RPF_SDEF7 not between", value1, value2, "rpfSdef7");
            return this;
        }

        public Criteria andRpfSdef8IsNull() {
            addCriterion("RPF_SDEF8 is null");
            return this;
        }

        public Criteria andRpfSdef8IsNotNull() {
            addCriterion("RPF_SDEF8 is not null");
            return this;
        }

        public Criteria andRpfSdef8EqualTo(String value) {
            addCriterion("RPF_SDEF8 =", value, "rpfSdef8");
            return this;
        }

        public Criteria andRpfSdef8NotEqualTo(String value) {
            addCriterion("RPF_SDEF8 <>", value, "rpfSdef8");
            return this;
        }

        public Criteria andRpfSdef8GreaterThan(String value) {
            addCriterion("RPF_SDEF8 >", value, "rpfSdef8");
            return this;
        }

        public Criteria andRpfSdef8GreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF8 >=", value, "rpfSdef8");
            return this;
        }

        public Criteria andRpfSdef8LessThan(String value) {
            addCriterion("RPF_SDEF8 <", value, "rpfSdef8");
            return this;
        }

        public Criteria andRpfSdef8LessThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF8 <=", value, "rpfSdef8");
            return this;
        }

        public Criteria andRpfSdef8Like(String value) {
            addCriterion("RPF_SDEF8 like", value, "rpfSdef8");
            return this;
        }

        public Criteria andRpfSdef8NotLike(String value) {
            addCriterion("RPF_SDEF8 not like", value, "rpfSdef8");
            return this;
        }

        public Criteria andRpfSdef8In(List values) {
            addCriterion("RPF_SDEF8 in", values, "rpfSdef8");
            return this;
        }

        public Criteria andRpfSdef8NotIn(List values) {
            addCriterion("RPF_SDEF8 not in", values, "rpfSdef8");
            return this;
        }

        public Criteria andRpfSdef8Between(String value1, String value2) {
            addCriterion("RPF_SDEF8 between", value1, value2, "rpfSdef8");
            return this;
        }

        public Criteria andRpfSdef8NotBetween(String value1, String value2) {
            addCriterion("RPF_SDEF8 not between", value1, value2, "rpfSdef8");
            return this;
        }

        public Criteria andRpfSdef9IsNull() {
            addCriterion("RPF_SDEF9 is null");
            return this;
        }

        public Criteria andRpfSdef9IsNotNull() {
            addCriterion("RPF_SDEF9 is not null");
            return this;
        }

        public Criteria andRpfSdef9EqualTo(String value) {
            addCriterion("RPF_SDEF9 =", value, "rpfSdef9");
            return this;
        }

        public Criteria andRpfSdef9NotEqualTo(String value) {
            addCriterion("RPF_SDEF9 <>", value, "rpfSdef9");
            return this;
        }

        public Criteria andRpfSdef9GreaterThan(String value) {
            addCriterion("RPF_SDEF9 >", value, "rpfSdef9");
            return this;
        }

        public Criteria andRpfSdef9GreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF9 >=", value, "rpfSdef9");
            return this;
        }

        public Criteria andRpfSdef9LessThan(String value) {
            addCriterion("RPF_SDEF9 <", value, "rpfSdef9");
            return this;
        }

        public Criteria andRpfSdef9LessThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF9 <=", value, "rpfSdef9");
            return this;
        }

        public Criteria andRpfSdef9Like(String value) {
            addCriterion("RPF_SDEF9 like", value, "rpfSdef9");
            return this;
        }

        public Criteria andRpfSdef9NotLike(String value) {
            addCriterion("RPF_SDEF9 not like", value, "rpfSdef9");
            return this;
        }

        public Criteria andRpfSdef9In(List values) {
            addCriterion("RPF_SDEF9 in", values, "rpfSdef9");
            return this;
        }

        public Criteria andRpfSdef9NotIn(List values) {
            addCriterion("RPF_SDEF9 not in", values, "rpfSdef9");
            return this;
        }

        public Criteria andRpfSdef9Between(String value1, String value2) {
            addCriterion("RPF_SDEF9 between", value1, value2, "rpfSdef9");
            return this;
        }

        public Criteria andRpfSdef9NotBetween(String value1, String value2) {
            addCriterion("RPF_SDEF9 not between", value1, value2, "rpfSdef9");
            return this;
        }

        public Criteria andRpfSdef10IsNull() {
            addCriterion("RPF_SDEF10 is null");
            return this;
        }

        public Criteria andRpfSdef10IsNotNull() {
            addCriterion("RPF_SDEF10 is not null");
            return this;
        }

        public Criteria andRpfSdef10EqualTo(String value) {
            addCriterion("RPF_SDEF10 =", value, "rpfSdef10");
            return this;
        }

        public Criteria andRpfSdef10NotEqualTo(String value) {
            addCriterion("RPF_SDEF10 <>", value, "rpfSdef10");
            return this;
        }

        public Criteria andRpfSdef10GreaterThan(String value) {
            addCriterion("RPF_SDEF10 >", value, "rpfSdef10");
            return this;
        }

        public Criteria andRpfSdef10GreaterThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF10 >=", value, "rpfSdef10");
            return this;
        }

        public Criteria andRpfSdef10LessThan(String value) {
            addCriterion("RPF_SDEF10 <", value, "rpfSdef10");
            return this;
        }

        public Criteria andRpfSdef10LessThanOrEqualTo(String value) {
            addCriterion("RPF_SDEF10 <=", value, "rpfSdef10");
            return this;
        }

        public Criteria andRpfSdef10Like(String value) {
            addCriterion("RPF_SDEF10 like", value, "rpfSdef10");
            return this;
        }

        public Criteria andRpfSdef10NotLike(String value) {
            addCriterion("RPF_SDEF10 not like", value, "rpfSdef10");
            return this;
        }

        public Criteria andRpfSdef10In(List values) {
            addCriterion("RPF_SDEF10 in", values, "rpfSdef10");
            return this;
        }

        public Criteria andRpfSdef10NotIn(List values) {
            addCriterion("RPF_SDEF10 not in", values, "rpfSdef10");
            return this;
        }

        public Criteria andRpfSdef10Between(String value1, String value2) {
            addCriterion("RPF_SDEF10 between", value1, value2, "rpfSdef10");
            return this;
        }

        public Criteria andRpfSdef10NotBetween(String value1, String value2) {
            addCriterion("RPF_SDEF10 not between", value1, value2, "rpfSdef10");
            return this;
        }
    }
}