package com.rc.project.vo;

import java.math.BigDecimal;
import java.util.Date;

public class RpReport {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.UD_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String udSno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.UD_SNO1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String udSno1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SREPORTUNITNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSreportunitname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SPROJECTNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSprojectname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SYEAR
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSyear;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.EMP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String empSno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SPERSON
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSperson;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.UD_SNO2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String udSno2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SPERDEPARTNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSperdepartname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SPROTYPE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSprotype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SREPORTTOTAL
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpSreporttotal;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_STOTAL
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpStotal;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_STYPE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpStype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SISDEL
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSisdel;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SISVALID
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSisvalid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SREPLYBY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSreplyby;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SREPLYDATE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date rpSreplydate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SALTERBY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSalterby;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SALTERDATE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date rpSalterdate;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RPB_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpbSno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef4;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef5;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF6
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef6;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF7
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef7;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF8
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef8;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF9
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef9;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF10
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef10;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF11
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef11;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF12
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef12;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF13
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef13;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF14
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private String rpSdef14;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_SDEF15
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpSdef15;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_DDEF16
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date rpDdef16;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_DDEF17
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date rpDdef17;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_DDEF18
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date rpDdef18;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_DDEF19
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date rpDdef19;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_DDEF20
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private Date rpDdef20;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_NDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpNdef1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_NDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpNdef2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_NDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpNdef3;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_NDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpNdef4;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_NDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpNdef5;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_NDEF6
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpNdef6;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_NDEF7
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpNdef7;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_NDEF8
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpNdef8;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_NDEF9
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpNdef9;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_NDEF10
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpNdef10;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column RP_REPORT.RP_NDEF11
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	private BigDecimal rpNdef11;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SNO
	 * @return  the value of RP_REPORT.RP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSno() {
		return rpSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SNO
	 * @param rpSno  the value for RP_REPORT.RP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSno(String rpSno) {
		this.rpSno = rpSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.UD_SNO
	 * @return  the value of RP_REPORT.UD_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getUdSno() {
		return udSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.UD_SNO
	 * @param udSno  the value for RP_REPORT.UD_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setUdSno(String udSno) {
		this.udSno = udSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.UD_SNO1
	 * @return  the value of RP_REPORT.UD_SNO1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getUdSno1() {
		return udSno1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.UD_SNO1
	 * @param udSno1  the value for RP_REPORT.UD_SNO1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setUdSno1(String udSno1) {
		this.udSno1 = udSno1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SREPORTUNITNAME
	 * @return  the value of RP_REPORT.RP_SREPORTUNITNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSreportunitname() {
		return rpSreportunitname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SREPORTUNITNAME
	 * @param rpSreportunitname  the value for RP_REPORT.RP_SREPORTUNITNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSreportunitname(String rpSreportunitname) {
		this.rpSreportunitname = rpSreportunitname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SPROJECTNAME
	 * @return  the value of RP_REPORT.RP_SPROJECTNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSprojectname() {
		return rpSprojectname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SPROJECTNAME
	 * @param rpSprojectname  the value for RP_REPORT.RP_SPROJECTNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSprojectname(String rpSprojectname) {
		this.rpSprojectname = rpSprojectname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SYEAR
	 * @return  the value of RP_REPORT.RP_SYEAR
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSyear() {
		return rpSyear;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SYEAR
	 * @param rpSyear  the value for RP_REPORT.RP_SYEAR
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSyear(String rpSyear) {
		this.rpSyear = rpSyear;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.EMP_SNO
	 * @return  the value of RP_REPORT.EMP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getEmpSno() {
		return empSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.EMP_SNO
	 * @param empSno  the value for RP_REPORT.EMP_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setEmpSno(String empSno) {
		this.empSno = empSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SPERSON
	 * @return  the value of RP_REPORT.RP_SPERSON
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSperson() {
		return rpSperson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SPERSON
	 * @param rpSperson  the value for RP_REPORT.RP_SPERSON
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSperson(String rpSperson) {
		this.rpSperson = rpSperson;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.UD_SNO2
	 * @return  the value of RP_REPORT.UD_SNO2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getUdSno2() {
		return udSno2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.UD_SNO2
	 * @param udSno2  the value for RP_REPORT.UD_SNO2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setUdSno2(String udSno2) {
		this.udSno2 = udSno2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SPERDEPARTNAME
	 * @return  the value of RP_REPORT.RP_SPERDEPARTNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSperdepartname() {
		return rpSperdepartname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SPERDEPARTNAME
	 * @param rpSperdepartname  the value for RP_REPORT.RP_SPERDEPARTNAME
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSperdepartname(String rpSperdepartname) {
		this.rpSperdepartname = rpSperdepartname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SPROTYPE
	 * @return  the value of RP_REPORT.RP_SPROTYPE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSprotype() {
		return rpSprotype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SPROTYPE
	 * @param rpSprotype  the value for RP_REPORT.RP_SPROTYPE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSprotype(String rpSprotype) {
		this.rpSprotype = rpSprotype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SREPORTTOTAL
	 * @return  the value of RP_REPORT.RP_SREPORTTOTAL
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpSreporttotal() {
		return rpSreporttotal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SREPORTTOTAL
	 * @param rpSreporttotal  the value for RP_REPORT.RP_SREPORTTOTAL
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSreporttotal(BigDecimal rpSreporttotal) {
		this.rpSreporttotal = rpSreporttotal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_STOTAL
	 * @return  the value of RP_REPORT.RP_STOTAL
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpStotal() {
		return rpStotal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_STOTAL
	 * @param rpStotal  the value for RP_REPORT.RP_STOTAL
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpStotal(BigDecimal rpStotal) {
		this.rpStotal = rpStotal;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_STYPE
	 * @return  the value of RP_REPORT.RP_STYPE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpStype() {
		return rpStype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_STYPE
	 * @param rpStype  the value for RP_REPORT.RP_STYPE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpStype(String rpStype) {
		this.rpStype = rpStype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SISDEL
	 * @return  the value of RP_REPORT.RP_SISDEL
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSisdel() {
		return rpSisdel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SISDEL
	 * @param rpSisdel  the value for RP_REPORT.RP_SISDEL
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSisdel(String rpSisdel) {
		this.rpSisdel = rpSisdel;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SISVALID
	 * @return  the value of RP_REPORT.RP_SISVALID
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSisvalid() {
		return rpSisvalid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SISVALID
	 * @param rpSisvalid  the value for RP_REPORT.RP_SISVALID
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSisvalid(String rpSisvalid) {
		this.rpSisvalid = rpSisvalid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SREPLYBY
	 * @return  the value of RP_REPORT.RP_SREPLYBY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSreplyby() {
		return rpSreplyby;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SREPLYBY
	 * @param rpSreplyby  the value for RP_REPORT.RP_SREPLYBY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSreplyby(String rpSreplyby) {
		this.rpSreplyby = rpSreplyby;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SREPLYDATE
	 * @return  the value of RP_REPORT.RP_SREPLYDATE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getRpSreplydate() {
		return rpSreplydate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SREPLYDATE
	 * @param rpSreplydate  the value for RP_REPORT.RP_SREPLYDATE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSreplydate(Date rpSreplydate) {
		this.rpSreplydate = rpSreplydate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SALTERBY
	 * @return  the value of RP_REPORT.RP_SALTERBY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSalterby() {
		return rpSalterby;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SALTERBY
	 * @param rpSalterby  the value for RP_REPORT.RP_SALTERBY
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSalterby(String rpSalterby) {
		this.rpSalterby = rpSalterby;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SALTERDATE
	 * @return  the value of RP_REPORT.RP_SALTERDATE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getRpSalterdate() {
		return rpSalterdate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SALTERDATE
	 * @param rpSalterdate  the value for RP_REPORT.RP_SALTERDATE
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSalterdate(Date rpSalterdate) {
		this.rpSalterdate = rpSalterdate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RPB_SNO
	 * @return  the value of RP_REPORT.RPB_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpbSno() {
		return rpbSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RPB_SNO
	 * @param rpbSno  the value for RP_REPORT.RPB_SNO
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpbSno(String rpbSno) {
		this.rpbSno = rpbSno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF1
	 * @return  the value of RP_REPORT.RP_SDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef1() {
		return rpSdef1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF1
	 * @param rpSdef1  the value for RP_REPORT.RP_SDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef1(String rpSdef1) {
		this.rpSdef1 = rpSdef1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF2
	 * @return  the value of RP_REPORT.RP_SDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef2() {
		return rpSdef2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF2
	 * @param rpSdef2  the value for RP_REPORT.RP_SDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef2(String rpSdef2) {
		this.rpSdef2 = rpSdef2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF3
	 * @return  the value of RP_REPORT.RP_SDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef3() {
		return rpSdef3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF3
	 * @param rpSdef3  the value for RP_REPORT.RP_SDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef3(String rpSdef3) {
		this.rpSdef3 = rpSdef3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF4
	 * @return  the value of RP_REPORT.RP_SDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef4() {
		return rpSdef4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF4
	 * @param rpSdef4  the value for RP_REPORT.RP_SDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef4(String rpSdef4) {
		this.rpSdef4 = rpSdef4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF5
	 * @return  the value of RP_REPORT.RP_SDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef5() {
		return rpSdef5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF5
	 * @param rpSdef5  the value for RP_REPORT.RP_SDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef5(String rpSdef5) {
		this.rpSdef5 = rpSdef5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF6
	 * @return  the value of RP_REPORT.RP_SDEF6
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef6() {
		return rpSdef6;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF6
	 * @param rpSdef6  the value for RP_REPORT.RP_SDEF6
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef6(String rpSdef6) {
		this.rpSdef6 = rpSdef6;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF7
	 * @return  the value of RP_REPORT.RP_SDEF7
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef7() {
		return rpSdef7;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF7
	 * @param rpSdef7  the value for RP_REPORT.RP_SDEF7
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef7(String rpSdef7) {
		this.rpSdef7 = rpSdef7;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF8
	 * @return  the value of RP_REPORT.RP_SDEF8
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef8() {
		return rpSdef8;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF8
	 * @param rpSdef8  the value for RP_REPORT.RP_SDEF8
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef8(String rpSdef8) {
		this.rpSdef8 = rpSdef8;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF9
	 * @return  the value of RP_REPORT.RP_SDEF9
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef9() {
		return rpSdef9;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF9
	 * @param rpSdef9  the value for RP_REPORT.RP_SDEF9
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef9(String rpSdef9) {
		this.rpSdef9 = rpSdef9;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF10
	 * @return  the value of RP_REPORT.RP_SDEF10
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef10() {
		return rpSdef10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF10
	 * @param rpSdef10  the value for RP_REPORT.RP_SDEF10
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef10(String rpSdef10) {
		this.rpSdef10 = rpSdef10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF11
	 * @return  the value of RP_REPORT.RP_SDEF11
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef11() {
		return rpSdef11;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF11
	 * @param rpSdef11  the value for RP_REPORT.RP_SDEF11
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef11(String rpSdef11) {
		this.rpSdef11 = rpSdef11;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF12
	 * @return  the value of RP_REPORT.RP_SDEF12
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef12() {
		return rpSdef12;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF12
	 * @param rpSdef12  the value for RP_REPORT.RP_SDEF12
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef12(String rpSdef12) {
		this.rpSdef12 = rpSdef12;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF13
	 * @return  the value of RP_REPORT.RP_SDEF13
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef13() {
		return rpSdef13;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF13
	 * @param rpSdef13  the value for RP_REPORT.RP_SDEF13
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef13(String rpSdef13) {
		this.rpSdef13 = rpSdef13;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF14
	 * @return  the value of RP_REPORT.RP_SDEF14
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public String getRpSdef14() {
		return rpSdef14;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF14
	 * @param rpSdef14  the value for RP_REPORT.RP_SDEF14
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef14(String rpSdef14) {
		this.rpSdef14 = rpSdef14;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_SDEF15
	 * @return  the value of RP_REPORT.RP_SDEF15
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpSdef15() {
		return rpSdef15;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_SDEF15
	 * @param rpSdef15  the value for RP_REPORT.RP_SDEF15
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpSdef15(BigDecimal rpSdef15) {
		this.rpSdef15 = rpSdef15;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_DDEF16
	 * @return  the value of RP_REPORT.RP_DDEF16
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getRpDdef16() {
		return rpDdef16;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_DDEF16
	 * @param rpDdef16  the value for RP_REPORT.RP_DDEF16
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpDdef16(Date rpDdef16) {
		this.rpDdef16 = rpDdef16;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_DDEF17
	 * @return  the value of RP_REPORT.RP_DDEF17
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getRpDdef17() {
		return rpDdef17;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_DDEF17
	 * @param rpDdef17  the value for RP_REPORT.RP_DDEF17
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpDdef17(Date rpDdef17) {
		this.rpDdef17 = rpDdef17;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_DDEF18
	 * @return  the value of RP_REPORT.RP_DDEF18
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getRpDdef18() {
		return rpDdef18;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_DDEF18
	 * @param rpDdef18  the value for RP_REPORT.RP_DDEF18
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpDdef18(Date rpDdef18) {
		this.rpDdef18 = rpDdef18;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_DDEF19
	 * @return  the value of RP_REPORT.RP_DDEF19
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getRpDdef19() {
		return rpDdef19;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_DDEF19
	 * @param rpDdef19  the value for RP_REPORT.RP_DDEF19
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpDdef19(Date rpDdef19) {
		this.rpDdef19 = rpDdef19;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_DDEF20
	 * @return  the value of RP_REPORT.RP_DDEF20
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public Date getRpDdef20() {
		return rpDdef20;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_DDEF20
	 * @param rpDdef20  the value for RP_REPORT.RP_DDEF20
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpDdef20(Date rpDdef20) {
		this.rpDdef20 = rpDdef20;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_NDEF1
	 * @return  the value of RP_REPORT.RP_NDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpNdef1() {
		return rpNdef1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_NDEF1
	 * @param rpNdef1  the value for RP_REPORT.RP_NDEF1
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpNdef1(BigDecimal rpNdef1) {
		this.rpNdef1 = rpNdef1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_NDEF2
	 * @return  the value of RP_REPORT.RP_NDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpNdef2() {
		return rpNdef2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_NDEF2
	 * @param rpNdef2  the value for RP_REPORT.RP_NDEF2
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpNdef2(BigDecimal rpNdef2) {
		this.rpNdef2 = rpNdef2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_NDEF3
	 * @return  the value of RP_REPORT.RP_NDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpNdef3() {
		return rpNdef3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_NDEF3
	 * @param rpNdef3  the value for RP_REPORT.RP_NDEF3
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpNdef3(BigDecimal rpNdef3) {
		this.rpNdef3 = rpNdef3;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_NDEF4
	 * @return  the value of RP_REPORT.RP_NDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpNdef4() {
		return rpNdef4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_NDEF4
	 * @param rpNdef4  the value for RP_REPORT.RP_NDEF4
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpNdef4(BigDecimal rpNdef4) {
		this.rpNdef4 = rpNdef4;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_NDEF5
	 * @return  the value of RP_REPORT.RP_NDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpNdef5() {
		return rpNdef5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_NDEF5
	 * @param rpNdef5  the value for RP_REPORT.RP_NDEF5
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpNdef5(BigDecimal rpNdef5) {
		this.rpNdef5 = rpNdef5;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_NDEF6
	 * @return  the value of RP_REPORT.RP_NDEF6
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpNdef6() {
		return rpNdef6;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_NDEF6
	 * @param rpNdef6  the value for RP_REPORT.RP_NDEF6
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpNdef6(BigDecimal rpNdef6) {
		this.rpNdef6 = rpNdef6;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_NDEF7
	 * @return  the value of RP_REPORT.RP_NDEF7
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpNdef7() {
		return rpNdef7;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_NDEF7
	 * @param rpNdef7  the value for RP_REPORT.RP_NDEF7
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpNdef7(BigDecimal rpNdef7) {
		this.rpNdef7 = rpNdef7;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_NDEF8
	 * @return  the value of RP_REPORT.RP_NDEF8
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpNdef8() {
		return rpNdef8;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_NDEF8
	 * @param rpNdef8  the value for RP_REPORT.RP_NDEF8
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpNdef8(BigDecimal rpNdef8) {
		this.rpNdef8 = rpNdef8;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_NDEF9
	 * @return  the value of RP_REPORT.RP_NDEF9
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpNdef9() {
		return rpNdef9;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_NDEF9
	 * @param rpNdef9  the value for RP_REPORT.RP_NDEF9
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpNdef9(BigDecimal rpNdef9) {
		this.rpNdef9 = rpNdef9;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_NDEF10
	 * @return  the value of RP_REPORT.RP_NDEF10
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpNdef10() {
		return rpNdef10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_NDEF10
	 * @param rpNdef10  the value for RP_REPORT.RP_NDEF10
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpNdef10(BigDecimal rpNdef10) {
		this.rpNdef10 = rpNdef10;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column RP_REPORT.RP_NDEF11
	 * @return  the value of RP_REPORT.RP_NDEF11
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public BigDecimal getRpNdef11() {
		return rpNdef11;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column RP_REPORT.RP_NDEF11
	 * @param rpNdef11  the value for RP_REPORT.RP_NDEF11
	 * @ibatorgenerated  Wed Mar 12 15:11:45 CST 2014
	 */
	public void setRpNdef11(BigDecimal rpNdef11) {
		this.rpNdef11 = rpNdef11;
	}
}