package com.rc.project.dao;

import com.rc.project.vo.EpAccessory;
import com.rc.project.vo.EpAccessoryExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpAccessoryDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpAccessoryDAO() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int countByExample(EpAccessoryExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("accessory_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByExample(EpAccessoryExample example) {
        int rows = getSqlMapClientTemplate().delete("accessory_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal asNid) {
        EpAccessory key = new EpAccessory();
        key.setAsNid(asNid);
        int rows = getSqlMapClientTemplate().delete("accessory_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insert(EpAccessory record) {
        getSqlMapClientTemplate().insert("accessory_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insertSelective(EpAccessory record) {
        getSqlMapClientTemplate().insert("accessory_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public List selectByExample(EpAccessoryExample example) {
        List list = getSqlMapClientTemplate().queryForList("accessory_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpAccessory selectByPrimaryKey(BigDecimal asNid) {
        EpAccessory key = new EpAccessory();
        key.setAsNid(asNid);
        EpAccessory record = (EpAccessory) getSqlMapClientTemplate().queryForObject("accessory_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExampleSelective(EpAccessory record, EpAccessoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("accessory_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExample(EpAccessory record, EpAccessoryExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("accessory_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKeySelective(EpAccessory record) {
        int rows = getSqlMapClientTemplate().update("accessory_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKey(EpAccessory record) {
        int rows = getSqlMapClientTemplate().update("accessory_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table EP_ACCESSORY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private static class UpdateByExampleParms extends EpAccessoryExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpAccessoryExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}