package com.rc.project.dao;

import com.rc.project.vo.EpBidWin;
import com.rc.project.vo.EpBidwinExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpBidWinDAO extends SqlMapClientDaoSupport  {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpBidWinDAO() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int countByExample(EpBidwinExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_BIDWIN_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByExample(EpBidwinExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_BIDWIN_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal ebwNid) {
        EpBidWin key = new EpBidWin();
        key.setEbwNid(ebwNid);
        int rows = getSqlMapClientTemplate().delete("EP_BIDWIN_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insert(EpBidWin record) {
        getSqlMapClientTemplate().insert("EP_BIDWIN_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insertSelective(EpBidWin record) {
        getSqlMapClientTemplate().insert("EP_BIDWIN_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public List selectByExample(EpBidwinExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_BIDWIN_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpBidWin selectByPrimaryKey(BigDecimal ebwNid) {
        EpBidWin key = new EpBidWin();
        key.setEbwNid(ebwNid);
        EpBidWin record = (EpBidWin) getSqlMapClientTemplate().queryForObject("EP_BIDWIN_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExampleSelective(EpBidWin record, EpBidwinExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_BIDWIN_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExample(EpBidWin record, EpBidwinExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_BIDWIN_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKeySelective(EpBidWin record) {
        int rows = getSqlMapClientTemplate().update("EP_BIDWIN_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKey(EpBidWin record) {
        int rows = getSqlMapClientTemplate().update("EP_BIDWIN_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table EP_BIDWIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private static class UpdateByExampleParms extends EpBidwinExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpBidwinExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}