package com.rc.project.dao;

import com.rc.project.vo.EpEntrancec;
import com.rc.project.vo.EpEntrancecExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpEntrancecDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpEntrancecDAO() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int countByExample(EpEntrancecExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_ENTRANCEC_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByExample(EpEntrancecExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_ENTRANCEC_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal etcNid) {
        EpEntrancec key = new EpEntrancec();
        key.setEtcNid(etcNid);
        int rows = getSqlMapClientTemplate().delete("EP_ENTRANCEC_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insert(EpEntrancec record) {
        getSqlMapClientTemplate().insert("EP_ENTRANCEC_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insertSelective(EpEntrancec record) {
        getSqlMapClientTemplate().insert("EP_ENTRANCEC_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public List selectByExample(EpEntrancecExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_ENTRANCEC_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpEntrancec selectByPrimaryKey(BigDecimal etcNid) {
        EpEntrancec key = new EpEntrancec();
        key.setEtcNid(etcNid);
        EpEntrancec record = (EpEntrancec) getSqlMapClientTemplate().queryForObject("EP_ENTRANCEC_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExampleSelective(EpEntrancec record, EpEntrancecExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_ENTRANCEC_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExample(EpEntrancec record, EpEntrancecExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_ENTRANCEC_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKeySelective(EpEntrancec record) {
        int rows = getSqlMapClientTemplate().update("EP_ENTRANCEC_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKey(EpEntrancec record) {
        int rows = getSqlMapClientTemplate().update("EP_ENTRANCEC_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table EP_ENTRANCEC
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private static class UpdateByExampleParms extends EpEntrancecExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpEntrancecExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}