package com.rc.project.dao;

import com.rc.project.vo.EpPayMoney;
import com.rc.project.vo.EpPaymoneyExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpPayMoneyDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpPayMoneyDAO() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int countByExample(EpPaymoneyExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_PAYMONEY_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByExample(EpPaymoneyExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_PAYMONEY_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal pmNid) {
        EpPayMoney key = new EpPayMoney();
        key.setPmNid(pmNid);
        int rows = getSqlMapClientTemplate().delete("EP_PAYMONEY_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insert(EpPayMoney record) {
        getSqlMapClientTemplate().insert("EP_PAYMONEY_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insertSelective(EpPayMoney record) {
        getSqlMapClientTemplate().insert("EP_PAYMONEY_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public List selectByExample(EpPaymoneyExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_PAYMONEY_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpPayMoney selectByPrimaryKey(BigDecimal pmNid) {
        EpPayMoney key = new EpPayMoney();
        key.setPmNid(pmNid);
        EpPayMoney record = (EpPayMoney) getSqlMapClientTemplate().queryForObject("EP_PAYMONEY_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExampleSelective(EpPayMoney record, EpPaymoneyExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_PAYMONEY_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExample(EpPayMoney record, EpPaymoneyExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_PAYMONEY_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKeySelective(EpPayMoney record) {
        int rows = getSqlMapClientTemplate().update("EP_PAYMONEY_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKey(EpPayMoney record) {
        int rows = getSqlMapClientTemplate().update("EP_PAYMONEY_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table EP_PAYMONEY
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private static class UpdateByExampleParms extends EpPaymoneyExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpPaymoneyExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}