package com.rc.project.dao;

import com.rc.project.vo.EpProjectDetail;
import com.rc.project.vo.EpProjectdetailExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpProjectDetailDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpProjectDetailDAO() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int countByExample(EpProjectdetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_PROJECTDETAIL_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByExample(EpProjectdetailExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_PROJECTDETAIL_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByPrimaryKey(EpProjectDetail key) {
              int rows = getSqlMapClientTemplate().delete("EP_PROJECTDETAIL_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insert(EpProjectDetail record) {
        getSqlMapClientTemplate().insert("EP_PROJECTDETAIL_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insertSelective(EpProjectDetail record) {
        getSqlMapClientTemplate().insert("EP_PROJECTDETAIL_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public List selectByExample(EpProjectdetailExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_PROJECTDETAIL_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpProjectDetail selectByPrimaryKey(EpProjectDetail key) {
    
        EpProjectDetail record = (EpProjectDetail) getSqlMapClientTemplate().queryForObject("EP_PROJECTDETAIL_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExampleSelective(EpProjectDetail record, EpProjectdetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_PROJECTDETAIL_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExample(EpProjectDetail record, EpProjectdetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_PROJECTDETAIL_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKeySelective(EpProjectDetail record) {
        int rows = getSqlMapClientTemplate().update("EP_PROJECTDETAIL_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKey(EpProjectDetail record) {
        int rows = getSqlMapClientTemplate().update("EP_PROJECTDETAIL_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table EP_PROJECTDETAIL
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private static class UpdateByExampleParms extends EpProjectdetailExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpProjectdetailExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}