package com.rc.project.dao;

import com.rc.project.vo.EpProcess;
import com.rc.project.vo.EpProcessExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EpProcessDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpProcessDAO() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int countByExample(EpProcessExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("EP_PROCESS_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByExample(EpProcessExample example) {
        int rows = getSqlMapClientTemplate().delete("EP_PROCESS_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByPrimaryKey(BigDecimal ssNid) {
        EpProcess key = new EpProcess();
        key.setSsNid(ssNid);
        int rows = getSqlMapClientTemplate().delete("EP_PROCESS_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insert(EpProcess record) {
        getSqlMapClientTemplate().insert("EP_PROCESS_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insertSelective(EpProcess record) {
        getSqlMapClientTemplate().insert("EP_PROCESS_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public List selectByExample(EpProcessExample example) {
        List list = getSqlMapClientTemplate().queryForList("EP_PROCESS_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public EpProcess selectByPrimaryKey(BigDecimal ssNid) {
        EpProcess key = new EpProcess();
        key.setSsNid(ssNid);
        EpProcess record = (EpProcess) getSqlMapClientTemplate().queryForObject("EP_PROCESS_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExampleSelective(EpProcess record, EpProcessExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_PROCESS_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExample(EpProcess record, EpProcessExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("EP_PROCESS_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKeySelective(EpProcess record) {
        int rows = getSqlMapClientTemplate().update("EP_PROCESS_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKey(EpProcess record) {
        int rows = getSqlMapClientTemplate().update("EP_PROCESS_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table EP_PROCESS
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private static class UpdateByExampleParms extends EpProcessExample {
        private Object record;

        public UpdateByExampleParms(Object record, EpProcessExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}