package com.rc.project.dao;

import com.rc.project.vo.RpReportBegin;
import com.rc.project.vo.RpReportBeginExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RpReportBeginDAO extends SqlMapClientDaoSupport {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public RpReportBeginDAO() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int countByExample(RpReportBeginExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("RP_REPORTBEGIN_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByExample(RpReportBeginExample example) {
        int rows = getSqlMapClientTemplate().delete("RP_REPORTBEGIN_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int deleteByPrimaryKey(String rpbSno) {
        RpReportBegin key = new RpReportBegin();
        key.setRpbSno(rpbSno);
        int rows = getSqlMapClientTemplate().delete("RP_REPORTBEGIN_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insert(RpReportBegin record) {
        getSqlMapClientTemplate().insert("RP_REPORTBEGIN_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public void insertSelective(RpReportBegin record) {
        getSqlMapClientTemplate().insert("RP_REPORTBEGIN_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public List selectByExample(RpReportBeginExample example) {
        List list = getSqlMapClientTemplate().queryForList("RP_REPORTBEGIN_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public RpReportBegin selectByPrimaryKey(String rpbSno) {
        RpReportBegin key = new RpReportBegin();
        key.setRpbSno(rpbSno);
        RpReportBegin record = (RpReportBegin) getSqlMapClientTemplate().queryForObject("RP_REPORTBEGIN_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExampleSelective(RpReportBegin record, RpReportBeginExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("RP_REPORTBEGIN_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByExample(RpReportBegin record, RpReportBeginExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("RP_REPORTBEGIN_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKeySelective(RpReportBegin record) {
        int rows = getSqlMapClientTemplate().update("RP_REPORTBEGIN_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    public int updateByPrimaryKey(RpReportBegin record) {
        int rows = getSqlMapClientTemplate().update("RP_REPORTBEGIN_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table RP_REPORTBEGIN
     *
     * @ibatorgenerated Wed Mar 12 15:11:45 CST 2014
     */
    private static class UpdateByExampleParms extends RpReportBeginExample {
        private Object record;

        public UpdateByExampleParms(Object record, RpReportBeginExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}